### ISSUE TITLE
Great work! What about turn on command?

### ISSUE THREAD

**Issue by acidquest** [smartHomeHub/SmartIR#1]
Thank you for your work, great. Configuration file is more readable for use in this version. What about turn on command? Now i can on AC with standard broadlink switch, but i want do it with climate component. In my AC on and off are different

**Comment by smartHomeHub** [comment]
Interesting. Isn't your remote control send the ON command every time you change the mode, temperature etc..? What's your AC model?

**Comment by acidquest** [comment]
I'm not at home now, I can not give you the exact model number. AC Fujitsu General. The remote control is off in its normal state. The display on the remote control is also turned off. I press the button - turn on, then the air conditioner turns on and the display appears on the remote and it can control the modes and temperature.

I read some commands from the remote and put them in the configuration file. Everything works except the tuned on AC.
For example the command:

 "cool": {
      "auto": {
          "18": "JgD2AGs2Dg4NDg0pDg4NKQ0ODQ8NDg0pDSkNDw0ODQ4NKQ4pDQ4NDg0PDQ4NDg4ODQ4NDg0PDQ4NDg4ODQ4NKQ0PDQ4NDg0PDQ4NDg0PDSkNDg0ODg4NDg0ODikNKQ0pDSkNKQ4pDQ4NDg0PDSkNDg0ODg4NDg0ODg4NDg0ODikNKQ0ODQ4ODgwPDQ8NDg0ODSkODg0ODSkNDw0ODQ4ODg0ODQ4ODg0ODA8ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ8NDg0ODA8ODg0ODQ8NKQ0pDSkNKQ0PDSkNDg0pDQANBQAA==",

I can turn on the AC with this switch:
 - platform: broadlink
    host: 10.5.254.25
    mac: 'C8:F7:42:16:97:5D'
    timeout: 15
    switches:
      fujitsu_ac:
        friendly_name: "Fujitsu General AC ON_OFF"
        command_on: 'JgD2AGw2DQ4NDg4pDQ4NKQ0ODg4NDg0pDSkODg0ODQ4OKQ0pDQ4NDg4ODQ4NDw0ODQ4NDw0ODQ4NDw0ODQ4NKQ4ODQ4NDg4ODQ4NDg4ODSkNDg0PDQ4NDg4ODSkNKQ0pDSkOKQ0pDQ4NDg4ODSkNDg0PDQ4NDg0PDQ4NDg4ODSkNKQ0ODg4NKQ0ODQ8NDg0ODSkODg0ODSkNDw0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ8NDg0ODQ8NDg0ODQ8NDg0ODQ8NDg0pDSkNKQ4ODSkNDg0pDgANBQAA=='
        command_off: 'JgBmAGw2DQ4ODg0pDQ4NKQ4ODQ4NDg4pDSkNDg0ODg4NKQ0pDQ4ODg0ODQ8NDg0ODQ8NDg0ODQ8NDg0ODQ8NKQ0ODQ4ODg0ODQ4ODg0ODSkODg0ODQ4ODg0pDQ4NDw0ODQ4NDw0ODQANBQAA=='
		
But in this operation, the climate component of course remains in the off mode.

Is it possible to add a command ON in the component?

I will read all the commands from the remote and send you a complete file later to add to the AC code DB.

**Comment by smartHomeHub** [comment]
Does your unit have indicators to display the operation mode?

**Comment by acidquest** [comment]
No, indication only in the pult

**Comment by smartHomeHub** [comment]
Please do the following. Turn on your unit from the remote control, set the mode to heat and turn it off. Go to another room or hide the IR led of your remote and press the on button, change the mode to cool and press the off button. Unhide the IR led and turn on your AC. Is your unit in heat or cool mode?

**Comment by acidquest** [comment]
ok, I'll check this scenario in the evening when I'm at home

**Comment by acidquest** [comment]
I test. Result - cool mode.
Thank you very much. After checking your test, I understood how to read the codes. I set the necessary parameters on the remote control, turn it off, then start the broadlink_learn service in HA and turn on the remote control. Thus I get the command to turn on the AC in the right mode and temperature. After few day i send you file with ir code of my AC.

**Comment by smartHomeHub** [comment]
However, this is not the correct behavior of an AC unit. In the 99% of units, every time you change the mode or temperature from the remote control, an On command is also sent.
Please compare the code you receive when you went from cold to heat and from off to heat. Of course, at the same temperature, swing etc.
I really appreciate your help.

**Comment by smartHomeHub** [comment]
Also, consider using the broadlink manager windows app to get your codes.
[Broadlink Manager](https://sourceforge.net/projects/broadlink-manager/)

**Comment by acidquest** [comment]
I compare, code is different.
This code remote send if it in on state:
JgD2AGs2Dg4NDg0pDg4NKQ0ODQ8NDg0pDSkNDw0ODQ4NKQ4pDQ4NDg0PDQ4NDg4ODQ4NDg0PDQ4NDg4ODQ4NKQ0PDQ4NDg0PDQ4NDg0PDSkNDg0ODg4NDg0ODikNKQ0pDSkNKQ4pDQ4NDg0PDSkNDg0ODg4NDg0ODg4NDg0ODikNKQ0ODQ4ODgwPDQ8NDg0ODSkODg0ODSkNDw0ODQ4ODg0ODQ4ODg0ODA8ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ4ODg0ODQ8NDg0ODA8ODg0ODQ8NKQ0pDSkNKQ0PDSkNDg0pDQANBQAA==

This code if it in OFF state:
JgD2AG01DwwPDA8oDg0PJxAMDg0ODQ8nDygPDA8MDw0OKA8nDwwPDQ4NDwwPDQ4NDwwPDQ4NDwwPDQ4NDwwPKA8MDwwPDQ4NDwwPDQ4NDycQCw8NDg0PDA8NDigPJxAmECcPJw8nDwwPDQ4NDycPDA8NDg0PDA8NDg0PDA8NDigPJxALDw0OKA8MDw0ODQ8MDygPDA8MDycQDA4NDwwPDQ4NDwwPDQ4NDwwPDQ4NDw0ODQ4NDw0ODQ4NDw0ODQ8MDw0ODQ8MDw0ODQ8MDw0ODQ8MDw0ODQ8MDw0ODQ8MDw0ODQ8MDw0ODQ8nECYQJw8MDycQCw8oDwANBQAA==

both codes  - cool, auto, 18

**Comment by ramelito** [comment]
> Interesting. Isn't your remote control send the ON command every time you change the mode, temperature etc..? What's your AC model?

Daikin ATXC-B is not sending ON command every time mode or temperature sent; More, off command can turn on the device;
So seems app logic needs to be tuned;
