### ISSUE TITLE
compatibility of AC with codes

### ISSUE THREAD

**Issue by networkpadawan** [smartHomeHub/SmartIR#100]
I have a MSZ-AP35VG and and a MSZ-AP50VG AC´s, and the remote is SG17B model.
i can have poweroff|power on with one of the codes, but how to be sure that the temperatures are working? vane i can see and fan i can listen. but 1º degree temperature change im not understanding how i can confirm is ok.
how are you guys debugging?
Thanks in advance!

**Comment by brent0np** [comment]
Hi, what codes are you using the moment?  None of your machines appear to be currently listed as a current device ID: [https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#mitsubishi-electric](url)

If you have not created your own codes using your SG17B remove, you will need to start the process.  Happy to help you understand how to do it.  Are you using broadlink RM as an IR Sender?

**Comment by networkpadawan** [comment]
hi! i´m still migrating from the other ha plugin that exists, the one with .ini files. im using this mitsg15d.ini from a different remote, on off works,but other commands im not sure.
that would be great:) yes im using broadlink as ir sender.

**Comment by brent0np** [comment]
Ok - the codes won't be working as they are not for your machine - which is easily fixed if you are willing to spend the time.  

The Broadlink Manager will allow you to generate the file of codes for your remote.  [Download and install](https://sourceforge.net/projects/broadlink-manager/files/Windows%207/Version%201.0.0.1/) the software on windows 10 machine (use this thread for help). [https://community.home-assistant.io/t/broadlink-manager-nicer-way-to-learn-and-send-ir-rf-commands/58770](url).

As you generate the codes put them in the JSON file.  You can use the format from mine [here](https://github.com/smartHomeHub/SmartIR/blob/master/codes/climate/1282.json). 

The easiest method I found for testing was to put an example code you gather from the broadlink manager into your existing code file in hassio.  Then call the exact code and it should work.  Once that works just complete going through every code on the remote.

I would encourage you to submit the completed JSON file as a seperate issue so it can be incorperated into SmartIR.

**Comment by networkpadawan** [comment]
thanks for this! just one question, is there any version of the software for osx?

**Comment by brent0np** [comment]
No, unfortunately it needs to be run on Windows 10
