### ISSUE TITLE
New json-File for Midea RG36C1/BGE (Remote)

### ISSUE THREAD

**Issue by Lateadapter** [smartHomeHub/SmartIR#1013]
Hi Team,

please find new testet remote code for Midea AC RG36C1/BGE.
[139x - Midea RG36C1_BGE (Remote).zip](https://github.com/smartHomeHub/SmartIR/files/10787300/139x.-.Midea.RG36C1_BGE.Remote.zip)

Many thanks for your work on that nice integration!

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
