### ISSUE TITLE
Unable to find service remote.send_command on ESP32 remote with custom services

### ISSUE THREAD

**Issue by KC-inDomus** [smartHomeHub/SmartIR#1015]
When acting on a Climate entity made by SmartIR (probably the same happens with Fans and Media Players), calling services (for example, off command) causes no ir code sending and the following error on Home Assistant log:

```
2023-02-22 18:36:48.913 ERROR (MainThread) [custom_components.smartir.climate] Unable to find service remote.send_command
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 366, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 111, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1734, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service remote.send_command
```

**Home Assistant version**
2023.2.1

**SmartIR version**
1.17.6

**SmartIR configuration**
```
smartir:

climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1000
    controller_data: esp360remote_send_ir_raw
    temperature_sensor: sensor.living_room_temperature
```

**More details:**
Using [this configuration file](https://github.com/smartHomeHub/SmartIR/blob/master/codes/climate/1000.json) just for testing.
`sensor.living_room_temperature` is a working sensor entity
`esp360remote` is ESPHome node name from [device configuration](https://github.com/ale1800/ESP-360-REMOTE/blob/main/ESPHome%20Configuration/esphome-esp360remote.yaml) made by @ale1800 and used on my device, which is integrated on Home Assistant
`esp360remote_send_ir_raw` used on smartir config is expected to be the correct service name (without `service.` suffix, as [ESPHome docs says](https://esphome.io/components/api.html#user-defined-services)) as [your docs says](https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#example-using-esphome).

**Comment by KC-inDomus** [comment]
Solved. The problem comes from the format of codes: esphome needs integer arrays, while all the other usual json are expressed in base64.

**Comment by tenabiker** [comment]
> Solved. The problem comes from the format of codes: esphome needs integer arrays, while all the other usual json are expressed in base64.

Sorry, but what was the solution itself ?

**Comment by KiLLeRRaT** [comment]
I'm also having trouble with esphome and smartIR.  Are you saying that we need to change the json files to be int IR arrays and not be base64 strings?
