### ISSUE TITLE
JSON for MSC-A07YV

### ISSUE THREAD

**Issue by gonsanbo** [smartHomeHub/SmartIR#1018]
New json file for Mitsubishi Electric MSC-A07YV

[9999.json.txt](https://github.com/smartHomeHub/SmartIR/files/10839339/9999.json.txt)

**Comment by gonsanbo** [comment]
Renamed to .txt because github wouldn't let me upload .json.

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
