### ISSUE TITLE
Block issue after update HA core 2023.3.1

### ISSUE THREAD

**Issue by TsailunVR** [smartHomeHub/SmartIR#1025]
System details
Home-assistant (version): Home Assistant 2023.3.1

After install this version when i want to check my configuration before restart i have this issues and i cant do it, The integration doesnt work neither

![image](https://user-images.githubusercontent.com/99659819/223198982-5229fbf8-edc5-4724-9c7c-9c3660104b52.png)

and configuration.yalm

smartir:
climate:
  - platform: smartir
    name: AC Salón
    unique_id: salon_ac
    device_code: 1401
    controller_data: remote.mando_salon_remote
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
  - platform: generic_thermostat
    name: Salon
    heater: input_boolean.input_boolean_aire_comedor
    target_sensor: sensor.termometro_1_xiaomi_temp
    min_temp: 10
    max_temp: 35
    ac_mode: false
    target_temp: 22
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode:  "off"
    away_temp: 25
    precision: 0.5
  - platform: smartir
    name: AC Buhardilla
    unique_id: buhardilla_ac
    device_code: 1481
    controller_data: remote.mando_buhardilla_remote
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
  - platform: generic_thermostat
    name: Buhardilla
    heater: input_boolean.aire_buhardilla
    target_sensor: sensor.termometro_6_xiaomi_temp_2
    min_temp: 10
    max_temp: 35
    ac_mode: false
    target_temp: 22
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode:  "off"
    away_temp: 25
    precision: 0.5
  - platform: dual_smart_thermostat
    name: Planta baja
    heater: input_boolean.input_boolean_aire_plantabaja
    cooler: input_boolean.input_boolean_aire_plantabaja
    target_sensor: sensor.termometro_4_xiaomi_temp_2
    floor_sensor: sensor.floor_temp
    min_temp: 10
    max_temp: 35
    ac_mode: false
    target_temp: 22
    cold_tolerance: 0.2
    hot_tolerance: 0.2
    min_cycle_duration:
      seconds: 5
    keep_alive:
      minutes: 3
    initial_hvac_mode: "off" # hvac mode will reset to this value after restart
    away: # this preset will be available for all hvac modes
      temperature: 22
      target_temp_low: 22
      target_temp_high: 22
    home: # this preset will be available only for heat or cool hvac mode
      temperature: 22
    precision: 0.1
    target_temp_step: 0.5

**Comment by rottiakash** [comment]
Facing the same issue, was someone able to find any resolution for this issue?

**Comment by TsailunVR** [comment]
I’ll try, thanks!
