### ISSUE TITLE
New Code LG Remote akb36637504

### ISSUE THREAD

**Issue by brotwi** [smartHomeHub/SmartIR#1032]
Hi, I'm attaching a code to add to the AC LG list for the akb36637504 remote control, I don't know how to assign the device_code so I'll leave it that way
[akb36637504.zip](https://github.com/smartHomeHub/SmartIR/files/11212101/akb36637504.zip)
for broadlink
Thank you very much for your work

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
