### ISSUE TITLE
New JSON (Daikin ARC484A10(remote), ATL50TV16V2)

### ISSUE THREAD

**Issue by Zarrickisdea** [smartHomeHub/SmartIR#1034]
New remote codes for Daikin ARC484A10(remote), ATL50TV16V2 split A/C
Notes:
The dry mode has no actual temperature control or fan speed control and is automated by the A/C unit itself
The fan mode does not have an auto speed setting and must be set to low, medium or high
Edit:
made a mistake in naming the modes, new file here that corrects it

[1119.json.zip](https://github.com/smartHomeHub/SmartIR/files/11230400/1119.json.zip)

**Comment by Zarrickisdea** [comment]
just from a quick google search of the remote model number, it looks like your AC has different modes than what is available on my remote.

If you want you can try one of the universal codes available for daikin models here: https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md

If you're using a broadlink remote, I recommend reading the Broadlink integration documentation by Home Assistant: https://www.home-assistant.io/integrations/broadlink/

This is also a good read if you need to understand how most Daikin remotes work: https://github.com/blafois/Daikin-IR-Reverse

**Comment by anjaan5** [comment]
Just to clarify, are you talking about the universal codes from 1100 to 1118? if you are then, I have already tried all. and none worked for me.

**Comment by anjaan5** [comment]
Yup. I used remote.learn_command service to input codes into HA. So I set three temp and fan combination settings on my ac remote and got HA to learn it via the learn command and then setup my wireless buttons to use those to control ac. All well and good so far. But the smart ir has this very neat looking Lovelace card and I can use hvac mode from smart ir to automate different ac settings at different time. This is why I now need the JSON file. I am gonna try what you suggested. But if I go as per format given in smartIR, I have to remote.learn command for every combination of temp and fan right?? My god, that will be a PITA.

**Comment by Zarrickisdea** [comment]
It was a PITA 👍

**Comment by anjaan5** [comment]
got it! thank you!

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
