### ISSUE TITLE
New JSON New remote codes for Brand: Micromax, ACS18C3T3QS6HW Split A/C

### ISSUE THREAD

**Issue by theshop35** [smartHomeHub/SmartIR#1037]
Add support New remote codes for Brand: Micromax, Model no: ACS18C3T3QS6HW Split A/C
for BroadLink 
i have attached the json file.
[5001 json file.zip](https://github.com/smartHomeHub/SmartIR/files/11261341/5001.json.file.zip)

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
