### ISSUE TITLE
SmartIR latest version incompatible with Home Assistant?

### ISSUE THREAD

**Issue by aristosv** [smartHomeHub/SmartIR#104]
I am on home assistant version 0.91.4 (which today is the latest) and I keep getting this notification.

![2019-04-25 09_16_17-Home Assistant](https://user-images.githubusercontent.com/528302/56713649-f18fad80-673a-11e9-86d0-7184d661dd9b.png)

**Comment by smartHomeHub** [comment]
![image](https://user-images.githubusercontent.com/47714957/56713697-21d74c00-673b-11e9-97ca-5ac201c4e59d.png)

**Comment by aristosv** [comment]
sorry about that, I didn't get a notification in Hass.io that there's a new version.

**Comment by smartHomeHub** [comment]
Please keep in mind that there is a breaking change in the configuration.

**Comment by aristosv** [comment]
I went through the breaking changes in the latest version but I don't see anything related to smartir. Sure enough, after upgrading, smartir component cant be loaded any more. Is there a way to fix it?

**Comment by smartHomeHub** [comment]
There is a breaking change in Broadlink send/learn service:
https://github.com/home-assistant/home-assistant/pull/21465

You need to change ``controller_send_service: switch.broadlink_send_packet_192_168_10_10`` to ``controller_data: 192.168.10.10`` in SmartIR climate/media/fan configuration.

**Comment by aristosv** [comment]
yes, this fixed it. Thanks.
