### ISSUE TITLE
how to fix media_player ?

### ISSUE THREAD

**Issue by GODAUMOI123** [smartHomeHub/SmartIR#1046]
media_player:
  -platform: smartir
   name: bedroom TV
   unique_id: living_room_tv
   device_id: 1060
   controller_data: remote.rm_pro_remote
   source_names:
     Channel 0: CD
     Channel 1: TAPE 1
     HDMI 1: TV
     HDMI 2: Computer

  -platform: smartir
   name: home TV
   unique_id: bed_room_tv
   device_code: 7000
   controller_data: remote.eremote_mini
   source_names:
     Channel 0: CD
     Channel 1: TAPE 1
     HDMI 1: TV
     HDMI 2: Computer

**Comment by vassilis-panos** [comment]
What do you want to fix?
