### ISSUE TITLE
New JSON for Panasonic air conditioner: CS-XU9UKH and CS-XU12UKH

### ISSUE THREAD

**Issue by huythach83** [smartHomeHub/SmartIR#1047]
Support basic control. Left out Quiet mode

[1032.zip](https://github.com/smartHomeHub/SmartIR/files/11369536/1032.zip)

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
