### ISSUE TITLE
Device working, but not included in supported devices: Hitachi RAS050YHA3

### ISSUE THREAD

**Issue by roldengarm** [smartHomeHub/SmartIR#1052]
Indoor unit: RAS-50YHA3 
I've extracted some of the IR commands manually, but that's a very tedious process.

I've tried the existing device 1087, but that doesn't work, and the codes are different.

Is there any way I can extract the data from my Broadlink Android app?

**Comment by vassilis-panos** [comment]
Unfortunately, no
