### ISSUE TITLE
PARKAIR DI-A series json

### ISSUE THREAD

**Issue by g1za** [smartHomeHub/SmartIR#1058]
PARKAIR DI-A series json

[parkair.json.zip](https://github.com/smartHomeHub/SmartIR/files/11630285/parkair.json.zip)

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
