### ISSUE TITLE
I did the HACS installation, but then what...?

### ISSUE THREAD

**Issue by Cr4z33** [smartHomeHub/SmartIR#1064]
I don't know if this project has been abandoned or not, but after adding the repository to HACS as "integration", I then searched for it, installed it and rebooted HA.

Now I am lost because I don't know what's the next step...? 🤔

**Comment by LordSushiPhoenix** [comment]
https://github.com/smartHomeHub/SmartIR#platform-setup-instructions

**Comment by devbyaccident** [comment]
Once you add it to configuration.yaml and restart, you'll see a new entity in HA. If not, you might have some kind of configuration issue. This is how mine looks and I've been using it just fine for my thermostats

![image](https://github.com/smartHomeHub/SmartIR/assets/12488263/95e70e54-002d-488b-afef-9ac47c0328b0)

**Comment by Cr4z33** [comment]
Thanks @devbyaccident found it finally! 😁
