### ISSUE TITLE
Can't configure Moes UFO-R11

### ISSUE THREAD

**Issue by ortiztundidor** [smartHomeHub/SmartIR#1074]
**Home Assistant version**

Home Assistant 2023.6.3

**SmartIR version**

1.17.7

**SmartIR configuration**

```yaml

Add configuration here

smartir:

climate:
  - platform: smartir
    name: aire dormitorio Elsa
    unique_id: aireDormitorioElsa
    device_code: 8888
    controller_data: zigbee2mqtt/IRElsa/set
    #temperature_sensor: sensor.broadlink_dormitorio_temperatura
    #humidity_sensor: sensor.broadlink_dormitorio_humedad
    #power_sensor: binary_sensor.ac_power    

JSON:

{
  "manufacturer": "General",
  "supportedModels": [
    "ASYG07KPCA"
  ],
  "supportedController": "MQTT",
  "commandsEncoding": "Raw",
  "minTemperature": 18.0,
  "maxTemperature": 30.0,
  "precision": 1.0,
  "operationModes": [
    "heat",
    "cool",
    "dry",
    "fan_only",
    "heat_cool"
  ],
  "fanModes": [
    "auto",
    "high",
    "med",
    "low",
    "quiet"
  ],
  "commands": {
    "off": "B/QMUQa7AZUBQAMFlQHJBJUBQAlAB4ABQA0BlQFADwHJBIALwAEByQSAA8AB4AUdQAHgERFAO+ALHQK7AZVgAUAfQAHAD0ABAckEQA1AA0AB4AMHAbsBwBsCyQSVIANAB+ACAwIElQE=",
....

}

**Describe the bug**

A clear and concise description of what the bug is.

**Debug log**

I have an IR transmitter MOES UFO-R11. I have configured it as indicated in the previous files. So far, I have only configured the stop function and left the others as they were. It's not working, and I don't know how to make this work. Could you help me?

Add your logs here.

```

**Additional context**

I have other Broadlink transmitters that I have configured without any problems on several devices.

**Comment by ortiztundidor** [comment]
i have this script and run perfect:

alias: irmqtt.stop
sequence:
  - service: mqtt.publish
    data:
      topic: zigbee2mqtt/IRElsa/set
      payload: >-
        {"ir_code_to_send":"B/QMUQa7AZUBQAMFlQHJBJUBQAlAB4ABQA0BlQFADwHJBIALwAEByQSAA8AB4AUdQAHgERFAO+ALHQK7AZVgAUAfQAHAD0ABAckEQA1AA0AB4AMHAbsBwBsCyQSVIANAB+ACAwIElQE="}
mode: single
icon: mdi:air-conditioner

**Comment by ortiztundidor** [comment]
I have done some tests with other JSON files, and they don't work either. These are the JSON files I have tried:

  "commands": {
    "off": {
		>-
        {"ir_code_to_send":"B/QMUQa7AZUBQAMFlQHJBJUBQAlAB4ABQA0BlQFADwHJBIALwAEByQSAA8AB4AUdQAHgERFAO+ALHQK7AZVgAUAfQAHAD0ABAckEQA1AA0AB4AMHAbsBwBsCyQSVIANAB+ACAwIElQE="}
		},
		
2023-06-28 20:33:47.280 ERROR (MainThread) [custom_components.smartir.climate] The device Json file is invalid

  "commands": {
    "off": {
        "ir_code_to_send":"B/QMUQa7AZUBQAMFlQHJBJUBQAlAB4ABQA0BlQFADwHJBIALwAEByQSAA8AB4AUdQAHgERFAO+ALHQK7AZVgAUAfQAHAD0ABAckEQA1AA0AB4AMHAbsBwBsCyQSVIANAB+ACAwIElQE="
		},

2023-06-28 22:17:05.024 ERROR (MainThread) [custom_components.smartir.climate] value should be a string for dictionary value @ data['payload']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 371, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 151, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1864, in async_call
    processed_data: dict[str, Any] = handler.schema(service_data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: value should be a string for dictionary value @ data['payload']
2023-06-28 22:17:05.031 WARNING (MainThread) [homeassistant.helpers.entity] Entity climate.aire_dormitorio_elsa_2 (<class 'custom_components.smartir.climate.SmartIRClimate'>) is using self.async_update_ha_state(), without enabling force_update. Instead it should use self.async_write_ha_state(), please report it to the custom integration author.

**Comment by madjetey** [comment]
I'm using the same device. This is what your json should look like [https://pastebin.com/Tw9XGJtY](https://pastebin.com/Tw9XGJtY)

**Comment by ortiztundidor** [comment]
Hello
I have created the following JSON:

https://pastebin.com/QAUrges4

I'm getting the following error in the log:

voluptuous.error.MultipleInvalid: value should be a string for dictionary value @ data['payload']
2023-07-10 07:59:18.785 ERROR (MainThread) [custom_components.smartir.climate] value should be a string for dictionary value @ data['payload']
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 371, in send_command
    await self._controller.send(self._commands['off'])
  File "/config/custom_components/smartir/controller.py", line 151, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1864, in async_call
    processed_data: dict[str, Any] = handler.schema(service_data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 232, in __call__
    return self._exec((Schema(val) for val in self.validators), v)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.11/site-packages/voluptuous/validators.py", line 351, in _exec
    v = func(v)
        ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 818, in validate_callable
    return schema(data)
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)

**Comment by ortiztundidor** [comment]
someone can help me?

**Comment by luisetex84** [comment]
In MQTT controller with Moes UFO-R11 it's necessary the json command you use in your script :

> i have this script and run perfect:
> 
> alias: irmqtt.stop sequence:
> 
>     * service: mqtt.publish
>       data:
>       topic: zigbee2mqtt/IRElsa/set
>       payload: >-
>       {"ir_code_to_send":"B/QMUQa7AZUBQAMFlQHJBJUBQAlAB4ABQA0BlQFADwHJBIALwAEByQSAA8AB4AUdQAHgERFAO+ALHQK7AZVgAUAfQAHAD0ABAckEQA1AA0AB4AMHAbsBwBsCyQSVIANAB+ACAwIElQE="}
>       mode: single
>       icon: mdi:air-conditioner

So, this would be the json file for smartir:

    "commands": {
      "on": "{\"ir_code_to_send\" : \"B/QMUQa7AZUBQAMFlQHJBJUBQAlAB4ABQA0BlQFADwHJBIALwAEByQSAA8AB4AUdQAHgERFAO+ALHQK7AZVgAUAfQAHAD0ABAckEQA1AA0AB4AMHAbsBwBsCyQSVIANAB+ACAwIElQE=\"}"

Look out to escape any double quote inside json command

**Comment by ortiztundidor** [comment]
thank you very much

**Comment by ortiztundidor** [comment]
i used the same than posted [luisetex84](https://github.com/luisetex84)

this is a example

  "commands": {
    "off": "{\"ir_code_to_send\":\"BegMTQabAcABBNUEywGbIAED1QSbAeADAUAPQAPgAwFAD0AD4CsB4Bc34Asf4AsTwAHAG0AH4AgDAgSbAQ==\"}",
    "heat": {
      "auto": {
        "16": "{\"ir_code_to_send\":\"BpoMUwa9AZRgAQa9Ac0EvQGUIAGAB0ALQAMBlAFADwfNBJQBlAG9AcADAc0EgAMAlGABQAfAA0ABwAtAB0ABQAfAAweUAc0ElAGUAUAP4AMB4AEPAc0E4AELwAEDzQSUAcAB4AcdwBsCzQS9IAPgAwcFlAHNBJQB\"}",
        "17": "{\"ir_code_to_send\":\"Bx4NSAauAYcBgAMDxwSuAUALwAdAC0ADQA9AA0ALwANAD0ADwA/gIwfAN0ABQDcCrgGHIAEArmABQAdAH+ABAQCHYAHAEwCHIAEAruACAQCHIAHAG0AHCccErgHHBK4BxwQ=\"}",
        "18": "{\"ir_code_to_send\":\"CRwNaQaXAZcBuQFAAwXYBJcBlwFABwK5AZdgAUAHBLkB2ASXIAMDuQGXAcADAZcBQA8H2ASXAZcBuQHgAQNAAYAPArkBl+ACAUANQANAAQa5AdgEuQGX4AIB4AUNAZcB4AUfgB0B2ATgFQPAAUAn4AMBgD3gAQFAD0AjAdgEQAmAAeADC8ABA9gElwHAIcAH4AMTwAHAG8AB4BMPQBtAA4ABgAmABQGXAcAHAZcB4AEJQAHgCQ3gARGACYAF4AEBgA9Aq0ABQA1AC0ADQAFAB0ATC5cBlwGXAZcB2ASXAQ==\"}",
        "19": "{\"ir_code_to_send\":\"BgENVga+AZZgAQa+Ac4EvgGWIAGAB4ALA5YBvgFADwfOBJYBlgG+AcADAc4EgAMAlmABQAfAA0ABQAtAAcAHQAHgAQsDzgSWAeABDYAB4AMPQB/gBQEBvgHgARMCvgGW4AQBAb4BwBtAB+AIAwIElgE=\"}",
        "20": "{\"ir_code_to_send\":\"BvcMWAa/AZVgAQa/AckEvwGVIAGAB0ALQAMBlQFADwfJBJUBlQG/AcADAckEgAMAlWABQAfAA0ABwAtAB0ABQAfAAwGVAUA7AZUBQANAAUAHwANAAQG/AYAfwAEBvwFAAwLJBJUgA+AHB0ATQAMEvwG/AZVgAUALAZUBQAPgAwHgBQ8ByQSAAwGVAYAXAckEQAdAA+ADAQq/AckElQGVAb8BlSABQAWAD0ABQA3gAQHgEw1AAeAFHwGVAeAHDwGVAeAFEeAFDUAB4AcR4AcPAZUB4AcR4AGrAZUBQAtAA0AjQAdAAQvJBJUByQSVAZUBvwE=\"}",
        "21": "{\"ir_code_to_send\":\"BvwMWQa9AZdgAQW9AcoEvQHgAwdACwCXIAFAFwPKBJcBgAEBvQFAA0APBMoEvQGXYAFAB8AD4AMBQBPAAUALQAMBlwGAN4ALgAFAC0ADgAGAH8ABQBcEvQHKBJcgA8AHwAvgAQ8ElwG9AZcgAUATApcBvSABAJegAYAJgAWAAQHKBIADgAEBvQFAD4ABAr0BlyABgA8BvQGAB4ABA70BlwGADwC9IAEAl+ACAQC9IAEAl+AEAeAXDwGXAeAXIeARH4AZgAXgAwHgBxGAq4ABQAtAA0AjQAdAAwuXAZcBygSXAb0BlwE=\"}",
        "22": "{\"ir_code_to_send\":\"BRcNcQadAcABA+EEnQFAAcAHwAFAD0ADBp0B0wFhAZ1gAQLhBNMgAwGdAYABAdMBwBfAAeAHD+ADAeABN+ANAeALH0AT4BMDwAFAI+AXAUAjQAPAAeADC8ABQBNAA+ADAeAHD+CTAeADq0ALAeEEgZHABwudAZ0B4QRhAZ0BnQE=\"}",
        "23": "{\"ir_code_to_send\":\"BsEMTAa4AZdgAQa4Ad0EuAGXIAGAB4ALA5cBuAFAD0ADQAuAAwGXAUAPB90ElwGXAbgB4AED4AMBQBfAAUALQANAAQa4Ad0EuAGX4AQB4AUPA90ElwFAAYAVgAVAE+ATA8ABAd0EgC/gAQHgBQ9ADQHdBEADQAmAAeADC0ABAd0E4AED4AMBQBfAAeABPYAB4AcPAZcB4AcR4BUP4AUdQA1AA4ABwAnAB8AB4BMPQKvAH0ALQANAD0AHwAMHlwGXAbgBlwE==\"}",

**Comment by dusnake** [comment]
> i used the same than posted [luisetex84](https://github.com/luisetex84)
> 
> this is a example
> 
> ```
>   "commands": {
>     "off": "{\"ir_code_to_send\":\"BegMTQabAcABBNUEywGbIAED1QSbAeADAUAPQAPgAwFAD0AD4CsB4Bc34Asf4AsTwAHAG0AH4AgDAgSbAQ==\"}",
>     "heat": {
>       "auto": {
>         "16": "{\"ir_code_to_send\":\"BpoMUwa9AZRgAQa9Ac0EvQGUIAGAB0ALQAMBlAFADwfNBJQBlAG9AcADAc0EgAMAlGABQAfAA0ABwAtAB0ABQAfAAweUAc0ElAGUAUAP4AMB4AEPAc0E4AELwAEDzQSUAcAB4AcdwBsCzQS9IAPgAwcFlAHNBJQB\"}",
>         "17": "{\"ir_code_to_send\":\"Bx4NSAauAYcBgAMDxwSuAUALwAdAC0ADQA9AA0ALwANAD0ADwA/gIwfAN0ABQDcCrgGHIAEArmABQAdAH+ABAQCHYAHAEwCHIAEAruACAQCHIAHAG0AHCccErgHHBK4BxwQ=\"}",
>         "18": "{\"ir_code_to_send\":\"CRwNaQaXAZcBuQFAAwXYBJcBlwFABwK5AZdgAUAHBLkB2ASXIAMDuQGXAcADAZcBQA8H2ASXAZcBuQHgAQNAAYAPArkBl+ACAUANQANAAQa5AdgEuQGX4AIB4AUNAZcB4AUfgB0B2ATgFQPAAUAn4AMBgD3gAQFAD0AjAdgEQAmAAeADC8ABA9gElwHAIcAH4AMTwAHAG8AB4BMPQBtAA4ABgAmABQGXAcAHAZcB4AEJQAHgCQ3gARGACYAF4AEBgA9Aq0ABQA1AC0ADQAFAB0ATC5cBlwGXAZcB2ASXAQ==\"}",
>         "19": "{\"ir_code_to_send\":\"BgENVga+AZZgAQa+Ac4EvgGWIAGAB4ALA5YBvgFADwfOBJYBlgG+AcADAc4EgAMAlmABQAfAA0ABQAtAAcAHQAHgAQsDzgSWAeABDYAB4AMPQB/gBQEBvgHgARMCvgGW4AQBAb4BwBtAB+AIAwIElgE=\"}",
>         "20": "{\"ir_code_to_send\":\"BvcMWAa/AZVgAQa/AckEvwGVIAGAB0ALQAMBlQFADwfJBJUBlQG/AcADAckEgAMAlWABQAfAA0ABwAtAB0ABQAfAAwGVAUA7AZUBQANAAUAHwANAAQG/AYAfwAEBvwFAAwLJBJUgA+AHB0ATQAMEvwG/AZVgAUALAZUBQAPgAwHgBQ8ByQSAAwGVAYAXAckEQAdAA+ADAQq/AckElQGVAb8BlSABQAWAD0ABQA3gAQHgEw1AAeAFHwGVAeAHDwGVAeAFEeAFDUAB4AcR4AcPAZUB4AcR4AGrAZUBQAtAA0AjQAdAAQvJBJUByQSVAZUBvwE=\"}",
>         "21": "{\"ir_code_to_send\":\"BvwMWQa9AZdgAQW9AcoEvQHgAwdACwCXIAFAFwPKBJcBgAEBvQFAA0APBMoEvQGXYAFAB8AD4AMBQBPAAUALQAMBlwGAN4ALgAFAC0ADgAGAH8ABQBcEvQHKBJcgA8AHwAvgAQ8ElwG9AZcgAUATApcBvSABAJegAYAJgAWAAQHKBIADgAEBvQFAD4ABAr0BlyABgA8BvQGAB4ABA70BlwGADwC9IAEAl+ACAQC9IAEAl+AEAeAXDwGXAeAXIeARH4AZgAXgAwHgBxGAq4ABQAtAA0AjQAdAAwuXAZcBygSXAb0BlwE=\"}",
>         "22": "{\"ir_code_to_send\":\"BRcNcQadAcABA+EEnQFAAcAHwAFAD0ADBp0B0wFhAZ1gAQLhBNMgAwGdAYABAdMBwBfAAeAHD+ADAeABN+ANAeALH0AT4BMDwAFAI+AXAUAjQAPAAeADC8ABQBNAA+ADAeAHD+CTAeADq0ALAeEEgZHABwudAZ0B4QRhAZ0BnQE=\"}",
>         "23": "{\"ir_code_to_send\":\"BsEMTAa4AZdgAQa4Ad0EuAGXIAGAB4ALA5cBuAFAD0ADQAuAAwGXAUAPB90ElwGXAbgB4AED4AMBQBfAAUALQANAAQa4Ad0EuAGX4AQB4AUPA90ElwFAAYAVgAVAE+ATA8ABAd0EgC/gAQHgBQ9ADQHdBEADQAmAAeADC0ABAd0E4AED4AMBQBfAAeABPYAB4AcPAZcB4AcR4BUP4AUdQA1AA4ABwAnAB8AB4BMPQKvAH0ALQANAD0AHwAMHlwGXAbgBlwE==\"}",
> ```

Hola, conseguiste hacerlo funcionar?

**Comment by Kazarnikov** [comment]
For MQTT, you must replace these lines in the json file.

  "supportedController": "MQTT",
  "commandsEncoding": "Raw",

configuration.yaml
```yaml
  smartir:
  
  climate:
    - platform: smartir
      name: Кондиционер JAX
      unique_id: conditioner_jax_unique_id
      device_code: 99999
      controller_data: 'zigbee2mqtt/0x8c65a3fffed603f4/set/ir_code_to_send'
      temperature_sensor: sensor.qingping_air_monitor_temperature
      humidity_sensor: sensor.qingping_air_monitor_humidity
```

99999.json
```json
{
  "manufacturer": "Midea",
  "supportedModels": [
    "MSY-12HRDN1"
  ],
  "supportedController": "MQTT",
  "commandsEncoding": "Raw",
  "minTemperature": 17.0,
  "maxTemperature": 30.0,
  "precision": 1.0,
  "operationModes": [
    "heat",
    "cool",
    "heat_cool",
    "fan_only",
    "dry"
  ],
  "fanModes": [
    "low",
    "mid",
    "high",
    "auto"
  ],
  "commands": {
    "off": "Cd8R3xEgAkUGIAJAAUAHQAPAAeATC8Ab4AMHQAvAA0ABwAtAB+AHAeADEwJFBl0gA0AHASAC4BcBQCPgBwMB3xFAAQEgAkAXQAFAB0ADwAHgEwvAG+ADB0ALwANAAcALQAfgBwHgAxNAC8AD4BcBwCcLRQYgAkUGIAJFBiAC",
    "heat": {
      "low": {
        "17": "CcwRzBEiAjkGIgJAAUAHQAPAAeATC8AbQAcEOQZXAiIgAQE5BuANA0ABATkGgCPgAQHgFw/gAQFAOwE5BkAH4A0DAcwRQAEGIgI5BlcCIiABATkGgAPAAUAPwAHgBwvAD0AHQANAAUAH4AsDQAFAF+AvAUA74BADAgYiAg==",
        "18": "CSIRIhEjAjYGIwJAAUAHBDYGWQIjoAHgEQtAGwEjAkABQAdAAwMjAlkCQAfgCwNAAUAX4BsB4AsnQBPAA0ABATYG4AVrC1YUIhEiESMCNgYjAkABQAdAA8AB4BMLwBtABwQ2BlkCIyABATYG4A0DQAFAG+AbAeALJ0ATwANAAcALBzYGIwI2BiMC",
        "19": CdcR1xEmAjIGJgJAAUAHQAPAAeATC8AbQAdAA0ABQAfgCwMDJgJcAkAX4BcBQCNAA+AHAUATQAPAAUAL4AMDAdcRQAHgAWPAG8ABQA/AAeAHC8APQAdAA0ABQAfgCwNAAUAX4BcBQCNAA+AHAUATQAPAAUALCzIGJgIyBiYCMgYmAg==",
