### ISSUE TITLE
0.92 problem

### ISSUE THREAD

**Issue by Shanghaiman** [smartHomeHub/SmartIR#108]
**Home Assistant version**
hassio 0.92
**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**
Invalid config for [climate.smartir]: required key not provided @ data['controller_data']. Got None. (See /config/components/packages/../climates/Pastry_Aircones_midea_.yaml, line 0). Please check the docs at https://home-assistant.io/components/climate.smartir/

**Debug log**

```text

Add your logs here.

```

**Additional context**

HI,

every thing used to work fine untill i have updated to the 0.92 hassio.
i have downloaded the newest PY files, placed them all inside the custom_components/smatrir folder but still getting this new problem.
any idea why?

**Comment by smartHomeHub** [comment]
https://community.home-assistant.io/t/smartir-control-your-climate-tv-and-fan-devices-via-ir-rf-controllers/100798/263

**Comment by Shanghaiman** [comment]
thank you.
Does that mean no more need to make a switch for each broadlink device?
can i delete the "controller_send_service: switch.broadlink_send_packet_192.*.*.*" from the climates files?

**Comment by Shanghaiman** [comment]
still doesnt work.
![5](https://user-images.githubusercontent.com/47654029/56875222-eb1e7000-6a71-11e9-94f6-d176ec5ce723.png)
![1](https://user-images.githubusercontent.com/47654029/56875224-ebb70680-6a71-11e9-8b2e-c34429f8e096.png)
![2](https://user-images.githubusercontent.com/47654029/56875225-ebb70680-6a71-11e9-9cf8-1832ac5701b2.png)
![4](https://user-images.githubusercontent.com/47654029/56875226-ec4f9d00-6a71-11e9-81ae-8763bd62f0f1.png)
![3](https://user-images.githubusercontent.com/47654029/56875227-ece83380-6a71-11e9-94ed-8404f7aaadab.png)

am i'm doing anything wrong?

**Comment by smartHomeHub** [comment]
Hi,
Sorry for the delay. Did you resolve this issue?

**Comment by Shanghaiman** [comment]
Yes I did,  thank you.
I think I wrote you in the thread.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
