### ISSUE TITLE
SmartIR/codes/climate /1185.json bad JSON format

### ISSUE THREAD

**Issue by pgarciafc** [smartHomeHub/SmartIR#1123]
Hi,

I'm trying to use 1185.json (Gree + Broadlink) but Home Assistant complains about JSON format being inappropriate.

I've ran a JSON lint test and indeed it is not properly defined.

I will be sending a PR including formatting fixes + compatibility with another Gree AC model.

**Comment by vassilis-panos** [comment]
Thanks for pointing it out. I usually test json files before merging. Looks like I missed that
