### ISSUE TITLE
Broadlink controller_data - IP address or entity ID?

### ISSUE THREAD

**Issue by richardgaywood** [smartHomeHub/SmartIR#1126]
https://github.com/smartHomeHub/SmartIR/blob/master/docs/FAN.md says:

> controller_data (Required): The data required for the controller to function. **Enter the IP address of the Broadlink device** (must be an already configured device), or the entity id of the Xiaomi IR controller, or the MQTT topic on which to send commands.

However, the example for Broadlink just a few lines further down seems to use an entity ID instead of an IP address:

> ` controller_data: remote.bedroom_remote`

**Comment by vassilis-panos** [comment]
Thanks for pointing it out. The correct one is an entity ID
