### ISSUE TITLE
 TCL FMA-09/12CHS   device_code

### ISSUE THREAD

**Issue by aleg80** [smartHomeHub/SmartIR#1128]
Hi! 
I cannot find my Clima TCL FMA-09/12CHSD Elite Series in device_code:
1900 and 1901 does not work.
Thanks

**Home Assistant version**
Home Assistant 2023.7.3
**SmartIR version**
RM4C mini da Broadlink
Firmware: 62092

**SmartIR configuration in yaml**

  - platform: smartir
    name: ClimaLetto
    device_code: 1900
    controller_data: remote.irca
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.stato_accensione

**A clear and concise description of what the bug is.**

code does not work

Thank you

**Comment by vassilis-panos** [comment]
I'm afraid if you can't find the codes for your device you have to create your own.
Remember that this is a place for issues, not feature requests.
Thanks
