### ISSUE TITLE
Climate SmartIT Broadlink example is out of date

### ISSUE THREAD

**Issue by domier** [smartHomeHub/SmartIR#117]
The example text on the SmartIR documentation is out of date:

[SmartIR/docs/CLIMATE.md](https://github.com/smartHomeHub/SmartIR/blob/4a946271071e72c533c477ce59abbcd2a4ed8557/docs/CLIMATE.md)

The line that currently reads
`    controller_send_service: switch.broadlink_send_packet_192_168_10_10`

should be updated to:
`    controller_data: 192.168.10.10`

**Comment by smartHomeHub** [comment]
The link isn't point to current master branch

**Comment by domier** [comment]
Thanks, not sure why I was finding that link, confirmed that the master is up to date, closing
