### ISSUE TITLE
Since last HA update I am getting this error: TypeError: SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given

### ISSUE THREAD

**Issue by hvddrift** [smartHomeHub/SmartIR#1170]
**Home Assistant version**
2023.12.1
**SmartIR version**
1.17.8
**SmartIR configuration**

``{
  "manufacturer": "Kaze",
  "supportedModels": [
    "Unknown"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "speed": [
    "lowest",
    "low",
    "mediumLow",
    "medium",
    "mediumHigh",
    "high"
  ],
  "commands": {
    "off": "sgA0ARsLGgsbCxoLGwsbGA4YDRgOCxsLGwobGA4AATgOGA4LGgsbGA4LGxgNCxsLGwsaCxsLGwobGA4YDgsaGA4LGwsbChsLGwsaCxsLGwsaCxsLGxgOFw4YDgsbCxoLGxgOAAE3DRgOCxsLGxgNCxsYDgsaCxsLGwsaCxsLGxcOGA4LGxgNCxsLGwsbChsLGwsbChsLGwsbCxoYDhgNGA4LGwsaCxsYDgABNw4YDgsaCxsYDgobGA4LGwsaCxsLGwsbChsYDhgNDBoYDgsbCxoLGwsaCxsLGwsbCxoLGwsbGA0YDhgOCxoLGwsbGA4AATkNGQ0LGwsbFw4LGxgNDBoLGwsbChsLGwsbGA0YDgsbGA0LGwsbCxsLGgsbCxsKGwsbCxsKGxgOGA4XDgsbCxsLGhgOAAXcAAAAAA==",
    "reverse": {
      "lowest": "sgD0AhwKGwocChwKGwocFw4YDgsbFw8KGwsbChwXDgsbChwKGwsbChsLGxgOFw8XDgsbCxsKHAobAAE4DxcOCxsKHBcOCxsXDwocChsKHAobCxsLGxcOGA4LGxcOCxsLGwobGA4LGwobCxsLGwocChsYDhcPFw4LGwsbChwKGwABNw4YDgocChsXDwocFw4LGwocChsLGwocChsYDhcPChwXDgocChwKGxgOChwKGwsbChwKGwocFw8XDhgOChwKGwsbChsAATgOFw8KHAobFw8KGxgOCxsKGwsbCxsKHAobGA4XDgsbGA4KHAobCxsXDwocChsKHAobCxsKGxgOGA4XDwobCxsLGwocAAE4DhcPChsLGxcPChwXDgocChsLGwocChsLGxcPFw4LGxcPChwKGwsbFw4LGwsbChsLGwsbChwXDhgOFw4LHAobChwKGwABNw4YDgocChwXDgsbFw4LHAobChsLGwsbChwXDhgOChwXDgsbChwKHBcOCxsKHAobCxsKHAobFw8XDhgOCxsKHAobCxsAATcOFw8KHAobGA4KHBcOChwKHAobCxsKHAobGA4XDwocFw4KHAobCxsXDwobCxsLGwocChsKHBcPFw4YDgocChwKGwocAAE4DhcOCxwKGxcOCxwXDgocChwKGwsbChwKGxcPFw4LGxgOChwKGwsbFw8KGwsbChwKGwsbChwXDxcOGA4KHAobCxsKHAABOA8XDgsbChsYDgsbFw8KGwsbCxsKHAobCxsXDhgOCxsXDgsbCxsKHBcOCxsKHAobCxsKHAobGA4XDxcPChsLG",
      "low": "sgBqAg8KHAobChsLGwsbChwXDhgOCxsXDwobCxsXDgsbCxsKHAobCxsKHAobGA4XDxcPChsLGwobCxsAATcOGA4KHAobGA4KHBcOCxsKGwsbCxsKHAobGA4XDwobGA4LGwocFw4LGwobCxsLGwobCxsLGxcPFw4YDgsbChsLGwsbAAE2DxcOCxsKGxgOCxsXDgsbCxsKGwsbCxsKHBcOGA4LGxcOCxsLGxcPChsLGwocChsLGwocChsYDhcPFw4LGwocChsLGwABNw4YDgocChsYDgocFw4LGwocChsLGwobCxsYDhcPChsYDgsbChsYDgsbChwKGwsbChwKGwsbFw8XDhgOCxsKGwsbCxsAATcOFw4LGwsbFw8KHBcOCxsKGwsbChwKGwsbFw8XDgsbFw8KHAobGA4KHAobCxsKGwsbCxsKGxgOGA4XDwobCxsKHAobAAE5DhgOCxsKGxgOCxsXDgsbChwKGwsbCxsKHBcOFw8KHBcOCxsKGxgOCxsKGwsbCxsKGwsbCxsYDhcOGA4LGwobCxsLGwABNw4XDgsbCxsXDgscFw4LGwobCxsKGwsbCxsXDhgOCxsYDQsbCxsYDgobCxsLGwocChsLGwocFw4YDhcPChwKGwobCxsAATcOGA4KHAocFw4LGxcOCxsLGwobCxsLGwobGA4YDgocFw4LGwocFw8KGwocChsLGwsbChsLGxgOFw4YDgsbChwKGwsbAAE5DhgNCxwKGxgOChwXDgsbChwKGwsbChwKHBcOFw4LHBcOCxsKGxgOCxsKGwsbCxsKHAobCxsXDxcOGA4LGwobCxsKGwAF3AE5DhgOCxsKGxgOCxsX",
      "mediumLow": "sgDkARsYDQsbGA0MGgsbCxoLGwsbCxoZDRgOCxsYDQsbCxsYDhcOCxsLGwsaCxsLGgsbGA4YDRkNCxsLGwsaCxsAATkNGA4LGwobGA4LGxgNCxsLGwsaCxsLGwsaGA4YDgsaGA4LGwsbFw4YDgsbChsLGwsaCxsLGxgOGA0YDgsbCxoLGwsbAAE3DhgNDBoLGxgOChsYDgsbCxoLGwsbCxoLGxgOGA0LGxgOCxoLGxgOGA4LGgsbCxoLGwsbCxoYDhgOGA4LGgsbCxsLGgABOQ4YDQsbCxsYDgobGA4LGwsaCxsLGwsaCxsYDRkNCxsYDgsbChsYDhgNCxsLGwsbChsLGwsbGA0YDhgNDBsKGwsaCxsAATgNGA4LGwsaGA4LGxgNCxsLGwsbChsLGwsbGA0YDgsbFw4LGwsbGA0YDgsbCxoLGwsbCxoLGxgOGA0YDgsbCxoLGwsbAAE3DhgOCxoLGxgOCxsXDgsbCxoLGwsbCxsKGxgOGA0MGxcOCxsLGhgOGA4LGwsaCxsLGgsbCxsYDRgOGA4LGwobCxsLGwABNg4YDQsbCxsYDQsbGA4LGwsbChsLGgsbCxsYDhgNCxsYDgsbChsYDhgNCxsLGwsbCxoLGwsbGA0YDhgOCxsKGwsbChsABdwbChsY",
      "medium": "sgB+AxsKGwsbCxoLGxgOGA0LHBcOCxsXDwobCxsKGwsbCxsKGwsbCxsYDhcOGA4LGwobCxsLGwABNw4XDgsbCxsYDgobGA4LGwobCxsLGgsbCxsYDhcOCxsYDgocFw4LGwobCxsLGwobCxsLGwobGA4YDhgOChsLGwsbChsAATgOFw4LGwsaGA8KGxgNCxsLGwsbChsLGwsbFw8XDgsbFw4LGxgOCxoLGwsbCxsKGwsbCxoLGxgOGA4XDgsbCxsKGwsbAAE5DhcOCxsKGxgOCxsYDgobCxsLGwobCxsLGxcPFw4LGxcOCxsYDgsbChsLGwsbChsLGwsbChsYDhcPFw4LGwsbChsLGwABNw4YDgsbChsYDgsbFw4LGwsbChwKGwsbCxsXDhgOCxsXDgsbGA0LGwsbCxoLGwsbCxoLGwsbGA4YDRgOCxsLGgsbCxsAATcOGA0LGwsbGA4KGxgOCxsLGwobCxsKHAobGA4XDwobGA4LGhgPChsLGwobCxsLGwobCxsLGxcOGA4YDgocChsLGwsbAAE4DhgOChsLGxgOChsYDgsbChsLGwsbChsLGxgOFw4LGxgOCxsXDgsbCxsKGwsbCxoLGwsbChwXDhgOGA4KGwsbCxsLGwABNw4XDgsbCxsXDgsbFw8KGwsbChwKGwsbCxsXDxcOCxsXDgsbGA4KGwsbCxsKHAobCxsLGgsbGA4XDhgOCxsKHAobCxsAATcOGA4KHAobGA4KHBcOCxsKGwsbCxsKGwsbGA4YDgobGA4LGxcOCxsLGwocChsLGwsaCxsLGxgNGA4YDgsbChwKGwsbAAE4DhgOCxsKHBcOCxsXDwobCxsLGwobCxsLGxcOGA4LGxcOCxsYDgobCxsLGwobCxsLGwobCxsYDhcOGA4LGwsbChsLGwABNw4XDgscChsYDQsbGA4LGwobCxsLGwobCxsYDhcOCxsYDgsbFw4LGwocChsLGwsbChsLGwsbFw4YDhgOChwKGwsbChwAATcOFw4LGwsaGA4LGxgOChsLGwsbChsLGwsbFw8XDgsbFw4LGxgOChwKGwsbChwKGwsbChwKGxgOFw8XDgsbCxsKGwsbAAE5DhgOChwKGxgOCxsXDgsbCxoLGwsbChsLGxgOFw4LHBcOCxsXDgsbCxsKGwsbCxsLGgsbCxsXDhgOGA4LGwobCxsKGwAF3BsKGwAF3AAAAAA=",
      "mediumHigh": "sgBAARwXDgsbFw8KGxgOCxsKHAobChwKHAobGA4XDhgOCxsKGwsbCxsAATgOGA4KHAocFw4KHBcOCxsLGwocChsLGwocFw4YDgocFw4LGxcPChsYDgsbChwKGwocChwKGxcPFw4YDgsbChsLGwsbAAE3DhcPChsLGxcPChsYDgocChwKGwsbChwKGxcPFw8KGxcPChsYDgsbFw8KGwsbChwKGwsbChwXDxcOGA4KHAobCxsKGwABNw8XDgsbChwXDgsbFw4LGwsbChwKGwsbCxsXDhgOCxsXDwobGA4KHBcOCxsKHAobCxsKHAobGA4XDxcOCxsLGwocChsAATkOGA4KHAobGA4KHBcOCxsKHAobCxsLGwobGA4YDgocFw4LGxcOCxsYDgobCxsLGwocChsLGxcPFw4YDgocChwKGwsbAAXcAAAAAAAAAAA=",
      "high": "sgDgARwXDgsbChwKGwsbChwKGxgOFw4LGxgOChwXDhgOCxsKHAobCxsKHAobCxsXDhgOGA4LGwobCxsKHAABNg8XDgsbCxsXDgsbGA4KGwsbCxsKGwsbCxsXDxcOCxsXDwobGA4YDgocChsLGwobCxsLGwobGA4YDhcPChsLGwsbChsAATcPFw4LGwobGA4LGxcPChsLGwobCxsLGwobGA4YDgocFw8KGxcPFw4LGwsbChwKGwsbChwKGxgOFw4YDgsbCxsKGwsbAAE4DhgOChwKGxgOCxsXDgsbCxsKHAobCxsKHBcOGA4KHBcOCxsXDxcOCxsLGwobCxsLGwocChsXDxcOGA4LGwobCxsLGwABOQ4XDwocChsXDwocFw4LGwocChsLGwobCxsYDhcOCxsYDgsbFw8XDgocChsLGwsbChsLGwsbFw8XDhgOChwKGwsbChwAATYOGA4LGwocFw8KGxcPChsLGwsbChsLGwsbFw4YDgsbFw8KGxgOFw4LHAobCxsKGwsbCxsKGxgOGA4XDgsbCxsKHAobAAE5DhgOChwKGxgOChwXDgsbCxsKGwsbCxsKGxgOGA4KGxgOCxsXDxcOCxsKGwsbCxsKGwsbCxsXDxcOGA4KHAocChsLGwAF3A8XDgsbCxsX"
    },
    "forward": {
      "lowest": "sgDiAg4LGgsbCxoYDgsbCxsLGgsbCxsLGhgOGA4XDgsbCxsLGhgOAAE5DRgOCxsLGxgNCxsYDQwaCxsLGgsbCxsLGhgOGA4LGxgOChsLGwsbGA0LGwsaCxsLGwsaCxsYDhgNGA4LGwsaCxsYDgABNw4YDQsbCxsYDQsbGA4LGwsaCxsLGwsaCxsYDhcODBoYDgsaCxsLGxgOCxoLGwsaCxsLGwsaGA4YDhgOCxoLGwsbGA4AATYOGA4LGgwaGA4LGxgNCxsLGwsbCxoLGwsbGA0YDgsbFw4LGwsaCxsYDgsbCxoLGwsbCxoLGxgOGA4YDQsbCxsLGhgOAAE4DhgOChsLGxgOCxoZDQsbCxoLGwsbCxoLGxgOGA4KGxgOCxsKGwsbGA4KGwsbCxsLGgsbCxsYDRgOGA4LGwsaCxsYDgABNw0YDgsbCxoYDgsbGA0LGwsbCxsLGgsbCxsYDRgOCxsYDQsbCxsLGhkNCxsLGgsbCxsLGgsbGA4YDRkNCxsLGwsaGA4AAX8NGA4LGwobGA4LGxgNCxsLGwsbChsLGgsbGA4YDgsaGQ0LGwsbChsYDgsbChsLGwsaCxsLGxgNGA4YDgsaCxsLGxgOAAE3DRgNDBoLGxgOCxoZDQsbCxsLGgsbCxsLGhgOGA0MGhgOCxsLGgsbGA4LGwsaCxsKGwsbCxsYDRgOGA4LGwsaCxsYDgABNw0YDgsbCxoYDgsbGA4LGgsbCxsLGgsbCxsYDhcOCxsYDQwaCxsLGhgOCxsLGgsbCxsLGgsbGA4YDhgNCxsLGwsaGQ0AATcOGA4LGgsbGA4LGxcOCxsLGwsaCxsLGwsaGA4YDgsbFw4LGgsbCxsYDgsaCxsLGwsaCxsLGxgOGA0YDgsbCxoLGxgNAAE4DRgOCxsLGxgNCxsYDQsbCxsLGwsaCxsLGxgNGA4LGxgOCxoLGwsaGA4LGwsbCxoLGwsbCxoYDhgOFw4LGwsaCxsYDgAF3BsLGgsbGA==",
      "low": "sgGEAxsXDwocChsLGwobCxsLGxcPFw4LGxcPChwKGxcPChsLGwsbChwKGwsbChwXDhgOFw4LGwsbChsYDgABNw4XDwocChsYDgocFw4LGwocChsLGwocChsYDhcOCxsYDgsbChsYDgsbChsLGwsbChsLGwsbFw4YDhgOChwKGwsbFw8AATYPFw8KGwobGA4LGxcPChwKGwsbChsLGwsbFw4YDgsbFw8KGwsbFw8KHAobChsLGwsbChsLGxgOFw8XDgsbCxsKHBcOAAE4DhgOChwKGxgOChwXDgsbCxsKGwsbCxsKGxgOGA4KHBcPChsKGxgOCxsLGwobCxsLGwocChsXDxcOGA4LGwobCxsYDgABNw4XDgsbCxsXDwobFw8KGwsbCxsKGwsbCxsXDxcOCxsYDgobCxsXDwocChsLGwobCxsLGwobGA4YDhcOCxsLGwocFw4AAX8OFw8KHAobGA4KHBcOCxsKGwsbCxsKGwsbGA4XDwobGA4KHAobGA4KHAocChsLGwocChsLGxcPFw4YDgocChsLGxcPAAE2DhcOCxsLGxcPChsYDgocChwKGwsbChwKGxgOFw4LGxgOChwKGxgOChwKGwsbCxsKGwsbCxsXDhgOGA4KHAobCxsXDwABNg4YDgsbChwXDgsbFw8KGwsbChwKGwsbChwXDxcOChwXDgsbCxsXDwobCxsKGwsbCxsKGwsbGA4XDxcOCxsKHAobGA4AATcOGA4KGwsbFw8KGxgOCxsKGwsbCxsKGwsbFw8XDgsbGA4LGwobGA4LGwobCxsKHAobCxsKHBcOGA4YDgocChsLGxcPAAE4DRgOCxsLGxcOCxsYDgobCxsLGwocChsLGxcOGA4LGxcPChsLGxgOChwKGwsbChsLGwsbChsYDhgOFw4LGwsbChwXDgABNw4YDgobCxsYDQsbGA4LGwobCxsLGwocChsYDhcOCxsYDgsaCxsYDgsbChsLGwsbChsLGwsaGA4YDhgOChwKGwsbFw4AATcPFw4LGwsbFw4LGxgOChwKGwsaCxsLGwsaGA4YDgsbFw8KGwsbFw8KGwsbChwKGwsbCxoLGxgOGA0YDgsbCxsKGxgOAAE5DhgNCxsLGxcOCxsYDgsbChsLGwsbChsLGxgOFw8KGxgOCxsKGxgOCxsKGwsbCxsKGwsbCxsXDhgOGA4KHAobCxsXDgAF3AAAAAA=",
      "mediumLow": "sgDiAg4LGwocFw4YDgocChsLGwocChsLGxcPFw4YDgocChsLGxcPAAE4DhcPChwKGxcPChwXDgocChwKGwocChwKGxgOFw8KHBcOChwKGxgOFw8KGwsbChwKGwsbChwXDhgOFw8KHAobChwXDwABNg4YDgocChwXDgocFw4LGwocChsLGwocChsYDhcPChwXDgsbChwXDhgOChwKHAobChwKHAobFw8XDxcOCxsKGwsbFw8AATcOFw4LHAobFw4LGxgOChwKGwsbChwKGwsbFw4YDgsbFw8KHAobFw8XDwobChwKHAobChwKHBcOFw8XDgsbCxsKHBcOAAE4DxcOCxsKHBcPChsXDwocChsKHAocChsKHBcOGA4LGxcPChsLGxcPFw8KGwocChsLGwocChsYDhcPFw4LGwocChwXDgABNw4XDwobCxsXDwocFw4KHAocChsKHAocChsXDxcPChwWDwocChsYDhcOCxwKGwocChsLGwocFw4YDhcPChwKGwocFw8AATYPFw4LGwocFw4LGxcPChsLGwocChsLGwocFw8XDgocFw8KGwsbFw8XDgsbChwKHAobChwKHBcOFw8XDwocCRwKGxgOAAE4DhgOChwKHBcOChwXDwocChsKGwsbCxsKHBcOGA4KHBcOCxsKHBcPFw4KHAocChsKHAobCxsXDxcPFw4LGwocChsYDgABNg8XDgscCRwXDwobFw8KHAobCxsKHAobCxsXDxcOCxsXDwocChsXDxcPChsKHAocChsLGwocFw4YDhcPChwKGwocFw8AATYOGA4KHAobGA4KHBcPChsKHAobCxsKHAobGA4XDwocFw4KHAocFw8XDgocChwKGwocChsLGxcPFw4YDgocChwKGxcPAAE4DxcOCxsKHBcOCxwWDwocChsKHAocChsKHBcPFw4LGxcPChwKGxcPFw8KGwocChwKGwocChwXDxYPFw4LHAobChwXDgAF3BsLGwocFw==",
      "medium": "sgAmAxsXDwocChwKGwocChwKGwocChwXDhcPFw4LHAkcChwXDgABfw4XDwocChsXDwocFw4KHAocChsKHAocChwWDxcPChwWDwocFw4LGwocChwKGwocChwKGwocFw8XDhcPChwKHAkcFw8AATYOFw8KHAobFw8KHBcOChwKGwsbChwKHAobFw8XDwobFw8KHBcOCxsKHAobCxsKHAobCxsKHBcPFw4XDwocChsKHBcPAAE2DxcOChwKHBcOChwXDwobChwKHAobCxsKHBcPFw4KHBcOCxsXDwocChwJHAobCxsKHAobCxsXDxcPFw4LGwocChsYDgABNw4XDwocChsXDwobGA4KHAocChsKHAocChsXDxcOCxwWDwocFw4KHAocChwJHAocChsLGwocFw4YDhcPChwKGwocFw8AATcPFw4LGwocFw4LGxcPChwKGwocChwKHAkcFw8XDgsbFw8KGxgOChwKHAobChwKHAobChwKHBcOFw8XDwobChwKHBcOAAE3DhcPChwKGxcPChwXDwkcChwKGwsbChwKGxcPFw8KHBcOChwXDgscCRwKGwsbChwKHAobChwXDxcOFw8KHAobCxsXDwABNg8XDwobChwXDwobFw8KHAobCxsKHAobCxsXDxcOCxsXDwocFw4KHAocChsKHAocChwJHAobGA4XDxcPChsLGwocFw8AATcPFw4LGwobGA4LGxcPChsLGwocChwKGwocFw4YDgocFw8KGxcPChwKGwocChwKGwsbChwKGxcPFw8XDgsbChwKGxgOAAE3DhcOCxwKGxcPChwXDgocChwKGwocChwKGxcPFw4LHBYPChwXDgsbChwKGwocChwKGwsbChwXDxcOFw8KHAobChwXDgABNw4YDgocChwXDgocFw4LGwocChwKGwocChsYDhcPChwXDgsbFw8KHAobChwKGwsbChwKGwsbFw8XDxcOChwKHAobFw8AATgPFw8KHAkcFw4LGxcPChwKGwsbChwKGwocFw8XDwobFw8KGxgOChwKHAobChwKHAobChwKHBcOFw8XDwocCRwKHBcOAAXcGwo=",
      "mediumHigh": "sgGEAxwXDwocCRwKHAobCxsKHBcOGA4KHBcPChsXDwocFw4KHAocChsKHAocChsXDxcPFw4LGwocChsYDgABNg8XDwobCxsXDwobGA4KHAobCxsKHAobCxsXDxcOCxsXDwocFw4KHBcPChsLGwocChsKHAocFw8WDxcPChwKGwocFw4AAX8OFw8KHAobGA4KHBcOCxsKHAocChsKHAocFw4XDwocFw4KHBcPChwWDwocChsLGwocChwKGxcPFw4YDgocChsLGxcPAAE2DhcPChwKGxcPChwXDgocChwKGwsbChwKHBYPFw4LHBcOChwXDwocFg8KHAobChwKGwsbCxsXDxcOGA4KHAocChsXDwABNg8XDgsbChwXDwobFw8KHAobChwKHAobChwXDxcOChwXDgscFg8KHBcPChsKHAobCxsKHAobGA4XDxcPChsKHAocFw8AATYOFw8KHAobFw8KHBcOChwKHAobCxsKHAocFg8XDwocFw4KHBcOCxsXDwocChsKHAocChsLGxcPFw4YDgocChsLGxcPAAE4DhcPChsLGxcPChwXDgocChwKGwocChwKGxcPFw8KGxcPChwXDwobFw8KGwsbChwKHAobChwXDxcOFw8KHAobChwXDgABNw8XDgocChsYDgocFw4LGwocChwKGwocChwXDhcPChwXDgsbFw8KGxgOChwKHAobChwKHAobFw8XDhgOChwKGwsbFw8AATcOFw8KHAobFw8KGxgOChwKHAobChwKHAobFw8XDgscFw4KHBcPChsXDwobCxsKHAocChsKHBcPFw4XDwocChsKHBcPAAE3DxcPChsKHBcPChwWDwocChsKHAocChsLGxcPFw8KGxcPChsYDgocFw8KGwocChsLGwocChsYDhcPFw8KGwsbChwXDwABNg4XDwocChsXDwocFw4LGwocChsLGwocChwWDxcPChwXDgocFw8KHBYPChwKGwocChwKGwocFw8XDxcOChwKGwsbFw8AATYPFw4LGwocFw4LGxcPChwKGwocChsLGwocFw8XDgocFw8KHBcOChwXDwobChwKGwsbChwKGxgOFw8XDwobChwKHBcOAAE5DhcPChsLGxcPChwXDgocChwKGwocChwKGxcPFw4LGxcPChwXDwobFw4LGwsbChwKGwsbChwXDhgOFw8KHAobChwXDwAF3AAAAAA=",
      "high": "sgDoABsKHAobGA4XDxcPChsKHAocFw4AATcOFw8KHAobFw8KGxgOChwKGwsbChwKGwsbFw8XDwobGA4KHBcOGA4KHAobCxsKHAocChsKHBcOGA4XDwocChsKHBcPAAE2DhgOChwKHBcOChwXDwobChwKGwsbChwKGxgOFw8KHBcPChsXDxcOCxsKHAocChsKHAocChsXDxcOGA4LGwobCxsXDwABOQ4XDwobCxsXDwocFw4KHAobCxsKHAobCxsXDxcPChsXDwocFw4YDgocChsLGwocChwKGwocFw8XDhcPChwKGwocFw4ABdw="
    }
  }
}
```

**Describe the bug**

When I try to control the fan I get an error: Failed to call service fan/turn_on. SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given

**Debug log**

```Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
First occurred: December 10, 2023 at 10:36:34 PM (5 occurrences)
Last logged: 9:30:42 AM

[139750257094464] SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
[139750521368384] SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
[139750338373184] SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
[139750514719808] SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 305, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
```

**Comment by hvddrift** [comment]
I rolled back to HA 2023.11.3 and it works again

**Comment by dannyleong74** [comment]
Me too getting same error. i'm retore back to 20231.11.3 untill the error fix.

**Comment by sfortis** [comment]
Until PR is approved/merged, you can manually change like 249 of fan.py in your custom_components/smartir folder to fix this issue.

https://github.com/smartHomeHub/SmartIR/pull/1167/files

**Comment by vassilis-panos** [comment]
Please confirm that the latest update fixes the problem.
Thanks

**Comment by sfortis** [comment]
All good here...eyxaristw @vassilis-panos !

**Comment by dannyleong74** [comment]
> Please confirm that the latest update fixes the problem. Thanks

Problem fix. Thanks vassilis-panos

**Comment by hvddrift** [comment]
Fixed thank you.
