### ISSUE TITLE
SmartIRFAN Turn_On does not work any more.

### ISSUE THREAD

**Issue by ronjtaylor** [smartHomeHub/SmartIR#1177]
I have a DC FAN that I have been using for some time and all of a sudden the Turn On gives the error in logs below.  I use the Mushroom Button Fan control in my front end.
As a work around I can use the fan speed increase or decrease and these work fine

My system
![image](https://github.com/smartHomeHub/SmartIR/assets/46874942/7c1f8e7a-1e9f-432f-84e3-a7f9bb32be07)

FROM LOGS

<Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:238
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:23:06 AM (3 occurrences)
Last logged: 6:37:04 AM

[140181400347328] SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
[140180308300992] SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 238, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2067, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2104, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 272, in handle_service
    return await service.entity_service_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 878, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 948, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 305, in async_handle_turn_on_service
    await self.async_turn_on(percentage, preset_mode, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given
!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

**Comment by make-all** [comment]
Was this on the latest release, made a few days before your report?  Because this seems like exactly the bug that release was supposed to fix.

**Comment by ronjtaylor** [comment]
How do I know what the latest release is?
I have just checked that I still have the same bug and I do. There is a HA core 2024.1.0 out about 2 hrs ago but I saw and issue where it still has the same problem?
I usually do my HA core updates on a Saturday each week so I have time to mop up any issues.
I am under the impression that restarting HA will prompt for updates on SMARTIR??
I looked at the Fan.py code and it has exactly the same number of lines as the one here so I am confused??
Any Help appreciated.

**Comment by make-all** [comment]
If you installed through HACS from this repository (and not a mirror), you should have got a notification to update this integration when it was available, but to check that you have the fix, check line 249 of /config/custom_components/smartir/fan.py whether it is the version in red (old) or green (new) from https://github.com/smartHomeHub/SmartIR/commit/e49543c3e0e33f1af10706056721196877eb97f8

The new version adds the third parameter that HA 2023.12 is expecting, so it should resolve
"TypeError: SmartIRFan.async_turn_on() takes from 1 to 2 positional arguments but 3 were given" at least in theory.  But if you confirm that you already have the latest, and the bug is still there, then both @sfortis and myself have missed something.

**Comment by ronjtaylor** [comment]
I have checked the fan.py in my custom_Components and it does not have the updated line 249.
I cannot remember how I installed it but I usually do install things through HACS -> integration.  However when I go into HACS Integration I cannot see it in my list of integrations and when I search I only see SmartIR as an irrigation integration.
I didn't get any notifications to update like I do with other HACS integrations??
What do you suggest I do?

**Comment by ronjtaylor** [comment]
OK I think I have figured it out.  I had to add the custom repositories in HACS to see the smartir integration.  I then downloaded it and restarted HA.
Seems to have done the trick.  I now remember having to do this in the first place but that was a few years ago.  The integration is now showing in HACS so I don't know why it disappeared??

Hopefully all good now.

**Comment by make-all** [comment]
If it is all good after the upgrade, maybe you can close this issue, as the developer seems very busy over the past year, so it will help them to not have to sort through issues that are already fixed.
