### ISSUE TITLE
JSON file for Midea MCD-24HRN1-Q1

### ISSUE THREAD

**Issue by Beduir** [smartHomeHub/SmartIR#121]
JSON file with codes for Midea MCD-24HRN1-Q1 air conditioner for Xiaomi controller.

[1382.zip](https://github.com/smartHomeHub/SmartIR/files/3175530/1382.zip)

**Comment by smartHomeHub** [comment]
Thanks for submitting the first codes for the Xiaomi controller. I really appreciate.
