### ISSUE TITLE
Climate Platform - Fujitsu Code 1281 - add further supported model to table 

### ISSUE THREAD

**Issue by SmbKiwi** [smartHomeHub/SmartIR#125]
**Home Assistant version**
      092.2

**SmartIR version**
    Latest - 1.5.0

**SmartIR configuration**

Climate.yaml 

- platform: smartir
  name: Lounge Fujitsu Heatpump
  unique_id: lounge_heatpump
  device_code: 1281
  controller_data: xx.xx.xx.xx
  temperature_sensor: sensor.xx
  power_sensor: binary_sensor.xx

Add configuration here:

Using Broadlink Controller. 

**Describe the bug**

SmartIR Climate platform - Fujitsu Code 1281 also supports remote model AR-ry3 using Broadlink controller. I have used it successfully with my Fujitsu heatpump with uses the AR-RY3 model remote.

So in the docs please add AR-RY3 as a model that works using code 1281 on this page:      
 
https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#available-codes-for-climate-devices

**Debug log**

NA

Add your logs here.

NA

**Additional context**

NA

**Comment by smartHomeHub** [comment]
Thanks for sharing
