### ISSUE TITLE
Power state in the climate panel cannot update correctly by the state of real power sensor.

### ISSUE THREAD

**Issue by larisalee** [smartHomeHub/SmartIR#127]
**Home Assistant version**
0.93.1
**SmartIR version**
1.5.0
**SmartIR configuration**

climate: 
- platform: smartir
  name: Living AC
  unique_id: living_ac
  device_code: 9998
  controller_data: 192.168.1.26
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.acpower_sensor (I use xiaomi door window sensor to monitor the state)

**Describe the bug**

The power state of climates cannot update correctly eventhough I add the power sensor in the configuration file.
For example, if I send the wrong turn on code, my ac will not turn on and the power sersor will show it "off", but in SmartIR panel, the power state still changes to "on".  
For another example, if I turn on the ac from my real remote controller, the SmartIR panel cannot changes the showing state to "on".

**Comment by smartHomeHub** [comment]
This is weird. Especially for the first example the state of the component should be the current mode (even if the component fails to send the ir command) and not “on”.
Did you check if the binary_sensor.acpower_sensor goes to on/true if you turn on the ac by the remote control?

**Comment by larisalee** [comment]
Yes, my binary_sensor.acpower_sensor works fine if I turn on the ac by original remote.

**Comment by larisalee** [comment]
[https://i.imgur.com/biyjknY.jpg](url)
