### ISSUE TITLE
Error adding repository to HA

### ISSUE THREAD

**Issue by frozendark01** [smartHomeHub/SmartIR#1290]
I am trying to add the repository to HA but i get this error
https://github.com/smartHomeHub/SmartIR is not a valid add-on repository
![Screenshot 2024-07-24 at 21 51 24](https://github.com/user-attachments/assets/b7e41cde-e97e-4c33-aa6a-ffc7d7ce4aa7)
i have no issues with other repository
Home Assistant Version: 2024.7.3

**Comment by frozendark01** [comment]
i was do it wrong.

**Comment by ohmstance** [comment]
How did you do it the right way??

**Comment by ohmstance** [comment]
Ah, I'm dumb. I'm supposed to add the repo within HACS, not the Add-ons menu.

**Comment by Miccio-AN** [comment]
Same problem. I'm inexperienced... sorry but I can't add it as an extra repo to HACS. Can you tell me the correct procedure step by step... Thank you!
