### ISSUE TITLE
Homekit support fan speed control and swing direct

### ISSUE THREAD

**Issue by daddvok** [smartHomeHub/SmartIR#134]
Hello, as I understand it, at the moment there is no support for adjusting the speed and direction of the blowing of the air conditioner, is it possible to add this feature?
![A1C177F2-3C10-4CB9-A9FA-0A9332B4CFBF](https://user-images.githubusercontent.com/47695947/58842335-5b726f80-8676-11e9-8d4a-e9aba3c7448c.jpeg)

**Comment by smartHomeHub** [comment]
I'm not a Homekit user, so I can not help.
