### ISSUE TITLE
How to add codes from broadlink cloud?

### ISSUE THREAD

**Issue by snapplecap84** [smartHomeHub/SmartIR#136]
The codes for my A/C are available from broadlink cloud, and I downloaded them by following these instructions: [https://github.com/mjg59/python-broadlink/issues/74#issue-211230377](url)

I have zero experience with IR codes and have been digging for hours on how to integrate this with SmartIR.  Any help would really be appreciated.

My A/C manufacturer is Carrier.
The Broadlink cloud remote number is 1200 (printed on the top right of the iOS app).  It can be downloaded from [http://cloud.broadlink.com.cn/irda_code/1200.gz](url)
The SmartIR remote code for Carrier A/Cs (1160) does not work.
The SmartIR remote code 1200 does not work either.

Is it possible to convert the broadlink cloud .gz file into something SmartIR can use?
Thank you for your help.

**Comment by unclehook** [comment]
The topic is still discussed here:
https://github.com/mjg59/python-broadlink/issues/74

There are indications to extract the codes and then convert them into formats usable in other projects but no one has yet understood how the files are organized and therefore for now it is not possible to convert them for SmartIR, at least so it seems to me to have understood.

I suggest following the issue and awaiting developments.

**Comment by snapplecap84** [comment]
Thank you very much for your reply
