### ISSUE TITLE
Add support for HACS

### ISSUE THREAD

**Issue by isabellaalstrom** [smartHomeHub/SmartIR#142]
I'm not using the issue template because this is not that kind of an issue, hope that is okey.

This is what needs to be done to add support for HACS (Home Assistant Component Store): https://custom-components.github.io/hacs/#note-for-developers

It would be awesome for this component to be added there so more people could find it and so that it's easier to update.

**Comment by aidbish** [comment]
+1 for supporting HACS, Would be great if possible

**Comment by kaosmagix** [comment]
+1

**Comment by unclehook** [comment]
+1

**Comment by smartHomeHub** [comment]
SmartIR has a built-in updater. When a new version is available, a notification in HA will appear and you can update it by calling the smartir.update service. One of the reasons I built this updater is that it checks if the new version is compatible with your HA instance. Most updates of SmartIR are due to breaking changes of the last HA version.
If at some point HACS is able to handle this situation I'll definitely implement it.

**Comment by ludeeus** [comment]
@smartHomeHub would this be good enough?
<https://custom-components.github.io/hacs/next/developer/integration/#github-releases-optional>

**Comment by Bastiencc** [comment]
+1 for supporting HACS, or maybe a sensors?

**Comment by cubilon** [comment]
+1 for HACS

**Comment by vMeph** [comment]
+1 for HACS

**Comment by jokerigno** [comment]
I'm also interested.

**Comment by smartHomeHub** [comment]
OK. Support for HACS :) :)

**Comment by KC-inDomus** [comment]
I can't find SmartIR on HACS.. how to add your repository?

**Comment by smartHomeHub** [comment]
> I can't find SmartIR on HACS.. how to add your repository?

https://custom-components.github.io/hacs/usage/settings/#add-custom-repositories

**Comment by KC-inDomus** [comment]
I mean which is the url to be used

**Comment by smartHomeHub** [comment]
> I mean which is the url to be used

https://github.com/smartHomeHub/SmartIR

**Comment by KC-inDomus** [comment]
tried adding https://github.com/smartHomeHub/SmartIR to HACS repository: 

`Could not add https://github.com/smartHomeHub/SmartIR at this time, check the log for more details.`

**Comment by cubilon** [comment]
+1
Not working via HACS, can't find the correct repository to be added.

**Comment by cubilon** [comment]
SOLVED. "integration" must be selected while adding repository.
