### ISSUE TITLE
Support for Hualing / Miller ac w/ Broadlink(json codes included)

### ISSUE THREAD

**Issue by soppilif** [smartHomeHub/SmartIR#143]
**Home Assistant version**
0.94.x
**SmartIR version**
latest
**SmartIR configuration**

[1700-1701.zip](https://github.com/smartHomeHub/SmartIR/files/3294168/1700-1701.zip)

```yaml

Add configuration here

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**
The zip file contains 2 files:
- 1700.json 
with full support of the cool, heat, dry, auto modes and their respective fan speeds (low, mid, high, auto)

- 1701.json
with support for only cool and heat modes and their respective fan speeds (low, mid, high, auto)

for Hualing (aka Miller) ac units

The only thing that is missing from the plugin is the level of the shades which regulates how high or low it emisses the airflow to the enviroment

**Comment by soppilif** [comment]
Hello, are the codes implemented? Under what number?

**Comment by smartHomeHub** [comment]
1840 in rc branch. Thank you for your contribution

**Comment by soppilif** [comment]
Hello there.
I have updated the codes empasizing on the position of the a/c blinds for cool and heat modes.
For cool mode i have placed the blinds on the upper level whereas for the heat mode the blinds are on the lower level.
Would be cool to be implemented since when I place the new file the whole entity breaks on hassio.
[1840.json.zip](https://github.com/smartHomeHub/SmartIR/files/3996062/1840.json.zip)
