### ISSUE TITLE
Media Player is always Off when change the name

### ISSUE THREAD

**Issue by cryptooth** [smartHomeHub/SmartIR#144]
**Home Assistant version**
0.94.3

**SmartIR version**
Latest commit 9984fe2  on May 14

**SmartIR configuration**

```
  - platform: smartir
    name: Omer Belek TV
    unique_id: omer_belek_tv
    device_code: 1000
    controller_data: 192.168.86.71
    power_sensor: sensor.ytkstatus
```

**Describe the bug**

When I change name and uniqe_id from "living_room_tv" to "omer_belek_tv" or antoher name, media_player card state is Off. 

When  I reverse to living_room_tv, everythings works well

**Comment by smartHomeHub** [comment]
Did you resolve this?

**Comment by cryptooth** [comment]
I will try to update component and try to change entity name
