### ISSUE TITLE
What is the right way to share the codes?

### ISSUE THREAD

**Issue by unclehook** [smartHomeHub/SmartIR#146]
**Home Assistant version**
ALL
**SmartIR version**
ALL
**SmartIR configuration**

```yaml

not significant

```

**Describe the bug**

Please indicate in the Readme.md or in the wiki what is the correct procedure to send new codes.
Options:

1. Create a fork, add codes, fix the related .md, create a "Pull request"
2.  Creating an issue, the add the files with the produced codes.

Which is preferable?

**Comment by smartHomeHub** [comment]
Hello and thank you for your willingness to contribute. Any of the methods you describe are acceptable.
