### ISSUE TITLE
Error: The device JSON file is invalid

### ISSUE THREAD

**Issue by aheath70** [smartHomeHub/SmartIR#147]
Home Assistant version: 0.94.4

**SmartIR version: 1.5.0

HA log file states "The device JSON file is invalid" and media player does not appear in HA UI. Only started happening after upgrade from 0.94.3 to 0.94.4. JSON file has been validated using YAMLLINT web site and comes back valid.

Add your logs here.
2019-06-20 15:34:10 ERROR (MainThread) [custom_components.smartir.media_player] The device JSON file is invalid

**Comment by smartHomeHub** [comment]
I just updated my instance and everything work as expected. Which device code are you using?

**Comment by aheath70** [comment]
1000 Apologies! 

I think I had an extra comma in there, on the last [source] item. It passed YAMLLINT, but obviously didn't pass whatever YAML validation is in the code.
