### ISSUE TITLE
Please change power sensor state 

### ISSUE THREAD

**Issue by keitetran** [smartHomeHub/SmartIR#15]
With other component power sensor will return state ON OFF or unavailable. Ex MQTT sensor will return unavailable when device power to off. That use state ON or unavailable only. Can u change it on component ? 
`        if power_state:
            if power_state.state == STATE_ON:
                self._state = STATE_ON
            else
                self._state = STATE_OFF
                self._source = None`

**Comment by smartHomeHub** [comment]
I'm afraid I'll reject this request. Unavailable state means that the sensor is... unavailable and not off. To accomplish this, please use a template binary sensor. Tell me if you need an example.
