### ISSUE TITLE
TV CODES - LG Scarlet 37LG6000, LG Remote MKJ40653802

### ISSUE THREAD

**Issue by unclehook** [smartHomeHub/SmartIR#150]
**Home Assistant version**
0.94.3
**SmartIR version**
1.5.0
**SmartIR configuration**

```json

   "manufacturer": "LG",
    "supportedModels": ["LG Scarlet 37LG6000, LG Remote MKJ40653802"],
    "supportedController": "Broadlink",
    "commandsEncoding": "Base64",
```

**Additional context**
Full remote codes for TV LG Scarlet 37LG6000 taken from a LG Remote MKJ40653802.

**File**
[37600.zip](https://github.com/smartHomeHub/SmartIR/files/3312056/37600.zip)

(filename as product name without letters and a zero less to take short)

**Comment by smartHomeHub** [comment]
Hello and thank you for your contribution. Please clean up the file with the unsupported commands.

**Comment by unclehook** [comment]
Hello, I will try but where I can find the list of supported commands?
Otherwise some indication about which are the unsupported commands?
