### ISSUE TITLE
auto issue

### ISSUE THREAD

**Issue by tongt15** [smartHomeHub/SmartIR#153]
**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

broadlink climate when click auto in lovelace ui,  it just jump to switch off button. status shows not correct

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by smartHomeHub** [comment]
Did you resolve this issue?
