### ISSUE TITLE
Google assistant shows thermostat in Fahrenheit but AC only functions in Celsius. 

### ISSUE THREAD

**Issue by adrianocr** [smartHomeHub/SmartIR#155]
**Home Assistant version**

Latest docker pulled fresh before this issue. 

**SmartIR version**

Latest, pulled fresh before filing this issue.

**Describe the bug**

This ac unit only works in Celsius and there's no way to change it. In home assistant the the thermostat correctly shows and works in Celsius. However, in the Google home app the thermostat shows in Fahrenheit and tries to issue calls to temperatures in Fahrenheit which doesn't work. Is there a way to force a temp unit?

**Comment by brent0np** [comment]
Have you tried saying 'Hey Google, I prefer Celsius'
