### ISSUE TITLE
Base64 codes for AC

### ISSUE THREAD

**Issue by friendodevil** [smartHomeHub/SmartIR#156]
Where should I be looking to find Base64 codes for YB1FA and RC08B AC remote controls?

**Comment by mac587** [comment]
For YB1FA try Gree codes, 1180 or 1181

**Comment by friendodevil** [comment]
Thank you @mac587 : 1180 worked for YB1FA.
Which profile should be used for RC08B?

**Comment by mac587** [comment]
Try Diatsu 1760, failing that try codes from Midea or Hisense

**Comment by friendodevil** [comment]
@mac587 tried codes for Diatsu, Midea, Hisense but no luck. Looking for RC08B remote codes for Electra air conditioner.
