### ISSUE TITLE
Component not loading successfully.

### ISSUE THREAD

**Issue by CountParadox** [smartHomeHub/SmartIR#158]
**Home Assistant version**
0.95.4
**SmartIR version**
er.....Latest commit 9984fe2 ?
**SmartIR configuration**

```yaml

- platform: smartir
  name: Bedroom AC
  unique_id: bedroom_ac
  device_code: 1180
  controller_data: 172.16.0.88
  temperature_sensor: sensor.temperature_158d00019cad62
  humidity_sensor: sensor.humidity_158d00019cad62

```

**Describe the bug**

The component does not start successfully.

**Debug log**

```text

2019-07-03 20:32:50 ERROR (MainThread) [homeassistant.setup] Error during setup of component smartir
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 153, in _async_setup_component
    hass, processed_config)
  File "/config/custom_components/smartir/__init__.py", line 43, in async_setup
    check_updates = conf[CONF_CHECK_UPDATES]
TypeError: 'NoneType' object is not subscriptable

2019-07-03 20:32:50 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform smartir.climate: Unable to set up component.

```

**Additional context**

Its a fresh install, I have not used the component before.
I have successfully installed and used OTHER custom components.

**Comment by aidbish** [comment]
Is smartir in its own config file? as in split up config
have you setup climate: in configuration.yaml?

this is mine in configuration.yaml
```
climate:           
  - platform: smartir
    name: Bedroom Room AC
    unique_id: master_bedroom_ac
    device_code: 1600
    controller_data: 10.0.0.106
    temperature_sensor: sensor.temperature_158d000208ead2
    humidity_sensor: sensor.humidity_158d000208ead2
```

**Comment by ShaharLahav** [comment]
I have the same error and mine is in the configuration.yaml file... same exact error and stack trace...

**Comment by smartHomeHub** [comment]
You need to include `smartir:` in your configuration.

```
smartir:

switch:
  - platform: broadlink
    host: 192.168.10.10
    mac: '00:00:00:00:00:00'
    
climate:
  - platform: smartir
    name: Office AC
    unique_id: office_ac
    device_code: 1000
    controller_data: 192.168.10.10
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

```

**Comment by thanasisloi7** [comment]
Hello, i updated today the HA and the component, after that i get the error 
Platform not found: climate.smartir
Any suggestion to fix the problem ?

**Comment by smartHomeHub** [comment]
> Hello, i updated today the HA and the component, after that i get the error
> Platform not found: climate.smartir
> Any suggestion to fix the problem ?

Dear Thanasi,
Please open a new issue by following the template or contact with me directly in greek via a PM at HA forums.
