### ISSUE TITLE
Line 28 from climate.py

### ISSUE THREAD

**Issue by cjsmns** [smartHomeHub/SmartIR#16]
With Version 1.1.0, line 28 is causing issues with HA. I've had a look through the previous versions and this line doesn't exist, so I removed it and everything started working properly again.

I'm not sure if this is a typo or something else is meant to be here.

https://github.com/smartHomeHub/SmartIR/blob/2712a2d201b33b5991ea1f2060c9c263dd60e7cc/smartir/climate.py#L28

**Comment by smartHomeHub** [comment]
Did you update the component through custom_updater?

**Comment by cjsmns** [comment]
Yep. What I had is exactly the same as on here.

**Comment by smartHomeHub** [comment]
I’m afraid custom_updater doesn’t fit well with this component. We need also to update the __init__.py file and custom_updater doesn’t provide this function.
Could you manual update __init__.py, climate.py and tell me the results?

**Comment by cjsmns** [comment]
Yep. My `__init__.py` file was empty. Didn't think to look at that.

Do you want me to test with Line 28 in climate.py?

**Comment by smartHomeHub** [comment]
Yes

**Comment by cjsmns** [comment]
Ok. It's working again. Have custom_updater not updating `__init__.py`, and it being blank with the new version seems to be the issue.

**Comment by smartHomeHub** [comment]
Sorry for the inconvenience. I'm trying to handle this situation. Thank you,

**Comment by madrose** [comment]
I had exactly the same issue. this is fixed now.
👍
