### ISSUE TITLE
Temperature: Celsius control of US Fahrenheit unit 

### ISSUE THREAD

**Issue by apschaefer** [smartHomeHub/SmartIR#160]
Is there a Fahrenheit JSON for Midea climate code 1380? 

My Danby / Midea window units do work fine in Celsius, but it is a bit confusing to have Fahrenheit displayed (using a remote temperature sensor) and be adjusting in Celsius.  This is a US A/C unit and the US remote on these units appears to send a specific Fahrenheit temp code. However, when SmartIR adjusts, it starts showing Celsius on the unit's display (not just in Homeassistant).  

A couple unrelated questions. 

Is there a SmartIR option for "lights out / LED" mode (it is a mode common to a lot of these units that turns off the LED on the AC unit).  Unfortunately this appears to be an IR only option and it does not persist through a power-cycle on Midea/Danby units

Is there a description of how the remote temperature,humidity or power sensor logic operates?

**Comment by puneit-hassio** [comment]
For the LED query, they way I have done is - I did a Broadlink.learn for the LED button on the remote. And then, I am using the code as a switch in Home Assistant. Added it to Good night scene on Homekit - so when I say good night, Home Assistant turns of the lights of the room and the LED on the AC.

**Comment by smartHomeHub** [comment]
There is no device code file in F for Midea. I'm afraid you need to make your own.

Temperature and humidity sensors are used to report the values to supported voice assistants. The power sensor accepts a binary state to actually determine the state of your unit in case you turn it on or off from the remote control.
