### ISSUE TITLE
Remote HIYASU ref YK1F

### ISSUE THREAD

**Issue by mafede** [smartHomeHub/SmartIR#163]
246/5000
Good afternoon.

I'm setting the climate for the home air, and I've got the codes for Mitsubishi, but for an air of the HYASU brand (remote ref YK1F) I can not find them.

Does anyone use it or know another compatible?

Thank you

**Comment by mac587** [comment]
Try Gree codes, 1180 or 1181

**Comment by mafede** [comment]
Ok 1180 Thank’s

**Comment by AntonEvmenenko** [comment]
@mac587 thank you so much for this information; it's very valuable knowledge for me! If you don't mind me asking, where did you learn this from?
