### ISSUE TITLE
Changes to climate component are required to be compatible with 0.96

### ISSUE THREAD

**Issue by aidbish** [smartHomeHub/SmartIR#164]
**Home Assistant version**
0.96

The changes in 0.96 require the climate component to be changed to be compatible.
Testing on 0.96b0 shows component does not load, no errors in logs

https://github.com/home-assistant/home-assistant/pull/23899

**Comment by smartHomeHub** [comment]
I have a quick fix in the RC branch. Keep in mind that with this update the accepted modes are heat, cool, heat_cool, auto, dry and fan_only. It is not possible to use any other mode such as ai, ion, etc. If your JSON file contains a fan mode you must rename it to fan_only. I have already fixed the JSON files that are shared in the repo.

**Comment by aidbish** [comment]
Just tested rc branch and can confirm that the climate component is now working again

**Comment by CarpeDiemRo** [comment]
Hello, after I update to the last version of HA, SmartIR stopped working. When I try to make the update to the last version of SmartIR, as was described in the persistent notification, an error is returned. I attached some print screens. I think something is missing me. Could you, please, advise me what to do. 
![2019-07-18_11h56_49](https://user-images.githubusercontent.com/38489167/61444194-97764100-a953-11e9-8c41-c7fe4f414790.png)
![2019-07-18_11h57_30](https://user-images.githubusercontent.com/38489167/61444203-9c3af500-a953-11e9-9409-427018fa0c8f.png)
![2019-07-18_11h57_40](https://user-images.githubusercontent.com/38489167/61444205-9d6c2200-a953-11e9-8a94-074c31e08bc1.png)
![2019-07-18_11h57_05](https://user-images.githubusercontent.com/38489167/61444211-9f35e580-a953-11e9-89e6-97ca5acc97df.png)
![2019-07-18_11h56_34](https://user-images.githubusercontent.com/38489167/61444218-a0671280-a953-11e9-9471-247404e44df9.png)

**Comment by smartHomeHub** [comment]
Could you try again please?

**Comment by CarpeDiemRo** [comment]
Unfortunately, the same result.

![2019-07-18_12h09_07](https://user-images.githubusercontent.com/38489167/61444831-d9ec4d80-a954-11e9-89a8-dc12ebd33a1a.png)

**Comment by smartHomeHub** [comment]
Oh. please change update_branch to master or comment it out

**Comment by CarpeDiemRo** [comment]
It works. I changed update_branch to master, and the update was successful. Thank you very much and well done for your work.

**Comment by Klagio** [comment]
Hi, I just updated to 0.96, and smartir to 1.6.2, now all my climate.xxxx disapperared, but I have nothing in 
 homeassistant LOG

**Comment by Klagio** [comment]
a restart fixed it

**Comment by adrianmihalko** [comment]
So fan mode is currently not working?

<img width="734" alt="Screenshot 2019-08-12 at 12 27 59" src="https://user-images.githubusercontent.com/733361/62859161-a35be580-bcfc-11e9-94b4-822f6935be21.png">
