### ISSUE TITLE
Codes from Fujitsu AR-RCE1E remote

### ISSUE THREAD

**Issue by mac587** [smartHomeHub/SmartIR#169]
Codes from Fujitsu AR-RCE1E remote, euro celsius version.
Full temperature range 16 to 30 only applicable to "heat" mode,
therefore in "cool", "auto" and "dry" 16, 17, 18 all simply send 18

Codes were captured with swing function off (personal preference), as swing command is not stand alone such as "set" and "powerfull" buttons (not implemented either), but rather is sent as: mode+temp+fan+swing

Note: For new version rename "fan" mode to "fan_only"
[1285.txt](https://github.com/smartHomeHub/SmartIR/files/3390071/1285.txt)

**Comment by smartHomeHub** [comment]
Amazing! Thank you.
