### ISSUE TITLE
Don't round temperature sensor value

### ISSUE THREAD

**Issue by adamrutt** [smartHomeHub/SmartIR#17]
In the previous version of this component the temperature sensor value was not rounded up. In this version the temperature sensor value gets rounded to an integer. Not a big deal but my temperature sensor gives me 1 decimal point which gets lost at the moment. I had a look at the code I can't see where it might get rounded. Would appreciate it. Thanks.

**Comment by smartHomeHub** [comment]
HA rounds the value if the precision is 1.0 (PRECISION_WHOLE). Precision is important for voice assistants.

**Comment by pilievwm** [comment]
OK but in my HA temperature sensor the temperature reads 20.5  which is ok
![image](https://user-images.githubusercontent.com/5072036/53306710-46c55500-3899-11e9-8e35-20b79c8a1c1a.png)

All my automation are based on those values and if I have to work with integers the precision of the temperature climate will get worse. Is it possible somehow to tell HA that the values have to be with decimals? 

My Google home works perfect before. If the temperature is 20.5 and i say: Warm up the living room, it will increase the temperature with 2 degrees. 

For me it is a big deal and crucial to have ability to work with decimals.

**Comment by pilievwm** [comment]
Also the graphic of the current temperature gets strange. Before the update it was smooth and with temperature collisions while after the update it gets strange for me :(
![image](https://user-images.githubusercontent.com/5072036/53306934-dbc94d80-389b-11e9-98c4-3b5ec094a6d6.png)

**Comment by smartHomeHub** [comment]
Fixed. Please update the climate.py

**Comment by pilievwm** [comment]
I confirm it is working as before! 
Thanks for your fast reaction!

**Comment by adamrutt** [comment]
Yes confirmed working as well thanks very much.

Sent from my iPad

On 25 Feb 2019, at 11:22 pm, pilievwm <notifications@github.com<mailto:notifications@github.com>> wrote:


I confirm it is working as before!
Thanks for your fast reaction!
