### ISSUE TITLE
Timer and  humidity sensor por thermostat card in Home Assistant 

### ISSUE THREAD

**Issue by mafede** [smartHomeHub/SmartIR#176]
How could a timer be added to the thermostat card of home assistant, to choose the time of shutdown of the air conditioning, selecting intervals of 15 minutes for example?

Can the humidity sensor be added to the thermostat card? I have an Aqara sensor for temperature, humidity and atmospheric pressure, and on the thermostat card, the temperature appears, but not the humidity. Can it be added?

I have home assistant 0.95.4

**Comment by smartHomeHub** [comment]
This place is only for issues. Please post your question in forums.
Btw there is a custom climate card that is able to show the humidity.
