### ISSUE TITLE
Cannot pull from HACS because home-assistant 0.96.0b1 is required

### ISSUE THREAD

**Issue by jlo88** [smartHomeHub/SmartIR#178]
Home assistant version: 0.95.4
SmartIR version: none

**Describe the bug**

I cannot pull smartIR with HACS because it requireds home-assistant 0.96.0b1 (a pre-release version). This pre-release is not automatically pulled by hassio and therefore I cannot use this component.

**Debug log**

```
Unsupported Home Assistant version
You have version '0.95.4' of Home Assistant, but version '1.6.1' of 'SmartIR' require version '0.96.0b1' of Home Assistant, install and upgrades are disabled for this integration untill you upgrade Home Assistant.
```

**Comment by smartHomeHub** [comment]
Try to pull a compatible version then
https://github.com/smartHomeHub/SmartIR/releases

**Comment by jokerigno** [comment]
The issue persist with 0.96:

> You have version '0.96.0' of Home Assistant, but version '1.6.2' of 'SmartIR' require version '0.96.0b1' of Home Assistant, installation and upgrades are disabled for this integration untill you upgrade Home Assistant.
