### ISSUE TITLE
upgrades delete the personalize media_player code

### ISSUE THREAD

**Issue by vMeph** [smartHomeHub/SmartIR#181]
**Home Assistant version**
0.96.0b4
**SmartIR version**
1.6.2

**Describe the bug**
Every time you do a upgrade of smarIR  it will delete the content os smartir/codes/media_player
 codes, in my case i have 2 files `1000.json` and a personalize one `12345.json`
it will delete de `12345.json` when you upgrade smartIR

This always been like that is there anyway to work arround or the system wont alow you to have your own names json files?

**Comment by smartHomeHub** [comment]
How do you update SmartIR?
Also, how is it possible to run 1.6.2 in HA 0.95?

**Comment by vMeph** [comment]
@smartHomeHub  i just edit guess you didnt get on time sorry, using 0.96.0b4 beta
i update via HACS
but for the last versions i been seeing this happen, so when the smartIR wasnt working i came to find out that every time you do a upgrade it will delete you code files personalize

**Comment by smartHomeHub** [comment]
I just checked it out. It only happens with HACS. The built-in updater of SmartIR does not delete the custom code files. It seems that HACS clean up the folder first and then download the python files from the repo.

**Comment by vMeph** [comment]
ahh @ludeeus any way to fix this?

**Comment by smartHomeHub** [comment]
From SmartIR side, a solution is to move the code files outside the integration folder. But this is a massive breaking change.

**Comment by ludeeus** [comment]
<https://custom-components.github.io/hacs/faq/#how-does-it-work-installation>
It does indeed do a cleanup before any install/upgrade.

**Comment by smartHomeHub** [comment]
I'll add a warning to an info.md file for those who are going to add the integration as a custom repository to HACS.
