### ISSUE TITLE
with HA version 0.96, cant get yet HACS option for SmartIR?

### ISSUE THREAD

**Issue by vMeph** [smartHomeHub/SmartIR#182]
**Home Assistant version**
0.96

**Describe the bug**

Unsupported Home Assistant version
You have version '0.96.0' of Home Assistant, but version '1.6.2' of 'SmartIR' require version '0.96.0b1' of Home Assistant, installation and upgrades are disabled for this integration untill you upgrade Home Assistant.

**Additional context**

wasnt 0.96 required to be able to install HACS?
i got 0.96 and im getting the following error above

**Comment by smartHomeHub** [comment]
https://community.home-assistant.io/t/smartir-control-your-climate-tv-and-fan-devices-via-ir-rf-controllers/100798/470?u=vassilis
