### ISSUE TITLE
Missing on-off switch after 1.6.x and 0.96.x

### ISSUE THREAD

**Issue by cubilon** [smartHomeHub/SmartIR#183]
As told in the subject: switch for on-off is missing on the frontend.

**Comment by smartHomeHub** [comment]
Hi. I miss it too ;)

**Comment by cubilon** [comment]
LOL.
did they took it away?

**Comment by smartHomeHub** [comment]
I supposed yes. I'm looking closely on this.

**Comment by cubilon** [comment]
what a pity. ok, let's see what happen
