### ISSUE TITLE
Adding new codes

### ISSUE THREAD

**Issue by nicxvan** [smartHomeHub/SmartIR#184]
I'm looking for the best way to contribute codes for a new model. Neither of the hiseer options worked. I mapped them out and have tested them on one of my minisplits, I'll test the other next week, please let me know the best way to add them.

Also I'm interested in adding other features. E.g. these models have the ability to shut off the led and sound, but I didn't see how to grab that code, same for timed sleep and timed start.

**Comment by brent0np** [comment]
I submitted my codes via an [issue on github](https://github.com/smartHomeHub/SmartIR/issues/48).

I am sorry I am not sure the LED/sound is something that will be easily supported
