### ISSUE TITLE
JSON file for GZ-1002B-E3 remote (climate)

### ISSUE THREAD

**Issue by ov1d1u** [smartHomeHub/SmartIR#185]
My AC's brand is Simbio, but according to the table at https://telecomanda-tv.ro/telecomanda-compatibipala-pentru-aer-conditionat-gz-1002/2440.htm there are many other AC units which use this remote control.
[4231.json.zip](https://github.com/smartHomeHub/SmartIR/files/3413328/4231.json.zip)

**Comment by smartHomeHub** [comment]
Thank you, sir!

**Comment by mansig88** [comment]
Hello, someone have this file to Xiaomi remote? por a remote GZ-1002A-E3
