### ISSUE TITLE
Support for Mitsubishi MSZ-AP50VGKD heatpump

### ISSUE THREAD

**Issue by insertjokehere** [smartHomeHub/SmartIR#187]
I have generated a code file for my Mitsubishi MSZ-AP50VGKD heatpump, please include this in the repository for others to use.

I suspect that it will work for other MSZ-AP series heatpumps, but have not tested

Thanks,
Will

[Mitsubishi_MSZ-AP50VGKD.json](https://github.com/smartHomeHub/SmartIR/files/3424252/Mitsubishi_MSZ-AP50VGKD.txt)

**Comment by smartHomeHub** [comment]
Thank you!
