### ISSUE TITLE
Auto Codes

### ISSUE THREAD

**Issue by barns102** [smartHomeHub/SmartIR#189]
**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**
Hi, for the Mitsubishi model (1120 code file), there are no Auto codes.  My heat pump does have an Auto function.  Is there anyway to get these added for heat and cool.  I have tried to learn the codes myself, but I'm having difficultly.  In the Home Assistant UI, Auto is not an option (I'm guessing this is because its not listed as an operation mode in the 1120 code file), but in HomeKit it is an option, but the button doesn't do anything (coz there's no corresponding code??).  My learn Broadlink service in HA is not working, not sure why??.  Could you please help.  

**Debug log**

```text

Thanks 
 
Add your logs here.

```

**Additional context**

**Comment by smartHomeHub** [comment]
You really need to fix the learn service or collect the codes through the broadlink manager
https://community.home-assistant.io/t/broadlink-manager-nicer-way-to-learn-and-send-ir-rf-commands/58770
