### ISSUE TITLE
How do I get the new codes to you 

### ISSUE THREAD

**Issue by barns102** [smartHomeHub/SmartIR#193]
**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

I have learnt the new codes for Auto Heat and Auto Cool, I have them saved to a word Document, but I'm unsure of the best way to add them to the file.  I'm also a bit confused about how they will work.  I have learnt codes for Cooling, Auto Fan and Auto fan oscillation (which to my heat pump means this is the temp I want, now set the fans to achieve that, and then coast once its reached the desired temp), but that doesn't match up with the current fan mode of Low, Mid, High and Highest.  Does this make sense and can you help?

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by barns102** [comment]
So now I have just learnt the codes for Auto (not heat or Cool, but just Auto), but when I click Auto in HomeKit, it doesn't work.  Clicking Heat and Cool, still work.  I tried to attached the file here, but the file type is not supported.  

What should I do?

**Comment by smartHomeHub** [comment]
Try to zip them.
In the last HA version, HomeKit cannot recognize the auto mode. Please consider renaming `auto `with `cool_heat` in your JSON files and tell me if it works

**Comment by barns102** [comment]
[1255 2.json.zip](https://github.com/smartHomeHub/SmartIR/files/3435437/1255.2.json.zip)

@smartHomeHub 

Can you see this?

**Comment by smartHomeHub** [comment]
Does your unit support fan speed at auto mode?

**Comment by barns102** [comment]
Yes, I believe so.

**Comment by barns102** [comment]
I have just change the config to cool_heat, and still not working.

Prior to changing it, it didn't work in Home Assistant either, but once I added the new Auto codes a new icon appear on my climate card in HA UI, but it didn't not do anything, same as HomeKit.

**Comment by barns102** [comment]
@smartHomeHub were you able to see the config from the zip file I sent?

**Comment by smartHomeHub** [comment]
Ok. So, you are trying to add the auto mode to 1120 right?
What is the speed of your fan when you learn the auto mode codes?

**Comment by barns102** [comment]
I copied the file 1120, renamed it 1255, and just added the extra codes.

Here are the codes I learnt, I have only added the bottom ones (Auto, neither heat or cool).
[Auto Cool 2.zip](https://github.com/smartHomeHub/SmartIR/files/3435514/Auto.Cool.2.zip)

**Comment by barns102** [comment]
So with my unit there are 2 Auto modes 
First Auto mode - You set the temp to what you want and if you want it to heat or cool, then you can put the fan on Auto, this will heat the room to the desired temp, and will put the fan to the best speed setting to achieve that temp.  Once that temp has been reached the fan slows down.

The Second Auto mode, you don't select heat or cool, its a seperate mode, and will either cool or heat the room depending on what temp you have set it on.  (this is the one that I want and is the last set of codes on the doc I sent you).

I have learnt all the codes - Heat Auto, Cool Auto and just Auto.

When I was learning the codes, the fan speed was set to Auto?

Hope this makes sense!!!

**Comment by smartHomeHub** [comment]
[1255.zip](https://github.com/smartHomeHub/SmartIR/files/3435557/1255.zip)

**Comment by barns102** [comment]
@smartHomeHub 

Sorry reading that back doesn't make any sense.  There is actually on one type of Auto mode, which is both heat and cool ( it will heat or cool the room depending on the set temp).

The other is just the fan on Auto, so you can set it to heat with an Auto fan speed.  

But as homekit does not allow for fan speeds, its the Auto Mode that I'm trying to create.  

OMG, this is so friggin confussing!!!!

**Comment by barns102** [comment]
@smartHomeHub 

Ok so I added the new 1255 you sent, and I have a new icon on in the HA UI and a new mode called Heat/Cool.  But it still doesn't do anything.  Heat and Cool still work.  The same applies in HomeKit

**Comment by smartHomeHub** [comment]
Be sure that the fan is also to auto on the UI

**Comment by barns102** [comment]
@smartHomeHub 

That has worked!!!

Where did you get your superpowers???!!!

Thanks heaps, yet again..

**Comment by smartHomeHub** [comment]
:) You need to learn the rest of commands in order to component work properly.
Did also HomeKit worked?

**Comment by barns102** [comment]
Yeah, HomeKit works to, as long as Auto fan is set in HA UI, it works.  It still sucks that you can't change the fan setting in HomeKit, but the Auto mode is the most economical, so I'm happy to just keep it on that.

What other commands do I need to learn?

**Comment by smartHomeHub** [comment]
The low, mid, high and highest fan speeds of auto mode.
![image](https://user-images.githubusercontent.com/47714957/61950518-bfe6e680-afb6-11e9-9320-a9002693d251.png)

**Comment by barns102** [comment]
but too be honest, will I really need to use those, because when the mode is set to Auto, and the fan speed in HA UI is set to auto, the fan will adjust accordingly, so there is no need to have low, mid, high or highest.  Am I right?

**Comment by smartHomeHub** [comment]
Yes

**Comment by barns102** [comment]
Thanks mate.  If you're ever in New Zealand, I know a perfect climate controlled place where you can stay and have a few beers!!!

Kia ora and Kia Kaha.
Barns

**Comment by smartHomeHub** [comment]
Your welcome!
Have a nice day.
