### ISSUE TITLE
Add support for Sintech AC

### ISSUE THREAD

**Issue by adrianmihalko** [smartHomeHub/SmartIR#2]
Hi,

I scanned all codes for Sintech AC, I tried to convert with provided tool, but something is broken here:

<img width="408" alt="screenshot 2019-02-19 at 22 21 44" src="https://user-images.githubusercontent.com/733361/53048324-c23b9680-3494-11e9-9265-f4f5342c8979.png">

I attach my .ini file. Can you please convert and add to the project?

All modes were recorded (heat, cool, fan, low-mid-high-auto from 16C to 31C)
[sintech.ini.txt](https://github.com/smartHomeHub/SmartIR/files/2882053/sintech.ini.txt)

**Comment by smartHomeHub** [comment]
The problem is at cool->auto_31. The command is in a new line. Is Sintech AC the brand name of your unit? I don't find any information online.

**Comment by adrianmihalko** [comment]
Oh, thanks for the find. 

Yes, it is the brand of the AC. It is pretty popular in our country. If am not wrong it is a china oem A/C, rebranded:

https://sinop.cz/media/cache/file/bd/NASTENA_plochy_typ.pdf
https://sinop.cz/media/cache/file/15/KAZETA_navod_na_obsluhu.pdf

**Comment by smartHomeHub** [comment]
Thanks for the additional information. Do you know the model of your unit?

**Comment by adrianmihalko** [comment]
Of course, it is Sintech KFR-34GW. I also found on other brand name: Shining.

**Comment by smartHomeHub** [comment]
Uploaded. The code is 1420. Thank you. I really appreciate your help.
