### ISSUE TITLE
Listen mode while idle to keep state in sync?

### ISSUE THREAD

**Issue by FezVrasta** [smartHomeHub/SmartIR#203]
_I'm not following the template because it's a feature request._

I was wondering if it could be possible to make the IR blaster (Broadlink RM Mini 3 in my case) stay on listen mode while idle.

This would allow this component to know when the original AC remote is used and reflect the changes made by the latter to the Home Assistant state.

**Comment by smartHomeHub** [comment]
This is not possible because the broadlink component stays in listen mode for 30 secs and also cannot be in listen and broadcast at the same time.

**Comment by cavoixanha** [comment]
I think you can use Broadlink RM Mini 3 (second)
- 1 for send
- 1 for receive
