### ISSUE TITLE
SmartIR Climate homekit broken

### ISSUE THREAD

**Issue by f4bio79** [smartHomeHub/SmartIR#212]
**Home Assistant version**
0.97.2
**SmartIR version**
1.7.2
**SmartIR configuration**

smartir:
climate:
  - platform: smartir
    name: sala3
    unique_id: sala3
    device_code: 1101
    controller_data: 192.168.178.218
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

switch:
  - platform: broadlink
    friendly_name: 'brmini3'
    host: 192.168.178.218
    mac: 'C8:F7:42:F5:F3:31'

**Describe the bug**

The issue is only related to Homekit. I can select the temperature, but the button  "AUTOMATIC" does not perform any action on the climate entity in home assistant.
Moreover when I ask to siri: "set 23 degress on room3" homekit by default use the "automatic" switch, so the climate never starts to work.
In homekit the climate button has available the temperature and 4 different modes: OFF, WARM, COLD and AUTOMATIC.
Using them manually they all works except "automatic"

**Debug log**

Sat Aug 24 2019 11:51:14 GMT+0200 
Error executing service <ServiceCall climate.set_hvac_mode (c:f9dd397f6cc74f31be0d8fb935042090): entity_id=['climate.sala3'], hvac_mode=heat_cool>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1243, in _safe_execute
    await self._execute_service(handler, service_call)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1260, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 210, in handle_service
    self._platforms.values(), func, call, service_name, required_features
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 334, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 356, in _handle_service_platform_call
    await getattr(entity, func)(**data)
  File "/config/custom_components/smartir/climate.py", line 299, in async_set_hvac_mode
    await self.send_command()
  File "/config/custom_components/smartir/climate.py", line 331, in send_command
    command = self._commands[operation_mode][fan_mode][target_temperature]
KeyError: 'heat_cool'

```

**Additional context**

The last version that was working properly (from HomeKit) was 0.95.4 with smartir 1.5.0
I was able to discover that this issue seems to be present since the version 0.96.0 with smartir 1.6.1

Thanks in advance for any help

**Comment by smartHomeHub** [comment]
Are you using your own json file or one of this repo?

**Comment by f4bio79** [comment]
> Are you using your own json file or one of this repo?

helllo Vassilis, thanks for your reply
I'm not using my own json (actually i don't even know how I could) 
I've even tried to install hassio from scratch, just adding 
   1. platform: broadlink
   2. platform: smartir (syntax in YAML and smartir files "1.7.2" in "custom_components")
   3. homekit as a new bridge

The results is the same: OFF, WARM and COLD work if used by hand in homekit
Siri always fails to turn on the climate because as far as I've understood it uses the "automatic" function.
Anyway using the "automatic" button from HASSIO works properly, and the climate can be successfully turned on

**Comment by smartHomeHub** [comment]
Ok. Could you replace the json file under /codes/climate, restart and send me your results?
[1101.zip](https://github.com/smartHomeHub/SmartIR/files/3537091/1101.zip)

**Comment by f4bio79** [comment]
I've substituted the 1101.json that you sent me.
Ive restarted HASSIO and now it's working properly even from homekit and SIRI!

I've noticed that the JSON you just sent me is different from the same file conteined in the 1.7.2 "codes" folder. (lines 20 and 38, right?)

Thanks a lot for your support!
you were awesome

**Comment by smartHomeHub** [comment]
Yes. It seems that homekit now use heat_cool instead of auto.
