### ISSUE TITLE
Midea AC 1380 doesn't do anything when selecting Auto mode in the Homekit (worked previosly)

### ISSUE THREAD

**Issue by Nebr88** [smartHomeHub/SmartIR#214]
**Home Assistant version**
0.97.2

**SmartIR version**
1.7.2

**SmartIR configuration**
climate:
  - platform: smartir
    name: AC Зал
    unique_id: hall_ac
    device_code: 1380
    controller_data: 192.168.0.100
    temperature_sensor: sensor.temperature_158d0001f52e24
    humidity_sensor: sensor.humidity_158d0001f52e24
  - platform: smartir
    name: AC Спальня
    unique_id: bedroom_ac
    device_code: 1380
    controller_data: 192.168.0.110
    temperature_sensor: sensor.temperature_158d0001f50686
    humidity_sensor: sensor.humidity_158d0001f50686

**Describe the bug**
Midea AC 1380 doesn't do anything when selecting Auto mode in the Homekit (worked previosly). For e.g. if I say Siri tun on AC in the hall it does nothing, the same in the homekit app, but if I select heat or cool, all works fine. Something wrong with AUTO settings

**Comment by smartHomeHub** [comment]
Please delete the JSON file from codes/climate folder and restart your HA instance. Let me know if it works

**Comment by Nebr88** [comment]
Thanks for the reply. Unfortunately it didn’t help. Climate folder is empty and I restarted HA few times

**Comment by smartHomeHub** [comment]
Do you have the `smartir:` in your configuration? eg:

```
smartir:

climate:
  platform: smartir
```

**Comment by smartHomeHub** [comment]
Does the 1380.json appear again after HA restart?

**Comment by Nebr88** [comment]
Sure. As I told before, only Auto mode doesn’t work. Cool, heat and temperature set work correctly

**Comment by Nebr88** [comment]
Yes, it was appeared with mod date 26 Jun 2019

**Comment by Nebr88** [comment]
![78D8BCA3-D636-42C0-B1A0-02891A97DCB2](https://user-images.githubusercontent.com/33136303/63643845-e6e22680-c6e2-11e9-96cd-14383089a956.png)

**Comment by smartHomeHub** [comment]
Show me the operationModes section of the JSON file

**Comment by Nebr88** [comment]
![680AEA9C-068B-4BA6-8E03-CC1EDD94B371](https://user-images.githubusercontent.com/33136303/63643875-ba7ada00-c6e3-11e9-8562-a574d873287d.png)

**Comment by smartHomeHub** [comment]
This is not the updated file. Are you able to replace the contents of the file with the data of the following link?
https://raw.githubusercontent.com/smartHomeHub/SmartIR/master/codes/climate/1380.json
You need also to restart HA.

**Comment by Nebr88** [comment]
Man, thank you, that really helped. It is strange that after an update and even delete pf that json it wasn’t updated

**Comment by smartHomeHub** [comment]
I'm glad it works. Please close this issue if you don't need further help.
Thanks
