### ISSUE TITLE
[RFE] Support for Hitachi RAS-32CNH2

### ISSUE THREAD

**Issue by soukron** [smartHomeHub/SmartIR#216]
Attached file for Hitachi RAS-32CNH2 Air Conditioner based on official remote.

It includes:
 - cool, heat and dry modes
 - auto, low, medium and high fan modes
 - all temperatures for all modes for all fan modes from 16 to 32

Note: Dry mode only works with low fan speed (it forces low speed) in my remote so I used the same codes for all fan speeds.
[your-ir-code.json.txt](https://github.com/smartHomeHub/SmartIR/files/3538979/your-ir-code.json.txt)

**Comment by smartHomeHub** [comment]
Thanks
