### ISSUE TITLE
Support for Hitachi RAS-35YHA (RAC-35YHA), RAS-25YHA (RAC-25YHA)

### ISSUE THREAD

**Issue by austwhite** [smartHomeHub/SmartIR#218]
Support for Hitachi RAS-35YHA, RAS-25YHA (and possibly others in same series).
These Hitachi models have 4 fan speeds plus Auto.
These Hitachi models are reverse cycle, inverters with Heat, Cool, Dry, Fan Only and a "Auto Comfort Mode"
Operational Temp for Heat and Cool is 16 degrees to 32 degrees Celsius.

Note: Although the other Hitachi files do also work with these models, they do not contain all the features (extra fan speeds and extra modes).

This code file allows operation of the following:
Operational Modes:
* Heat 
* Cool
* Dry
* Fan Only

Fan Modes:
* High
* Med
* Low
* Quiet
* Auto

Caveats: 
*  Auto mode is not included as this is a "Comfort Feel" setting with no temperature setting
* Dry Mode only has two fan speeds, Quiet and Low, on the original remote.  I have copied the 
  "Quiet" setting to Quiet and Low speeds, with "Low" setting on Med, High and Auto so as to   
  allow operation in any mode
* Fan Only: This does not support Auto Fan in Fan Only and no codes are in the "Auto" section 
  for Fan Only mode.

Edit: Codes were captured from Original remote control and tested in real life use.

[HitRAS35.json.txt](https://github.com/smartHomeHub/SmartIR/files/3539583/HitRAS35.json.txt)

**Comment by smartHomeHub** [comment]
Amazing job. Thanks
