### ISSUE TITLE
SmartIR using HACS will delete all your media codes

### ISSUE THREAD

**Issue by vMeph** [smartHomeHub/SmartIR#220]
**SmartIR version**
1.7.3

this has been report before that everytime you Update SmartIR using HACS will delete all your media codes, was wondering if there is any plan to fix this?

**Comment by smartHomeHub** [comment]
It is already fixed by last HACS version.
https://hacs.netlify.com/developer/general/#hacsjson

**Comment by smartHomeHub** [comment]
Do you need further help?
