### ISSUE TITLE
Climate not working

### ISSUE THREAD

**Issue by kbashiri** [smartHomeHub/SmartIR#221]
After updating HA to 0.98 smartir climate entities don't show up anymore.

**Home Assistant version**
0.98
**SmartIR version**
Latest as of 30th August

**SmartIR configuration**

```yaml
- platform: broadlink
  host: 192.168.1.31
  mac: 78:0F:77:B9:12:B9
  friendly_name: RM2 Pro Plus3

- platform: broadlink
  host: 192.168.1.32
  mac: 78:0f:77:50:f9:91
  friendly_name: RM Mini Audrina

smartir:

climate:
  - platform: smartir
    name: Audrina's AC
    unique_id: ab_ac
    device_code: 391
    controller_data: 192.168.1.32
    temperature_sensor: 
 sensor.audrina_temperature
    humidity_sensor: sensor.audrina_humidity

  - platform: smartir
    name: Downstairs AC
    unique_id: ds_ac
    device_code: 391
    controller_data: 192.168.1.31
    temperature_sensor: sensor.living_temperature
    humidity_sensor: sensor.living_humidity
    
Smartir media player works ok.

**Comment by smartHomeHub** [comment]
Hi,
I need logs. Please restart your HA instance and send me your full logs.
Thank you

**Comment by jgb90** [comment]
Hi. I have "xiaomi universal ir" (with MI logo on the top) And it works perfectly. Recently I acquired "xiaomi universal ir v2" (with mijia logo on the top. Model: MJYKQ01CM) Home Assistant recognizes it perfectly and responds to the learn command and send command services correctly, but I don't get the climate component to work. Maybe this model is not compatible? Please help me!
Thank you

**Comment by smartHomeHub** [comment]
Any errors in the log?

**Comment by kbashiri** [comment]
> Hi,
> I need logs. Please restart your HA instance and send me your full logs.
> Thank you

The problem solved after renaming the climate entities and restarting HA for a couple of times. Not sure why but renaming the entities did the job ...
