### ISSUE TITLE
Feature Request: Disable update notification 

### ISSUE THREAD

**Issue by tyjtyj** [smartHomeHub/SmartIR#222]
**Home Assistant version**
0.98.1
**SmartIR version**
1.7.3
**SmartIR configuration**

```yaml
smartir:
```

**Describe the bug**

Feature Request.
Allow configuration to disable notification. Some user may no updated to latest Home Assistant and SmartIR will remain old version. This cause notification each time home assistant restart.

Suggest add allow disable check update and call only when necessary. 
Alternatively, notification in log as Info: New SmartIR version available 

smartir:
  check_update: false

**Comment by smartHomeHub** [comment]
Aah, it is not documented. Please do configuration as follows:
```yaml
smartir:
  check_updates: false
```
