### ISSUE TITLE
Problems with Xiaomi Universal IR updated version

### ISSUE THREAD

**Issue by jgb90** [smartHomeHub/SmartIR#224]
Please open a new issue. Any errors in the log?

_Originally posted by @smartHomeHub in https://github.com/smartHomeHub/SmartIR/issues/221#issuecomment-527238578_

The home assistant log does not register any problems. Thanks for answering

**Comment by smartHomeHub** [comment]
Firstly,
Does the xiaomi universal ir v2 has a led that blinks when it sends a command?

**Comment by jgb90** [comment]
If you have it. But it doesn't blink

**Comment by smartHomeHub** [comment]
Are you able to send commands through REMOTE.SEND_COMMAND service?

**Comment by jgb90** [comment]
yes. And capture them too

**Comment by smartHomeHub** [comment]
Try copying a random command from the JSON file and sending it through the service. I'm thinking of the possibility that the commands are different from v1 to v2.

**Comment by jgb90** [comment]
I have tried to send a previously captured command and it works. The command tested is this: "nMwmcwlk0msxmEsmoBBTWcAD7MZvMAGPAH8DDwMGA58BnwCPAI8D3wEPAQ8AfwKPAQ8BDwCPAIWYQAA"

But if I try a command randomly from the 3380.json file it doesn't work. The code is this: "Z6XHACECAABpBgAAEREAADoRAAB+FAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzEAAQEAAAEAAAEAAAEBAAEBAAEBAQEBAQABAAAAAAAAAAAAAAEBAAABAQEBAAABAQQCMQABAQAAAQAAAQAAAQEAAQEAAQEBAQEBAAEAAAAAAAAAAAAAAQEAAAEBAQEAAAEBAA"

What could be the problem?

Thank you.

**Comment by smartHomeHub** [comment]
I think the problem is obvious. v2 does not support the commands of the v1 controller
