### ISSUE TITLE
Cannot control smartir using Alexa

### ISSUE THREAD

**Issue by km2000us** [smartHomeHub/SmartIR#227]
Please help me with turning this component on using Alexa:

I have set up an entity called climate.living_room_ac using the smartir component.

The entity works correctly and I can control it using the Home Assistant front end - turning it on, off, changing temperature etc.

I have exposed the entity climate.living_room_ac to Alexa using the emulated hue component.
I CAN change the temperature of the entity climate.living_room_ac using Alexa commands (either via the alexa app on my mobile or voice). The temperature indicator on the front end changes to the new value but the state remains “off”.
I CANNOT turn the entity on using Alexa.

I have used both the broadlink platform (using base64 codes) and the xiaomi platform (using raw codes).

**Comment by smartHomeHub** [comment]
I don't think it will work with that emulated hue component. Please try the cloud component.

**Comment by km2000us** [comment]
Thanks.
 I managed to connect using Node Red instead.
