### ISSUE TITLE
media player unavable

### ISSUE THREAD

**Issue by jokerigno** [smartHomeHub/SmartIR#236]
**Home Assistant version**
0.99.3
**SmartIR version**
1.7.3
**SmartIR configuration**
```

binary_sensor:
  - platform: threshold
    name: "Status TV Studio"
    entity_id:  sensor.rgbplug2_energy_power
    upper: 26
    
  - platform: threshold
    name: "Status Stereo Studio"
    entity_id:  sensor.presa_tpl1_watts
    upper: 26
    
sensor:
  - platform: template
    sensors:
     presa_tpl1_watts:
        friendly_name_template: "{{ states.switch.presa_tpl1.name}} Current Consumption"
        value_template: '{{ states.switch.presa_tpl1.attributes["current_power_w"] | float }}'
        unit_of_measurement: 'W'
          
media_player:
  - platform: smartir
    name: Stereo Studio
    device_code: 1099
    controller_data: 192.168.2.206
    power_sensor: binary_sensor.status_stereo_studio

  - platform: smartir
    name: TV Studio
    device_code: 1010
    controller_data: 192.168.2.206
    power_sensor: binary_sensor.status_tv_studio



**Describe the bug**

The component is installed (i tried also reinstalling it without changes), the media player are defined ( those was working until 1 month ago) but the media player are not create. No trace. No error in log.

**Comment by smartHomeHub** [comment]
I'm afraid I can't help you without errors in logs. Please try to restart HA and examine line by line if something related to SmartIR

**Comment by joesan1** [comment]
Same problem, with HA 0.98.3
In the folder .homeassistant/custom_components/smartir/__pycache__    the file media_player.cpython-37.pyc does not exist
There is no error in HA anywhere

**Comment by jokerigno** [comment]
for me the error was that the .json file for device was missing (lost after upgrade !).

**Comment by joesan1** [comment]
Thats's not my error, because I've got all de json files in the folders, media_player, fan and climate.
Thanks jokerigno.

> 
> 
> for me the error was that the .json file for device was missing (lost after upgrade !).

Thats's not my error, because I've got all de json files in the folders, media_player, fan and climate.
Thanks jokerigno.
