### ISSUE TITLE
Support for SRK50ZS-s

### ISSUE THREAD

**Issue by bjptwist** [smartHomeHub/SmartIR#243]
Sorry for using a bug report for this.
I've just integrated a Mitsubishi Heavy SRK50ZS-S in _SmartIR climate_ and I'd like to share the map containing the IR codes with you. What is the right approach to share this contribution?

Thanks in advance.

**Comment by smartHomeHub** [comment]
Thank you for your willingness to contribute. Please post your codes here in a zip file.

**Comment by bjptwist** [comment]
[1700.json.zip](https://github.com/smartHomeHub/SmartIR/files/3761912/1700.json.zip)
I've assigned a random code number (1700).
