### ISSUE TITLE
own code not working 

### ISSUE THREAD

**Issue by sonybansi** [smartHomeHub/SmartIR#253]
I make a own code for climate, file is valid in https://jsonformatter.org when i download file after validation then file save as jsonformatter.txt . I renamed the file 2061.json and put file in directory custom_components/smartir/codes/climate, but error in HA `The device Json file is invalid`

**Comment by smartHomeHub** [comment]
Could you send me the file?

**Comment by sonybansi** [comment]
@smartHomeHub [https://jsonformatter.org/26ae73](url)

**Comment by smartHomeHub** [comment]
Your file works for me. Could you post your SmartIR configuration?

**Comment by sonybansi** [comment]
json file working fine now,  thanks
