### ISSUE TITLE
New Code for Hamilton Bay Fans

### ISSUE THREAD

**Issue by waxhell** [smartHomeHub/SmartIR#256]
I've created a new file for Hamilton Bay (Home Depot) Fan Remotes  (3 speeds + Off). There is also a light / dimmer switch on the fan remote as well that I have not included (I integrated that myself via just the normal broadlink switch).

[2000.zip](https://github.com/smartHomeHub/SmartIR/files/3906711/2000.zip)

**Comment by smartHomeHub** [comment]
Perfect. Thanks for your contribution!
