### ISSUE TITLE
Unable to update from temperature sensor

### ISSUE THREAD

**Issue by legolas0802** [smartHomeHub/SmartIR#257]
hello, I have had this problem for a couple of days before.
Unable to update from temperature sensor: could not convert string to float: 'unavailable'
7:24 custom_components/smartir/climate.py (ERROR)
-Unable to update from humidity sensor: could not convert string to float: 'unavailable'
7:24 custom_components/smartir/climate.py.
- Issues without debug logging will be closed.
- Issues without configuration will be closed
-->

**Home Assistant version last**

**SmartIR version last**

**climate:
  - platform: smartir
    name: Condizionatore Salotto
    device_code: 1002
    controller_data: "192.168.178.29"
    temperature_sensor: sensor.salotto_temperature
    humidity_sensor: sensor.salotto_humidity
    power_sensor: binary_sensor.power_sensor_condizionatore_salotto**

**Comment by smartHomeHub** [comment]
The state of your temperature sensor is 'unavailable' instead of a float number

**Comment by krasatos** [comment]
Sorry for coming back to this, but i have the same issue.
It is probably because my zigbee sensors take a little longer to load on startup so they show up as unavailable when smartir loads.
Is there a way i can avoid this error?
perhaps change the temp sensor to some template that will show zero until it loads?
```
  - platform: smartir
    name: UP LR AC Toshiba 
    unique_id: smartir_toshiba
    device_code: 1260
    controller_data: remote.broadlink_lr_up_remote
    temperature_sensor: sensor.up_lr_xiaomi_temperature_sensor ##<-- this takes more time to load
```

**Comment by quadhammer** [comment]
Same problem here
