### ISSUE TITLE
Support for Mitsubishi Electric Split type AC with Broadlink (json code included)

### ISSUE THREAD

**Issue by Tunttis** [smartHomeHub/SmartIR#259]
**Home Assistant version**
0.102.3
**SmartIR version**
1.73
**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**
No bug, added support for device

**Debug log**

```text

Add your logs here.

```

**Additional context**

I created 1124.json for Mitsubishi Electric Split type AC models:
- MSZ-SF25VE3
- MSZ-SF35VE3
- MSZ-SF42VE3
- MSZ-SF50VE

with full support for auto, cool, heat, dry, fan only (with their respective fan speeds auto, quiet, low, normal, high & very high.
Vane settings are not included.

json included in the attached zip.

[1124.zip](https://github.com/smartHomeHub/SmartIR/files/3936579/1124.zip)

**Comment by smartHomeHub** [comment]
Thanks for your contribution. I really appreciate it.

**Comment by dimafemabo** [comment]
I want to give back to the community and here is a bit of my experience.

Just want to confirm that the file also works perfekt with the following split device:
MSZ-AP20VG
built in 12/2019

Might want to add this to the list of devices.
Cheers
Dietger
