### ISSUE TITLE
Climate state

### ISSUE THREAD

**Issue by cubilon** [smartHomeHub/SmartIR#26]
Hi Vassilis,
I noticed that my climate gets the "on" state from the binary sensor, but not the "off". I mean: it remains "on" even when binary sensor turns "off".

**Comment by smartHomeHub** [comment]
Fixed. Please update

**Comment by cubilon** [comment]
Ok.

P.S. will you release the "fan" version of SmartIR too?

**Comment by smartHomeHub** [comment]
Yes, In 1-2 weeks

**Comment by cubilon** [comment]
(it was me on Linkedin. just needed to speak to you privately :) )

**Comment by smartHomeHub** [comment]
I’m not using the platform. Please send me the username of your HA account in order to send you my email address via PM

**Comment by cubilon** [comment]
faster: write me to crew@indomus.it ;)

**Comment by CarpeDiemRo** [comment]
Hello,
I use history stats to monitor how much does my AC stay on. I have the following issue:
a. When I define the state as 'cool' / I use AC only on cool mode, no value is returned
b. When I define the state value as 'off', I have the values of the "off" state displayed. 
Can you advise me, please, what is the correct state for case A?
This is the script
  - platform: history_stats
    name: Cooling Hours Today
    entity_id: climate.samsung_ac
    state: 'off'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    end: '{{ now() }}'
