### ISSUE TITLE
SmartIR shouldn't advertise SUPPORT_VOLUME_SET

### ISSUE THREAD

**Issue by clapbr** [smartHomeHub/SmartIR#261]
IR volume usually (always?) works only in steps so it doesn't make sense to use SUPPORT_VOLUME_SET on this component. SmartIR also obviously doesn't implement arbitrary volume set. https://github.com/smartHomeHub/SmartIR/blob/master/custom_components/smartir/media_player.py#L119
Stumbled upon this because I have a yamaha receiver exposed to Alexa and it would fail to turn volume up/down because SmartIR reports wrong device capabilities.

**Comment by zacnut** [comment]
It does support volume_set? I could use it with the [issue I posted ](https://github.com/smartHomeHub/SmartIR/issues/260)perhaps

**Comment by clapbr** [comment]
Fixed in e1bba39
