### ISSUE TITLE
Issue updating to 1.7.4

### ISSUE THREAD

**Issue by chemelli74** [smartHomeHub/SmartIR#263]
**Home Assistant version**
0.103.0

**SmartIR version**
1.7.3

**HACS version**
0.18.2

**Describe the bug**

Unable to update from 1.7.3 to 1.7.4 via HACS

**Debug log**

![image](https://user-images.githubusercontent.com/57354320/70902549-5b780280-1ffd-11ea-8d0d-21151163ba89.png)

**Comment by smartHomeHub** [comment]
I would appreciate if @ludeeus could tell us if the problem was on our side.

**Comment by Bastiencc** [comment]
+1

**Comment by chemelli74** [comment]
> I would appreciate if @ludeeus could tell us if the problem was on our side.

I updated other extensions, for example "ShellyForHASS", without any problem if can help to narrow it down.

Simone

**Comment by nicx** [comment]
+1

**Comment by chrisdaloa** [comment]
Same Issue on Hassio 0.102.3

**Comment by robertopiumatti** [comment]
+1

**Comment by chemelli74** [comment]
repository.py, line 352: `tempfile.TemporaryFile()`

I think you should use `tempfile.TemporaryFile().Name` or `tempfile.NamedTemporaryFile()`

Simone

**Comment by ringhio80** [comment]
same here using Home Assistant 0.103.0, Hacs 0.19.0 and  Hassio 192

![immagine](https://user-images.githubusercontent.com/53511163/71109644-eb68a880-21c5-11ea-9bfd-7f4cd82010f1.png)

**Comment by mcasper73** [comment]
+1

**Comment by tatunts** [comment]
+1

**Comment by Akzid** [comment]
+1

**Comment by ludeeus** [comment]
@smartHomeHub Has been fixed in HACS <https://github.com/hacs/integration/pull/870>, next release is 1-5 days out.

**Comment by tatunts** [comment]
Problem solved! Working just fine. Thanks!

**Comment by chemelli74** [comment]
latest HACS fixed the issue, SmartIR update to 1.7.4 smoothly.
