### ISSUE TITLE
Add missing models to Daikin code 1101

### ISSUE THREAD

**Issue by Filipe-Figueiredo** [smartHomeHub/SmartIR#267]
**Home Assistant version**
0.103.0

**SmartIR version**
1.7.4

**SmartIR configuration**

```yaml

default

```

**Describe the bug**

There is no bug. Just to inform that **Daikin code 1101** also works with these two models:

**-FTXM35M**
**-FVXM35F**

**Comment by smartHomeHub** [comment]
Τhanks for pointing that out.
