### ISSUE TITLE
Add support for swing_modes

### ISSUE THREAD

**Issue by fontanellif** [smartHomeHub/SmartIR#27]
Hello,
i notice that with the old version of this component (https://github.com/Thunderbird2086/homeassistant-custom-components) i can set the swing_modes, but with your component i can't.

There is a way to set the swing_modes?

**Comment by smartHomeHub** [comment]
This was a custom fork of Thunderbird2086. I never merged it in the master branch. I'm not planning to add swing mode due to the command file complexity. Thank you.

**Comment by fontanellif** [comment]
Ok.

**Comment by nedgeworth** [comment]
Still not planning to add a swing mode? As I'd love to see this.
