### ISSUE TITLE
it is not working for Hassio!

### ISSUE THREAD

**Issue by gotodragon** [smartHomeHub/SmartIR#28]
I don't know the reason? it's not working on Hassio following your introduction!
19-02-25 15:08:38 ERROR (MainThread) [hassio.homeassistant] Invalid Home Assistant config found!
switch:           
  - platform: broadlink
    host: 10.0.0.12
    mac: '00:00:00:9C:C9:9E'
    timeout: 15
    switches:
      receiver:
        friendly_name: "any"
        command_on: '' 
        command_off: ''

climate:
  - platform: smartir
    name: Office AC
    device_code: 1180
    controller_send_service: switch.broadlink_send_packet_10_0_0_12
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power

**Comment by smartHomeHub** [comment]
According to the error, your config is invalid. Could you post it to a proper format?

**Comment by gotodragon** [comment]
I delete it from configration.yaml ,the config check is ok. i check the log like this:Unable to find component climate.smartir, but I made the right dir custom_components inside smartir include your three .py  files and codes download from you.


* platform: smartir
  name: Office AC
  device_code: 1180
  controller_send_service: switch.broadlink_send_packet_10_0_0_12
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.ac_power

**Comment by gotodragon** [comment]
I mean if add - platform: smartir  ......  under - platform: broadlink ........ inside configuration.yaml with your introduction way, then check the config, this say that the configration is invalid , can not find Climate.smartir.

**Comment by gotodragon** [comment]
I update hass to 0.88.1 for testing is ok, the previous ver 0.84.3 is not working, thanks your efforts!
