### ISSUE TITLE
Daikin CTXS15K2V1B

### ISSUE THREAD

**Issue by giussani** [smartHomeHub/SmartIR#288]
Good evening,
I created this file for my air conditioner, it works well.
The file-name is invented (I didn't know how to define it).
regards and thanks for the good job!

[9151.zip](https://github.com/smartHomeHub/SmartIR/files/4201794/9151.zip)

**Comment by smartHomeHub** [comment]
Generally, we don't accept partial device configuration files. Please fill or remove the empty sections
