### ISSUE TITLE
Set temperature is only displayed in Celsius

### ISSUE THREAD

**Issue by gotopside** [smartHomeHub/SmartIR#29]
I need the set temperature in Fahrenheit for my setup.

**Comment by smartHomeHub** [comment]
Ok. What is the code (Json file) of your device?

**Comment by gotopside** [comment]
I'm not sure how to answer that.  I had an existing Broadlink IR device set up and I just added the SmartIR and specified the existing 'switch' that I had already defined. Here is the YAML for the switch.

#####  IR controller on Garage AC
- platform: broadlink
  host: 192.168.0.42
  mac: '78:0F:77:5A:B9:52'
  timeout: 15
  switches:
    garage_ac:
      friendly_name: "Garage AC"
      command_on: 'JgBgAAABKpIUNhQQFRAVEBQRFBEUERQ1FRAVNRQ2FBEUEBU1FDYUERQ1FRAUERQRFBEUERQRFDUUERQ2FDYUNRQ2FDYUNRUQFAAFcAABKkkTAAxZAAEqSBQADFgAAS$
      command_off: 'JgBoAAABKpIUNhQRFBEUERQQFBEUERQ2FBEUNRQ2FBEUERQ1FTUUERQ2FBEUEBUQFBEUERQRFDYUEBU1FDYUNhQ1FDYUNhQRFAAFbwABKkkTAAxZAAEqSRMADFkAA$

**Comment by smartHomeHub** [comment]
I need the number of device_code value (SmartIR config).

**Comment by gotopside** [comment]
I used 1060, as I have an LG window unit, but I was not sure if that is the correct code.

**Comment by smartHomeHub** [comment]
Oh, wait. Did your device respond when you set the mode, temperature etc?

**Comment by gotopside** [comment]
Honestly, I am not certain.  I played with it a bit this morning, but once I saw the temperature was in Celsius I did not think I could get it to turn on with the Fahrenheit temperature sensor.

The unit is in a separate building from where I am at, but I can go try it real quick.

**Comment by gotopside** [comment]
If I click the snowflake, it turns the unit on.  I have a sensor in the outgoing airflow from the unit and it dropped and when I go outside, it is running.  It is set to 26 degrees and the temperature is at 81.9 which is well below that.

**Comment by smartHomeHub** [comment]
This is good. Could you send me the temperature range of your remote control?

**Comment by gotopside** [comment]
The remote just has up and down buttons on it.  The A/C unit goes from 60 to 86 degrees range.

**Comment by gotopside** [comment]
This is the unit: https://www.lg.com/us/support-product/lg-LWHD1500ER

**Comment by gotopside** [comment]
This is the remote I have with it.  
![image](https://user-images.githubusercontent.com/24878482/53383293-1dfa9980-3945-11e9-8d40-84543df28258.png)

**Comment by smartHomeHub** [comment]
Those remotes are incompatible with this component. Does your unit have a display that shows the temperature, mode etc?

**Comment by gotopside** [comment]
It does.  I have been trying to use a node-red thermostat to control it just by turning it on and off, with the retained setpoint of 60.  I don't really need to be able to adjust it up or down, just to turn it on or off.  The node-red thing had a mind of it's own and would turn on at random times and I would wake up to my garage being freezing because the unit was on all night.

**Comment by gotopside** [comment]
Is there a way to do that with your code?  The main appeal of it to me was that it could use a temperature sensor that was external to the air conditioner, which is exactly what I have been trying to do.

**Comment by smartHomeHub** [comment]
Please adjust the mode and the temperature from the component until the display of the unit shows 60 F (20 C?). Then use the services climate_turn_on and climate_turn_off from your automations. I can’t help you further.

**Comment by gotopside** [comment]
60F is around 15C, I just googled it.  So if I set it to 15, does the interface call climate_turn_on and climate_turn_off, or will I have to provide that myself through my own automations?

**Comment by smartHomeHub** [comment]
The range of this file is 18 to 30 C. 
Yes, you need to provide that through automations. This is not a thermostat component. Maybe the generic thermostat component fit your needs.
https://www.home-assistant.io/components/climate.generic_thermostat/

**Comment by gotopside** [comment]
Ok, thanks for your help.
