### ISSUE TITLE
Adding Codes for OpenMQTTGateway

### ISSUE THREAD

**Issue by eldadh** [smartHomeHub/SmartIR#290]
I am using OpenMQTTGateway for both IR,RF,BLE,PIR,DHT
it is using IR Codes over MQTT
I have created a jason file for it for my AC's
How can i add it to the repository?

**Comment by josep112** [comment]
Hello how did you do this working? could you give me your file?

**Comment by eldadh** [comment]
> 
> 
> Hello how did you do this working? could you give me your file?

i simply recorded the commands, i dont mind sending you ( where to? ) 
how ever they are for electra ( perhaps midea)  AC only.
