### ISSUE TITLE
Kolin Aircon (Generic)

### ISSUE THREAD

**Issue by johnjoemorgan** [smartHomeHub/SmartIR#291]
**Home Assistant version**
0.105.5
**SmartIR version**
9691aaa
**SmartIR configuration**
climate:
  - platform: smartir
    name: Master AC
    unique_id: master_ac
    device_code: 7661
    controller_data: 192.168.0.47
    temperature_sensor: sensor.temperature_158d00033b83cf
    humidity_sensor: sensor.humidity_158d00033b83cf
```yaml

Add configuration here

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**
Additional codes for Kolin brand aircon unit from the Philippines

[kolin.zip](https://github.com/smartHomeHub/SmartIR/files/4219312/kolin.zip)

Codes obtained with Broadlink RM Pro+

**Comment by smartHomeHub** [comment]
Generally, we don't accept partial device configuration files. Please fill or remove the empty sections
