### ISSUE TITLE
Sound mode selection for media_player (media_player.select_sound_mode)

### ISSUE THREAD

**Issue by maxill1** [smartHomeHub/SmartIR#292]
This is a feature request for "sound mode" support to media_player component.

https://www.home-assistant.io/integrations/media_player/#service-media_playerselect_sound_mode

It would be nice to add a separate array of modes to switch DSPs (surround, straight, etc):
```json

{
  "manufacturer":"",
  "supportedModels":[
    ""
  ],
  "supportedController":"Broadlink",
  "commandsEncoding":"Base64",
  "commands":{
 
    "sources":{
      "AV1":"",
      "AV2":""
    },
    "modes":{
      "DSP1":"",
      "DSP2":""
    }

  }
}

```

**Comment by kmplngj** [comment]
Any news?
