### ISSUE TITLE
climate.set_temperature service call not working?

### ISSUE THREAD

**Issue by chierichetto** [smartHomeHub/SmartIR#30]
Hi,
Just installed this component yesterday, but i'm not able to use climate.set_temperature in automations or service calls. It says "service called", but the target temperature is unchanged.
This is an example which does not work:

{
  "entity_id": "climate.varmepumpe",
  "temperature":21
}

This works great with the older broadlink climate component. Anyone else have this problem? I can control temp, operation mode and fan mode through the UI.

**Comment by smartHomeHub** [comment]
It works. Are any error in logs?

**Comment by chierichetto** [comment]
Got home now, and testet some. I got this error in the log:

```
2019-02-26 16:33:36 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/helpers/service.py", line 291, in _handle_service_platform_call
    await func(entity, data)
  File "/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/__init__.py", line 576, in async_service_temperature_set
    await entity.async_set_temperature(**kwargs)
  File "/config/custom_components/smartir/climate.py", line 299, in async_set_temperature
    await self.send_command()
  File "/config/custom_components/smartir/climate.py", line 343, in send_command
    command = self._commands[operation_mode][fan_mode][target_temperature]
KeyError: 'Heat'
```

But! I found out that Operation Mode was not set before, making it fail. If i set Operation Mode to Heat in front end, it works. I'll add the climate.set_operation_mode to the automation before the temperature_set to ensure it'll run, if operation_mode ever becomes unset again.
Thanks!

**Comment by smartHomeHub** [comment]
First of all, use heat instead of Heat.
The component ignores the operation_mode key in climate.set_temperature service.
You need to call climate.set_operation_mode service before or after the climate.set_temperature service

**Comment by chierichetto** [comment]
yeah, i just didn't choose an operation mode after installing the component, and did not set an operation mode when calling climate.set_temperature, just entity_id and temperature. But we are all good now:-)

**Comment by anglrus** [comment]
Hello, please, could you help with setup.
I use SmartIR - UFO-R1 and Hisense. Hisense integrated with SmartIR using Tuya. I'd like to use your module. I did following:
1. Configuration yaml:
smartir:
  update_branch: rc
climate: !include climates.yaml

2. Climates.yaml:
- platform: smartir
  name: Hisense Living Room
  unique_id: hisense_living
  device_code: 1522 # 1520, 1521, 1522
  controller_data: 192.168.1.81
  temperature_sensor: sensor.temperature
  humidity_sensor: sensor.humidity
  power_sensor: binary_sensor.ac_power

3. Switches.yaml
- platform: broadlink
  host: 192.168.1.81
  mac: 'XX'

And have got following errors:

ERROR:
Unable to find service broadlink/send
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 338, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
  File "/config/custom_components/smartir/controller.py", line 85, in send
    'broadlink', 'send', service_data)
  File "/usr/src/homeassistant/homeassistant/core.py", line 1212, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send

The second WARNING:
Platform broadlink not ready yet. Retrying in 60 seconds.

Thank you

**Comment by vassilis-panos** [comment]
Nothing to do with SmartIR.
You need to fix the broadlink switch until broadlink.send is available
