### ISSUE TITLE
Adding support for the Logitech Z906 (Broadlink)

### ISSUE THREAD

**Issue by D33M** [smartHomeHub/SmartIR#301]
Hi,

I have created the configuration for the Logitech Z906 using Broadlink RM Mini.

```json
{
  "manufacturer": "Logitech",
  "supportedModels": [
    "Z906"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "commands": {
    "off": "JgBYAAABJJAUERU0FRAVDxQRFBEVDxUQFBEUERQQFRAUERQ1FBEUNRQRFBAVEBQRFBEUEBUQFDUVNBU1FDUUNRQ1FDUUNRUQFAAF2wABKEgUAAxNAAEqRRYADQU=",
    "on": "JgBYAAABJJAUERU0FRAVDxQRFBEVDxUQFBEUERQQFRAUERQ1FBEUNRQRFBAVEBQRFBEUEBUQFDUVNBU1FDUUNRQ1FDUUNRUQFAAF2wABKEgUAAxNAAEqRRYADQU=",
    "nextChannel": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
    "volumeDown": "JgBQAAABJY8WDxYzFg8WDhYPFg8WDxYOFg8WDxYOFg8WDxYzFg8WMxYPFjMWDxYzFg8WMxYzFg8WMxYOFjQWDhYzFg8WDxYzFgAF2QABKkYWAA0FAAAAAAAAAAA=",
    "volumeUp": "JgBQAAABIpIUERM2ExITEhMSExETEhMSExEUERMSExITERQ1FBETNhQRFDYTERM2ExITNhMSEzYTNhMSEzYTEhM2ExITNhMRFAAF3AABKEcVAA0FAAAAAAAAAAA=",
    "mute": "JgBQAAABI5EUERQ1FBEUERMRFBEUERQRFBAUERMSFBEUEBQ1FBEUNRQREzYUERQ1FBETNhM2FDUUNRQRFDUUERQ1FBETEhMRFAAF3AABKEcTAA0FAAAAAAAAAAA=",
    "sources": {
      "Input 1": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxISEhISEhISEhISNxI3EhISNxI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
      "Input 2": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEgAF0wABKEoSAAxWDQUAAAAAAAA=",
      "Input 3": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxI3EhISEhISEhISNxI3EhISEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
      "Input 4": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxI3EhISEhISEjcSNxI3EhISEhI3EjcSNxISEgAF0wABKEoSAAxWDQUAAAAAAAA=",
      "Input 5": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
      "AUX" : "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhI3EhISNxISEjcSNxI3EjcSEhI3EgAF0wABKEoSAAxWDQUAAAAAAAA="
    }
  }
}
```
I also have more codes if there is possible integration:
```yaml
level: JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=
effect: JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSNxI3EhISEhISEhISNxISEhISEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=
```

**Comment by D33M** [comment]
Im not doing a pull request due to the fact that I do not really understand, how do you generate the device codes - from where the `xxxx.json` numbers are coming?

**Comment by smartHomeHub** [comment]
Thanks for your contribution!

**Comment by Musyanon** [comment]
> Hi,
> 
> I have created the configuration for the Logitech Z906 using Broadlink RM Mini.
> 
> ```json
> {
>   "manufacturer": "Logitech",
>   "supportedModels": [
>     "Z906"
>   ],
>   "supportedController": "Broadlink",
>   "commandsEncoding": "Base64",
>   "commands": {
>     "off": "JgBYAAABJJAUERU0FRAVDxQRFBEVDxUQFBEUERQQFRAUERQ1FBEUNRQRFBAVEBQRFBEUEBUQFDUVNBU1FDUUNRQ1FDUUNRUQFAAF2wABKEgUAAxNAAEqRRYADQU=",
>     "on": "JgBYAAABJJAUERU0FRAVDxQRFBEVDxUQFBEUERQQFRAUERQ1FBEUNRQRFBAVEBQRFBEUEBUQFDUVNBU1FDUUNRQ1FDUUNRUQFAAF2wABKEgUAAxNAAEqRRYADQU=",
>     "nextChannel": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISEhI3EhISEhISEhISNxI3EjcSEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
>     "volumeDown": "JgBQAAABJY8WDxYzFg8WDhYPFg8WDxYOFg8WDxYOFg8WDxYzFg8WMxYPFjMWDxYzFg8WMxYzFg8WMxYOFjQWDhYzFg8WDxYzFgAF2QABKkYWAA0FAAAAAAAAAAA=",
>     "volumeUp": "JgBQAAABIpIUERM2ExITEhMSExETEhMSExEUERMSExITERQ1FBETNhQRFDYTERM2ExITNhMSEzYTNhMSEzYTEhM2ExITNhMRFAAF3AABKEcVAA0FAAAAAAAAAAA=",
>     "mute": "JgBQAAABI5EUERQ1FBEUERMRFBEUERQRFBAUERMSFBEUEBQ1FBEUNRQREzYUERQ1FBETNhM2FDUUNRQRFDUUERQ1FBETEhMRFAAF3AABKEcTAA0FAAAAAAAAAAA=",
>     "sources": {
>       "Input 1": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxISEhISEhISEhISNxI3EhISNxI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
>       "Input 2": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhISEjcSNxISEjcSNxI3EjcSNxISEgAF0wABKEoSAAxWDQUAAAAAAAA=",
>       "Input 3": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxI3EhISEhISEhISNxI3EhISEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
>       "Input 4": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEhISNxI3EhISEhISEjcSNxI3EhISEhI3EjcSNxISEgAF0wABKEoSAAxWDQUAAAAAAAA=",
>       "Input 5": "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhISEhISNxISEjcSNxI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=",
>       "AUX" : "JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhISEhISEhI3EhISNxISEjcSNxI3EjcSEhI3EgAF0wABKEoSAAxWDQUAAAAAAAA="
>     }
>   }
> }
> ```
> 
> I also have more codes if there is possible integration:
> 
> ```yaml
> level: JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSEhI3EhISEhISEhISNxISEjcSEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=
> effect: JgVQAAABKJMSEhI3EhISEhISEhISEhISEhISEhISEhISEhI3EhISNxISEjcSNxI3EhISEhISEhISNxISEhISEhI3EjcSNxI3EgAF0wABKEoSAAxWDQUAAAAAAAA=
> ```

Hello,

Thanks for your work ! 

How did you have obtain the codes for input ? It's possible to get same for volume, example at 25%, 50%...

Many tanks !

**Comment by thedeemling** [comment]
Hello,
basically, the first step to obtain those codes is to search the web for "IR codes table" for the specific device. In this case I found the data:
![image](https://user-images.githubusercontent.com/82749218/152366418-df8781ed-3639-4f4b-8458-74f6602aa0e8.png)
![image](https://user-images.githubusercontent.com/82749218/152366445-a1ca993d-5de4-4b72-89a7-3b7695e0af91.png)

Having this information you still have to convert it to pronto hex codes, as this format is used by this integration/Hass/python module (I believe, but maybe there are other formats supported, too. I just did "monkey see, monkey do", everyone here uses pronto hex, so did I).

That being said, sadly - no, I could not find codes like these. Instead, I have modified this integration to "remember" what % the speaker currently is set on, so if I tell home assistant to increase the volume to 90%, it knows how many times it should send the command.  But... I have it only on my branch, haven't sent any PR here as I didn't know if this would be useful for others.

**Comment by thedeemling** [comment]
If @smartHomeHub is interested, I can make PR with this functionality though. It looks like this:
```yaml
- platform: irmp
  name: Speakers
  id: logitech_z906_speakers_ir
  volume_step: 0.0238095238 # This is new, from scale 0 to 1, how much does one-time increase changes the volume
  remote_entity: remote.rm3_mini_remote
  remote_device: Logitech Speakers
  power_on_template: "{{ is_state('switch.speakers_plug', 'on') and state_attr('switch.speakers_plug', 'current_consumption')|float > 5 }}"
  commands:
    power_on: power
    power_off: power
    volume_up: volume up
    volume_down: volume down
    mute: mute
  sources:
    PC: input 1
    Chromecast: input 2
```
