### ISSUE TITLE
power sensor problem

### ISSUE THREAD

**Issue by Dilkins85** [smartHomeHub/SmartIR#308]
tell me what the problem is, at the moment of activation of the power sensor, information about the operation mode of the air conditioner disappears, although the air conditioner continues to work as expected.
https://youtu.be/_e50ELtY73c

**Comment by ceaswaran** [comment]
Ya I too see when power sensor is OFF, I am able to control modes & Temperature which is not correct.
When Power sensor is OFF all the controls in the UI should be disabled. When Power Sensor ON all the controls in the UI should be enabled .

Please help to fix
