### ISSUE TITLE
Ability to track this component with custom_updater and tracker card

### ISSUE THREAD

**Issue by aheath70** [smartHomeHub/SmartIR#31]
Would be great if we could track updates to this with HA's custom_updater and tracker card - A custom_components.json file

**Comment by smartHomeHub** [comment]
Requested multiple times. Custom_updater does not meet the needs of SmartIR. A new version comes soon with the ability to self-update.

**Comment by smartHomeHub** [comment]
Please read this post:
https://community.home-assistant.io/t/smartir-climate-component/100798/80

**Comment by adrianmihalko** [comment]
@smartHomeHub I think it is now support:

https://github.com/custom-components/custom_updater/wiki/components

It was good, because I can track all my components on one page. If it is possible, please consider to re-add it.
