### ISSUE TITLE
Daikin FVXS50FV1B is working

### ISSUE THREAD

**Issue by maxPeuck** [smartHomeHub/SmartIR#310]
**Home Assistant version**
0.107.6
**SmartIR version**
1.7.4
**SmartIR configuration**

**Describe the bug**

No bug. Climate AC Daikin FVXS50FV1B is working perfectly with code 1101 and broadlink mini 3

Thank for you work!

**Debug log**

**Comment by vassilis-panos** [comment]
Thanks for your contribution
