### ISSUE TITLE
The Broadlink emitter does not transmit any IR signals

### ISSUE THREAD

**Issue by lucrom61** [smartHomeHub/SmartIR#316]
**Good evening.
I installed on Hassio (HassOS 3.12) SmartIR Installed: 1.7.4

I want to control a Mitsubishi air conditioner with your magnificent instrument.

I configured everything as instructed but the emitter does not transmit any signal.

Below is the part of configuration.yaml****

smartir:

remote:
  - platform: broadlink
    name: IR Living room
    host: 192.168.188.165
    mac: '78: 0F: 77: EC: 11: 4D '
    
  - platform: broadlink
    name: IR Corridor
    host: 192.168.188.166
    mac: 'C8: F7: 42: 16: D0: 57'

climate:

  - platform: smartir
    name: Mitsubishi

    device_code: 1022

    controller_data: 192.168.188.165

    temperature_sensor: sensor.router_2_si7021_temperature
    humidity_sensor: sensor.router_2_si7021_humidity
    power_sensor: switch.ponente_pow

The log from the log

Log details (ERROR)
Logger: homeassistant.core
Source: components / google_assistant / trait.py: 900
First occurred: 16:53:24 (5 occurrences)
Last logged: 17:03:24

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/report_state.py", line 39, in async_entity_state_listener
    entity_data = entity.query_serialize ()
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/helpers.py", line 468, in query_serialize
    deep_update (attrs, trt.query_attributes ())
  File "/usr/src/homeassistant/homeassistant/components/google_assistant/trait.py", line 900, in query_attributes
    response ["humidityAmbientPercent"] = round (float (current_humidity))
ValueError: could not convert string to float: 'None'

And finally a working configuration of "Check Button Card" which always controls the same air conditioner.
This to highlight the anomaly does not depend on Hassio or on
Broadlink

color: 'rgb (75, 75, 77)'
color_type: card
icon: 'mdi: power'
tap_action:
  action: call-service
  service: remote.send_command
  service_data:
    command: on_off
    device: tv_samsung
    entity_id: remote.ir_soggiorno
type: 'custom: button-card'

Looking forward to your kind reply, I offer cordial greetings

**Comment by litinoveweedle** [comment]
This is because SmartIR expect broadlink remote to be configured as a switch component while you have configured it wrongly as a remote component in HA. SmartIR calls service broadlink.send which simply doesn't exists on remote type component.

I would suggest you to really keep with [instructions](https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md) ans configure your broadlink device as a switch to be used with smartIR:
```
switch:
  - platform: broadlink
    host: 192.168.10.10
    mac: '00:00:00:00:00:00'
```

**Comment by lucrom61** [comment]
> Questo perché SmartIR prevede che il telecomando Broadlink sia configurato come componente switch mentre lo si è configurato erroneamente come componente remoto in HA. SmartIR chiama il servizio broadlink.send che semplicemente non esiste sul componente di tipo remoto.
> 
> Ti suggerirei di seguire davvero le [istruzioni](https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md) e di configurare il tuo dispositivo Broadlink come switch da utilizzare con smartIR:
> 
> ```
> switch:
>   - platform: broadlink
>     host: 192.168.10.10
>     mac: '00:00:00:00:00:00'
> ```

Many times the things you have under your eyes are not always seen. Thanks a lot for your help. Now everything works smoothly

**Comment by litinoveweedle** [comment]
:) I am glad, that I could help you. Could you please close this issue?
