### ISSUE TITLE
a problem "media_player" Platform not found: media_player.smartir

### ISSUE THREAD

**Issue by mshafiksh** [smartHomeHub/SmartIR#32]
Thanks for awesome platform
i setup climate with smartir all good, but when trying to add media_player in configuration.yaml 
it gives me "Platform not found: media_player.smartir"  , and i checked the files all good 
it didn't happened with me in climate

**Comment by smartHomeHub** [comment]
Are there any errors in the logs?

**Comment by mshafiksh** [comment]
Here is the log:

Unable to find platform smartir
February 26, 2019, 5:18 PM loader.py (ERROR)
Error loading custom_components.smartir.media_player. Make sure all dependencies are installed
February 26, 2019, 5:18 PM custom_components/smartir/media_player.py (ERROR)

**Comment by smartHomeHub** [comment]
Please restart HA and send me the full log until the media player error appears

**Comment by mshafiksh** [comment]
> Are there any errors in the logs?

thanks
i try to compare climate.py and media_player.py files and found the solution
========================================
1-from homeassistant.components.media_player import (
2-    MediaPlayerDevice, PLATFORM_SCHEMA)
3-from homeassistant.components.media_player.const import (
4- SUPPORT_TURN_OFF, SUPPORT_TURN_ON, SUPPORT_PREVIOUS_TRACK,
5- SUPPORT_NEXT_TRACK, SUPPORT_VOLUME_STEP,SUPPORT_VOLUME_MUTE, 
6- SUPPORT_SELECT_SOURCE, MEDIA_TYPE_CHANNEL)
7-from homeassistant.const import (
8- CONF_NAME, STATE_OFF, STATE_ON, STATE_UNKNOWN)
9- from homeassistant.core import callback, split_entity_id
10-import homeassistant.helpers.config_validation as cv
11-from homeassistant.helpers.restore_state import RestoreEntity
12-from . import Helper

first : you have to delete line 3-from homeassistant.components.media_player.const import 
second : move all 4-5-6 line to be under 1-from homeassistant.components.media_player import
and add ,DOMAIN)

here is the code modify media_player.py

from homeassistant.components.media_player import (
    MediaPlayerDevice, SUPPORT_TURN_OFF, SUPPORT_TURN_ON, SUPPORT_PREVIOUS_TRACK,
    SUPPORT_NEXT_TRACK, SUPPORT_VOLUME_STEP,SUPPORT_VOLUME_MUTE, 
    SUPPORT_SELECT_SOURCE, MEDIA_TYPE_CHANNEL, PLATFORM_SCHEMA, DOMAIN)
from homeassistant.const import (
    CONF_NAME, STATE_OFF, STATE_ON, STATE_UNKNOWN)
from homeassistant.core import callback, split_entity_id
import homeassistant.helpers.config_validation as cv
from homeassistant.helpers.restore_state import RestoreEntity
from . import Helper

thanks again, now all works good

**Comment by smartHomeHub** [comment]
Are you in last HA version?

**Comment by mshafiksh** [comment]
yes, i need to know how to add more than one media player 
i tried to : 

platform: smartir
name: kk
device_code: 1000
controller_send_service: switch.broadlink_send_packet_192_168_1_7

but its not appearing in ui

**Comment by smartHomeHub** [comment]
Are you sure? Because by this fix you make the media player component prior to 0.88.x compatible.

**Comment by smartHomeHub** [comment]
```yaml
media_player:
  - platform: smartir
    name: Media Player 1
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_10_59

  - platform: smartir
    name: Media Player 2
    device_code: 1000
    controller_send_service: switch.broadlink_send_packet_192_168_10_59

```

**Comment by mshafiksh** [comment]
INFO:homeassistant.util.package:Attempting install of colorlog==4.0.2 Testing configuration at /config Failed config General Errors: - Platform not found: media_player.smartir Successful config (partial)
7:25 PM components/hassio/__init__.py (ERROR)

this what i found in log but it works fine
how i fix it?

**Comment by mshafiksh** [comment]
INFO:homeassistant.util.package:Attempting install of colorlog==4.0.2
Testing configuration at /config
Failed config
  General Errors: 
    - Platform not found: media_player.smartir
Successful config (partial)

**Comment by smartHomeHub** [comment]
Please post a screen of your about page
![image](https://user-images.githubusercontent.com/47714957/53510663-35619000-3ac7-11e9-887e-4aea9423070f.png)

**Comment by mshafiksh** [comment]
![untitled](https://user-images.githubusercontent.com/48022402/53541732-dda54200-3b23-11e9-8dbc-99801e5e5fc1.png)

**Comment by smartHomeHub** [comment]
https://github.com/smartHomeHub/SmartIR/issues/32#issuecomment-467915980

**Comment by bpmittal** [comment]
yesterday i was trying to configure smartir for the first time and i am not able to start it

after doing the initial configurations i am getting error

Copy to clipboard
Configuration invalid
Platform not found: media_player.smartir


what to do ?

**Comment by Goriachevviktor** [comment]
Добрый день!
Ошибка.
Platform error media_player.smartir - cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/srv/homeassistant/lib/python3.7/site-packages/homeassistant/components/media_player/__init__.py)
