### ISSUE TITLE
Detected I/O inside the event loop

### ISSUE THREAD

**Issue by vMeph** [smartHomeHub/SmartIR#321]
Log Details (WARNING)
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 9:59:27 PM (1 occurrences)
Last logged: 9:59:27 PM

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for smartir doing I/O at custom_components/smartir/__init__.py, line 68: request = requests.get(MANIFEST_URL.format(branch), stream=True, timeout=10)

**Comment by stast1** [comment]
Similarly:

Home Assistant 0.109.0b2
```
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for smartir doing I/O at custom_components/smartir/__init__.py, line 68: request = requests.get(MANIFEST_URL.format(branch), stream=True, timeout=10)
```

**Comment by vassilis-panos** [comment]
At some point I will remove the update routine.
To fix configure smartir as follows:

```
smartir:
  check_updates: False
```

**Comment by stast1** [comment]
Ok. Thanks!

**Comment by lollo78** [comment]
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 13:36:25 (1 occurrences)
Last logged: 13:36:25

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for smartir doing I/O at custom_components/smartir/__init__.py, line 68: request = requests.get(MANIFEST_URL.format(branch), stream=True, timeout=10)

**Comment by vassilis-panos** [comment]
1.7.5
