### ISSUE TITLE
Export IHC app codes

### ISSUE THREAD

**Issue by edgano** [smartHomeHub/SmartIR#326]
It's not a bug, its a kind of "feature request"

I'm able to learn the codes from the ihc app for an AC devide, and the app allows me to use a pre-configured codes using the brand and model. (IRCODE 5818, Brand 2945)

I would like to export/dump it to use with smartIR

Thanks in advance :smile:

**Comment by chemelli74** [comment]
You may consider learn codes using https://keitetran.github.io/BroadlinkIRTools/dist/#

Simone
