### ISSUE TITLE
York Aircondition

### ISSUE THREAD

**Issue by tyjtyj** [smartHomeHub/SmartIR#33]
Here is what I have from old config

Anyway to figure out file number ? 

# Models: 
[off]
off_command = JgDKAJGQEjYUEBI1EzUUEBISEjYSEhISEjYSEhISEjUTNRISEjYSEhI2EjUTNRI2EhISNhI1EzUTERMRExETERM1EhISEhI2EjYSNRMRExETERMRExETERMRExETNRM1EjYSNRM1EqySjxM1EhISNhI1ExETERM1EhITERM1EhISEhI2EjUTERM1ExETNRI2EjUTNRISEjYSNhI1ExETERMRExETNRISEhISNhI2EjUTERMRExETERMRExETERMREzUSNhI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA==

[cool]
high_17 = JgDKAJGREjYSEhE2EzUTERISEjYSEhISEjYSEhISEjUTNRISEjYSNhETEjYSNRM1EjYSNRM1ExETNRISEhISEhISEhISEhISEhISEhISEhISEhISEhISNhI1EzUTNRI2EjUTNRI2EquRkBI2EhISNRI2ExETERI2EhIRExI2EhISEhI2EjUTERM1EzUSEhI2EjYSNRM1EjYSNRMSEjUTERMRExETERMREhITERMRExESEhMRExETERMREzMUNhI1EzUTNRI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA=='
high_18 = JgDKAJCQFDQTERM1EzUTERMREzQVDxQQFDQUEBQQFDQTNRMRFDMUNBMRFDQUNBI2EzQVMxQ0ExETNRMRExETERMRExETERMRExETERM0FBATERQQFBAUNBQ0EzUTERM0FDQUNBM1Ea2RkBM1EhITNBQ0ExEUEBQ0ExETERI2ExESEhI2EjUTERQ0EjYTERI2EjYTNBQ0EzUTNBQREjUUEBMRExEUEBISExEUEBMRExEUNBMREhISEhMREzUTNRI1FBATNRM1EzQUNBIADQUAAAAAAAAAAAAAAAAAAA=='
high_19 = JgDKAJGQEjYSEhI2EjUTERMREzUSEhISEjYSEhISEjUTNRMREzUSNhISEjYSNhI1EzUSNhI1ExETNRISEhISEhISEhISEhISEhISNhI2EhISEhISEhISNRM1ExETERI2EjYSNRM1Ea2RkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUUEBM1EjYSEhI2EjUTNRM1EzUTNBQQEzUTERISExESEhISEhITERISEzUTNRIRFBAUEBQQFDQUNBMRExESNhI1FDQUNBEADQUAAAAAAAAAAAAAAAAAAA=='
high_20 = JgDKAJGQEjYSEhI2EjUTERMREzUSEhISEjYSEhISEjYSNRMREzUSNhISEjYSNhI1EzUSNhI1ExETNRMRExETERMRExESEhMRExETNRISEhISEhISEhISNhI1ExETNRM1EjYSNRM1E6yRjxM1ExETNRI2EhISEhI1ExETERM1ExETERM1EjYSEhI2EjYSERM1EzUSNhI1EzUTNRISEjYSEhISEhISEhISEhISEhISEjYSEhISEhETERMSEjUTNRISEjYSNhI1EzUSNhIADQUAAAAAAAAAAAAAAAAAAA=='
high_21 = JgDKAJGQEzUSEhI2EjUTERMREzUSEhISEzUSEhISEjYSNRMREzUTNRMREjYSNhI1EzUSNhI2EhISNRMRExETERMRExETERMREzUSNhISEhISEhISEhISNhISEhISNRM1EjYSNRM1EqyRkBI1ExETNRM1EhISEhI2EhISEhI1ExETERM1EzUSEhI2EjYSEhI1EzUSNhI2EjUTNRISEjYSEhISEhISEhISEhISEhI1EzUSEhISEhISEhISEjYSEhISEjUTNRM1EjYSNRIADQUAAAAAAAAAAAAAAAAAAA=='
high_22 = JgDKAJCREjYSERM1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNRM1ExETNRISEhISEhISEhISEhISEjYSNRM1EhISEhISEhISNhISEhISEhI2EjUTNRI2Ea2RkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERQ0EzUSEhI2EjYSNRM1EjYSNRUQEjUUEBQQFBATERMREhITERQ0FDQSNRQQExETERMRFDQTERMRExETNRI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA=='
high_23 = JgDKAJGPEzUTERM1EjYSEhISEjUTEhISEjUTERMREzUSNhISEjYSNhISEjUTNRM1EjYSNRM1EhITNRISEhISEhISEhISEhISEjYSEhI1ExETERMRExETNRMREzUTERM1EjYSNRM1E6uRkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERM1EzUSEhI2EjYSNRM1EjYSNRMSEjUTERMRExETERISEhITERM1EhISNhISEhISEhISEjYSEhI1ExETNRM1EjYSNhIADQUAAAAAAAAAAAAAAAAAAA=='
high_24 = JgDKAJCREzUTERI2EjYSEhISEjUTERMREzUTERMREzUSNhISEjYSNRMREzUTNRI2EjUTNRI2EhISNhISEhISEhQPExETEhISEjUTERQQExETERMRExETNRMREjYSNhI1EzUSNhI1Eq2TjhI1ExETNRM1EhIUEBQ0EhISEhI2EhISEhI1EzUSEhI2EjYSEhI2EjUTNRI2EjUTNRMREzUSEhISEhISEhISEhISEhI2EhISEhISEhISEhISEjYSERM1EzUSNhI1EzUSNhEADQUAAAAAAAAAAAAAAAAAAA=='
high_25 = JgDKAJKPEzUSEhI2EjUTERMREzUSEhISEjYSEhISEjYSNRMREzUTNRISEjYSNhI1EzUSNhI1ExISNRMRExETERMREhISEhI2EjYSEhISEhISEhISEhISEhISEjYSNRM1EjYSNRM1EqyRkBM1EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERM1EjYSEhI2EjUTNRM1EjYSNRMREzUSEhISEhISEhISEhISNhI1ExETERMRExETERMRExETERM1EzUSNhI1EzUSNhIADQUAAAAAAAAAAAAAAAAAAA=='
high_26 = JgDKAJGQEjYSEhI1EzUTERMREzUSEhISEjYSEhISEjYSNRMREzUTNRISEjYSNhI1EzUSNhI2EhISNRMRExETERMRExETERM1EjYSEhI2EhISEhISEhISEhISEjYSEhI1EzUTNRI2Ea2RkBI1ExETNRI2EhISEhI1ExISEhI1ExETERM1EjYSEhI2EjYSEhI1EzUSNhI1EzUTNRISEjYSEhISEhISEhISEhISNhI1ExETNRISEhISEhISEhITERI2EhISNhI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA=='
high_27 = JgDKAJGQEjYSEhI1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNRM1ExETNRISEhISEhISEhISEhI2EhISEhI1ExETERMRExETERM1EzUSEhI2EjUTNRI2Ea2RkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERI2EjYSEhI2EjUTNRI2EjUTNRMREzUSEhISEhISEhISEhISNhISEhISNRMRExETERMRExETNRI2EhISNhI1EzUSNhEADQUAAAAAAAAAAAAAAAAAAA=='
high_28 = JgDKAJGQEjYSEhI1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNhI1ExETNRISEhISEhISEhISEhI2EhISEhISEhISEhISEhISEhI2EjUTNRI2EjYSNRM1Ea2RkBM1EhISNhI1ExETERM1EhISEhM1EhISEhI2EjUTERM1EzUTERM1EjYSNRM1EzUSNhISEjUTERMRExETERMRExETNRMRExETERMRExETERMRExETNRM1EjYSNRM1EjYSNhEADQUAAAAAAAAAAAAAAAAAAA=='
high_29 = JgDKAJGREjUTERM1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNhI1ExETNRISEhISEhISEhISEhI2EhISNhISEhISEhISEhISEhI2EhISNRM1EzUSNhI1E6uSjxM1EhISNhI2EhETERM1ExETERM1EhISEhI2EjUTERM1EzUTERM1EjYSNhI1EzUSNhISEjUTERMRExETERMRExETNRMREzUTERMRExETERMRExETNRISEjYSNhI1EzUSNhEADQUAAAAAAAAAAAAAAAAAAA=='
high_30 = JgDKAJGQEjYSEhI2EjUTERMREzUSEhISEjYSEhISEjYSNRMREzUTNRMREjYSNhI1EzUSNhI2EhISNRMRExETERMRExETERM1ExESNhI2EhISEhISEhISEhI1ExETERM1EjYSNRM1E6yRjxM1EhISNhI2EhISEhI1ExETERM1ExETERM1EjYSEhI1EzUTERM1EzUSNhI1EzUSNhISEjYSEhISEhETERMRExISNRMREzUTNRISEhISEhISEhISNhISEhISNRM1EjYSNRMADQUAAAAAAAAAAAAAAAAAAA=='

**Comment by smartHomeHub** [comment]
Sorry, I didn't get it. Do you want to convert the file?

**Comment by tyjtyj** [comment]
i managed to convert the file but I am not sure what number I should put. is there a standard you device on the number ?

**Comment by smartHomeHub** [comment]
Add a number that not exists in the list. I will not upload this file because even the cool mode is incomplete

**Comment by tyjtyj** [comment]
{
  "manufacturer": "York",
  "supportedModels": [
    "Unknown"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "minTemperature": 17,
  "maxTemperature": 30,
  "precision": 1,
  "operationModes": [
    "cool"
  ],
  "fanModes": [
    "high"
  ],
  "commands": {
    "off": "JgDKAJGQEjYUEBI1EzUUEBISEjYSEhISEjYSEhISEjUTNRISEjYSEhI2EjUTNRI2EhISNhI1EzUTERMRExETERM1EhISEhI2EjYSNRMRExETERMRExETERMRExETNRM1EjYSNRM1EqySjxM1EhISNhI1ExETERM1EhITERM1EhISEhI2EjUTERM1ExETNRI2EjUTNRISEjYSNhI1ExETERMRExETNRISEhISNhI2EjUTERMRExETERMRExETERMREzUSNhI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA==",
    "cool": {
      "high": {
        "17": "JgDKAJGREjYSEhE2EzUTERISEjYSEhISEjYSEhISEjUTNRISEjYSNhETEjYSNRM1EjYSNRM1ExETNRISEhISEhISEhISEhISEhISEhISEhISEhISEhISNhI1EzUTNRI2EjUTNRI2EquRkBI2EhISNRI2ExETERI2EhIRExI2EhISEhI2EjUTERM1EzUSEhI2EjYSNRM1EjYSNRMSEjUTERMRExETERMREhITERMRExESEhMRExETERMREzMUNhI1EzUTNRI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA==",
        "18": "JgDKAJCQFDQTERM1EzUTERMREzQVDxQQFDQUEBQQFDQTNRMRFDMUNBMRFDQUNBI2EzQVMxQ0ExETNRMRExETERMRExETERMRExETERM0FBATERQQFBAUNBQ0EzUTERM0FDQUNBM1Ea2RkBM1EhITNBQ0ExEUEBQ0ExETERI2ExESEhI2EjUTERQ0EjYTERI2EjYTNBQ0EzUTNBQREjUUEBMRExEUEBISExEUEBMRExEUNBMREhISEhMREzUTNRI1FBATNRM1EzQUNBIADQUAAAAAAAAAAAAAAAAAAA==",
        "19": "JgDKAJGQEjYSEhI2EjUTERMREzUSEhISEjYSEhISEjUTNRMREzUSNhISEjYSNhI1EzUSNhI1ExETNRISEhISEhISEhISEhISEhISNhI2EhISEhISEhISNRM1ExETERI2EjYSNRM1Ea2RkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUUEBM1EjYSEhI2EjUTNRM1EzUTNBQQEzUTERISExESEhISEhITERISEzUTNRIRFBAUEBQQFDQUNBMRExESNhI1FDQUNBEADQUAAAAAAAAAAAAAAAAAAA==",
        "20": "JgDKAJGQEjYSEhI2EjUTERMREzUSEhISEjYSEhISEjYSNRMREzUSNhISEjYSNhI1EzUSNhI1ExETNRMRExETERMRExESEhMRExETNRISEhISEhISEhISNhI1ExETNRM1EjYSNRM1E6yRjxM1ExETNRI2EhISEhI1ExETERM1ExETERM1EjYSEhI2EjYSERM1EzUSNhI1EzUTNRISEjYSEhISEhISEhISEhISEhISEjYSEhISEhETERMSEjUTNRISEjYSNhI1EzUSNhIADQUAAAAAAAAAAAAAAAAAAA==",
        "21": "JgDKAJGQEzUSEhI2EjUTERMREzUSEhISEzUSEhISEjYSNRMREzUTNRMREjYSNhI1EzUSNhI2EhISNRMRExETERMRExETERMREzUSNhISEhISEhISEhISNhISEhISNRM1EjYSNRM1EqyRkBI1ExETNRM1EhISEhI2EhISEhI1ExETERM1EzUSEhI2EjYSEhI1EzUSNhI2EjUTNRISEjYSEhISEhISEhISEhISEhI1EzUSEhISEhISEhISEjYSEhISEjUTNRM1EjYSNRIADQUAAAAAAAAAAAAAAAAAAA==",
        "22": "JgDKAJCREjYSERM1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNRM1ExETNRISEhISEhISEhISEhISEjYSNRM1EhISEhISEhISNhISEhISEhI2EjUTNRI2Ea2RkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERQ0EzUSEhI2EjYSNRM1EjYSNRUQEjUUEBQQFBATERMREhITERQ0FDQSNRQQExETERMRFDQTERMRExETNRI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA==",
        "23": "JgDKAJGPEzUTERM1EjYSEhISEjUTEhISEjUTERMREzUSNhISEjYSNhISEjUTNRM1EjYSNRM1EhITNRISEhISEhISEhISEhISEjYSEhI1ExETERMRExETNRMREzUTERM1EjYSNRM1E6uRkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERM1EzUSEhI2EjYSNRM1EjYSNRMSEjUTERMRExETERISEhITERM1EhISNhISEhISEhISEjYSEhI1ExETNRM1EjYSNhIADQUAAAAAAAAAAAAAAAAAAA==",
        "24": "JgDKAJCREzUTERI2EjYSEhISEjUTERMREzUTERMREzUSNhISEjYSNRMREzUTNRI2EjUTNRI2EhISNhISEhISEhQPExETEhISEjUTERQQExETERMRExETNRMREjYSNhI1EzUSNhI1Eq2TjhI1ExETNRM1EhIUEBQ0EhISEhI2EhISEhI1EzUSEhI2EjYSEhI2EjUTNRI2EjUTNRMREzUSEhISEhISEhISEhISEhI2EhISEhISEhISEhISEjYSERM1EzUSNhI1EzUSNhEADQUAAAAAAAAAAAAAAAAAAA==",
        "25": "JgDKAJKPEzUSEhI2EjUTERMREzUSEhISEjYSEhISEjYSNRMREzUTNRISEjYSNhI1EzUSNhI1ExISNRMRExETERMREhISEhI2EjYSEhISEhISEhISEhISEhISEjYSNRM1EjYSNRM1EqyRkBM1EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERM1EjYSEhI2EjUTNRM1EjYSNRMREzUSEhISEhISEhISEhISNhI1ExETERMRExETERMRExETERM1EzUSNhI1EzUSNhIADQUAAAAAAAAAAAAAAAAAAA==",
        "26": "JgDKAJGQEjYSEhI1EzUTERMREzUSEhISEjYSEhISEjYSNRMREzUTNRISEjYSNhI1EzUSNhI2EhISNRMRExETERMRExETERM1EjYSEhI2EhISEhISEhISEhISEjYSEhI1EzUTNRI2Ea2RkBI1ExETNRI2EhISEhI1ExISEhI1ExETERM1EjYSEhI2EjYSEhI1EzUSNhI1EzUTNRISEjYSEhISEhISEhISEhISNhI1ExETNRISEhISEhISEhITERI2EhISNhI2EjUTNRIADQUAAAAAAAAAAAAAAAAAAA==",
        "27": "JgDKAJGQEjYSEhI1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNRM1ExETNRISEhISEhISEhISEhI2EhISEhI1ExETERMRExETERM1EzUSEhI2EjUTNRI2Ea2RkBI2EhISNhI1ExETERM1EhISEhI2EhISEhI2EjUTERI2EjYSEhI2EjUTNRI2EjUTNRMREzUSEhISEhISEhISEhISNhISEhISNRMRExETERMRExETNRI2EhISNhI1EzUSNhEADQUAAAAAAAAAAAAAAAAAAA==",
        "28": "JgDKAJGQEjYSEhI1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNhI1ExETNRISEhISEhISEhISEhI2EhISEhISEhISEhISEhISEhI2EjUTNRI2EjYSNRM1Ea2RkBM1EhISNhI1ExETERM1EhISEhM1EhISEhI2EjUTERM1EzUTERM1EjYSNRM1EzUSNhISEjUTERMRExETERMRExETNRMRExETERMRExETERMRExETNRM1EjYSNRM1EjYSNhEADQUAAAAAAAAAAAAAAAAAAA==",
        "29": "JgDKAJGREjUTERM1EzUSEhISEjYSEhISEjYSEhISEjUTNRISEjYSNhISEjYSNRM1EjYSNhI1ExETNRISEhISEhISEhISEhI2EhISNhISEhISEhISEhISEhI2EhISNRM1EzUSNhI1E6uSjxM1EhISNhI2EhETERM1ExETERM1EhISEhI2EjUTERM1EzUTERM1EjYSNhI1EzUSNhISEjUTERMRExETERMRExETNRMREzUTERMRExETERMRExETNRISEjYSNhI1EzUSNhEADQUAAAAAAAAAAAAAAAAAAA==",
        "30": "JgDKAJGQEjYSEhI2EjUTERMREzUSEhISEjYSEhISEjYSNRMREzUTNRMREjYSNhI1EzUSNhI2EhISNRMRExETERMRExETERM1ExESNhI2EhISEhISEhISEhI1ExETERM1EjYSNRM1E6yRjxM1EhISNhI2EhISEhI1ExETERM1ExETERM1EjYSEhI1EzUTERM1EzUSNhI1EzUSNhISEjYSEhISEhETERMRExISNRMREzUTNRISEhISEhISEhISNhISEhISNRM1EjYSNRMADQUAAAAAAAAAAAAAAAAAAA=="
      }
    }
  }
}
