### ISSUE TITLE
Detected I/O inside the event loop: line 174,372,219

### ISSUE THREAD

**Issue by cicerone73** [smartHomeHub/SmartIR#331]
Logger: homeassistant.util.async_
Source: util/async_.py:120
First occurred: 16:47:36 (8 occurrences)
Last logged: 16:51:42

Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 174: headers=self._headers, json=app_details)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 372: ), headers=self._headers)
Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for sonoff doing I/O at custom_components/sonoff/__init__.py, line 219: r = requests.post('https://%s-disp.coolkit.cc:8080/dispatch/app' % self._api_region, headers=self._headers)

**Comment by vassilis-panos** [comment]
custom_components/**sonoff**/init.py
