### ISSUE TITLE
Mida model for code 1382

### ISSUE THREAD

**Issue by alex00x6** [smartHomeHub/SmartIR#335]
Not an issue, but just informing that Midea code 1382 works with Midea MSY-12HRDN1
(although not all functions present on the original remote are implemented, but close enough)
![image](https://user-images.githubusercontent.com/21043225/81057894-fb172e00-8ed5-11ea-81d4-7ba007e3d0d8.png)

**Comment by vassilis-panos** [comment]
Thank you!
