### ISSUE TITLE
Multiple Sensors

### ISSUE THREAD

**Issue by Sphinix1** [smartHomeHub/SmartIR#338]
i am trying to add  multiple broadlink RM devices   to control multiple devices (TV,AC,Curtains) in 5 different rooms. would prefer to have them in seperate files, 1 per room. can anyone guide me with the yaml file
`switch:
  - platform: broadlink
    host: 192.168.xx.xx
    mac: '98:0F:88:18:0D:8E'

climate:
  - platform: smartir
    name: Bedroom 1 AC
    unique_id: Bedroom1_ac
    device_code: 1760
    controller_data: 192.168.xx.xx
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
    
media_player:
  - platform: smartir
    name: Bedroom 1 TV
    unique_id: Bedroom1_TV
    device_code: 1060
    controller_data: 192.168.xx.xx
    power_sensor: binary_sensor.tv_power

  - platform: broadlink
    host: 192.168.xx.xx
    mac: '98:0F:88:18:0D:9E'

climate:
  - platform: smartir
    name: Bedroom 2 AC
    unique_id: Bedroom2_ac
    device_code: 1760
    controller_data: 192.168.xx.xx
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.ac_power
    
media_player:
  - platform: smartir
    name: Bedroom 2 TV
    unique_id: Bedroom2_TV
    device_code: 1060
    controller_data: 192.168.xx.xx
    power_sensor: binary_sensor.tv_power
`

**Comment by tristone-cz** [comment]
I guess you are searchign for this:
https://www.home-assistant.io/docs/configuration/packages/
