### ISSUE TITLE
Philips TV Codes 26PFL560H

### ISSUE THREAD

**Issue by dimafemabo** [smartHomeHub/SmartIR#345]
This is actually an information or feedback about the "smartir Philips TV" 

**Home Assistant version**
0.109.3
**SmartIR version**
1.9.0

It  works with:
Philips Model 26PFL560H and the Philips IR codes work as follows:
On / Off
Volume up / Volume down
Input Selctor:
well, except that the names provided don't match the selectd input, but all can be selected and eventually you get where you want to (;-))
Thanks for the great work!

**Comment by vassilis-panos** [comment]
You can override the source names [see here](https://github.com/smartHomeHub/SmartIR/blob/master/docs/MEDIA_PLAYER.md#overriding-source-names).
Thank you

**Comment by dimafemabo** [comment]
Thank you, 
I found this already.
Such a cool integration you did here!
I love it,
needs to become a standard integration for hasss.io (;-))
Cheers
Dietger
