### ISSUE TITLE
Delonghi PAC AN 111 file or IR codes

### ISSUE THREAD

**Issue by dimafemabo** [smartHomeHub/SmartIR#346]
I searched the many sources I could find, but ultimately thought to ask the wizzards.

Issues not containing the minimum requirements will be closed:

- Issues without a description (using the header is not good enough) will be closed.
- Issues without debug logging will be closed.
- Issues without configuration will be closed
-->

**Home Assistant version**
0.109.3
**SmartIR version**
1.9.0
**SmartIR configuration**
n/a
```yaml
n/a
Add configuration here

**Describe the bug**
I hope this is the correct forum, otherwise please direct me to the right one.
I am using a DeLonghi PAC AN 111 portable AC unit and want to controll it with the smartir climate section. 
I couldn't find any IR codes that I might be able to use and wonder if there is a device using the same sort of IR codes.
I am afraid my handheld IR control for the AC is broken and I can't figure a way to learn the codes.
Anyone, any idea or ideally a json file with the codes?
Any help greatly appreciated.

Dietger

**Comment by alexander-mikhnov** [comment]
I have a config file for my Delonghi PAC N82. Maybe it will work for you.
[2727.zip](https://github.com/smartHomeHub/SmartIR/files/4634001/2727.zip)

**Comment by dimafemabo** [comment]
Perfect!
Many thanks that indeed did the trick.
I added the zipfile to the climate subdirectory, entered the file number in the config and tried it out.
So: 
1) I thank you for sharing the file
2) Can happily confirm it works for Delonghi PAC AN 111

This is a great community!
Dietger

**Comment by vassilis-panos** [comment]
@alexander-mikhnov Can I include it in the list?

**Comment by alexander-mikhnov** [comment]
@vassilis-panos sure, absolutely :)
