### ISSUE TITLE
Error in Home assistant after updating smartir version 1.10.0

### ISSUE THREAD

**Issue by Jaguaza** [smartHomeHub/SmartIR#347]
** Home Assistant version **

Home Assistant 0.109.6

** SmartIR version **

version 1.10.0

** SmartIR configuration **

`` yaml

Add configuration here

#BROADLINK MEDIA_PLAYER
smartir:

media_player:
  - platform: smartir
    name: TELEVISIÓN SALÓN
    unique_id: television_salon
    device_code: 1061
    controller_data: 192.168.200.9
    power_sensor: binary_sensor.tv_salon

  - platform: smartir
    name: QVIART
    unique_id: qviart
    device_code: 1062
    controller_data: 192.168.200.75
    power_sensor: binary_sensor.qviart

  - platform: smartir
    name: AMPLIFIER
    unique_id: amplifier
    device_code: 1063
    controller_data: 192.168.200.9

** Describe the bug **

I can't even restart home assistant, everything was working fine and in the last update of smartir it broke.

** Debug log **

Registration details (ERROR)
Logger: homeassistant.components.hassio
Source: components / hassio / __ init__.py:277
Integration: Hass.io (documentation, issues)
First occurred: 17:37:06 (1 occurrences)
Last logged in: 17:37:06

Platform error media_player.smartir - cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py) Platform error media_player.smartir - cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/usr/src/homeassistant/homeassistant/components/media_player/__init__.py) Platform error media_player.smartir - cannot import name 'MediaPlayerEntity' from 'homeassistant.components.media_player' (/ usr / src / homeassistant / homeassistant / components / media_player / __ init__.py)

**Comment by chemelli74** [comment]
version 1.10.0 is only for HA **>= 0.110.x**, but you are on 0.109.6 

Simone

**Comment by Jaguaza** [comment]
Can I go back?

**Comment by chemelli74** [comment]
Yes of course, if you have HACS would be even easier

Simone

**Comment by Jaguaza** [comment]
If I have hasc, but never come down

**Comment by vassilis-panos** [comment]
How did you update?

**Comment by Jaguaza** [comment]
> ¿Cómo actualizaste?

Hacs

**Comment by Jaguaza** [comment]
I saw how it is done, I select the previous version and reinstall it.

**Comment by Jaguaza** [comment]
Thanks to all it can be closed.

**Comment by vassilis-panos** [comment]
Strange. How does it allow you to update?
![εικόνα](https://user-images.githubusercontent.com/4130346/81959959-eabf2b80-9618-11ea-9790-e76a22f40b6a.png)

**Comment by Jaguaza** [comment]
> Extraño. ¿Cómo te permite actualizar?
> ![εικόνα](https://user-images.githubusercontent.com/4130346/81959959-eabf2b80-9618-11ea-9790-e76a22f40b6a.png)

If you want, I can record the screen again, in 0.109.6 I update

**Comment by chemelli74** [comment]
> Strange. How does it allow you to update?
> ![εικόνα](https://user-images.githubusercontent.com/4130346/81959959-eabf2b80-9618-11ea-9790-e76a22f40b6a.png)

I think you forgot to commit new hacs.json.
Current one in repository reports:

`"homeassistant": "0.96.0",`

Simone
