### ISSUE TITLE
climate actual state

### ISSUE THREAD

**Issue by tyjtyj** [smartHomeHub/SmartIR#35]
On the climate card,

There is on/off switch. I assume it is data from binary sensor power_sensor. if so, it should be showing data and not actionable switch. 

When I switch the on/off switch, the HA logs shows "Press the key you want Home Assistant to learn"

Can you explain bit about the on/off switch ? 

If it is just shows the binary sensor state, it should be "Power State" instead of "On/Off"

**Comment by smartHomeHub** [comment]
Please post a picture of the switch

**Comment by tyjtyj** [comment]
![capture5](https://user-images.githubusercontent.com/5368474/53432541-a8b6c380-3a2d-11e9-8233-fc8d5cf7fa05.PNG)

**Comment by smartHomeHub** [comment]
Did you try to test it? :) If you turn off the switch your unit will turn off. If turn on the switch the unit will turn on in last "non off mode". This is useful for voice assistants to simply say "Turn on the AC".

**Comment by tyjtyj** [comment]
I found some error in the yaml file. I fixed it seems to fixed the issue.. will test voice assistant again...
i put 
switch.broadlink_learn_command_192_168_11_62
instead of 
switch.broadlink_send_packet_192_168_11_62
my mistake. 

currently away from home to validate it.. thanks for help. appreciate it.
