### ISSUE TITLE
Warning: MediaPlayerDevice is deprecated, modify SmartIRMediaPlayer to extend MediaPlayerEntity

### ISSUE THREAD

**Issue by kaosmagix** [smartHomeHub/SmartIR#350]
Home Assistant 0.110.0b2

MediaPlayerDevice is deprecated, modify SmartIRMediaPlayer to extend MediaPlayerEntity

This warning appears in the logs when starting HA (also for a few other custom components).

(No idea what it entails but as it is a deprecation warning I thought it would be useful to know)

Thanks for this great component!

**Comment by vassilis-panos** [comment]
https://github.com/smartHomeHub/SmartIR/releases/tag/1.10.0
