### ISSUE TITLE
Can not import climate entity

### ISSUE THREAD

**Issue by H30lth** [smartHomeHub/SmartIR#354]
hass version: Home Assistant 0.109.6

issue:
 When checking config file in home assistant receive error - 
Platform error climate.smartir - cannot import name 'ClimateEntity' from 'homeassistant.components.climate' (/usr/src/homeassistant/homeassistant/components/climate/__init__.py)

yaml is - 

smartir:

switches:
  - platform: broadlink
    host: 1.1.1.1
    mac: 00:00:00:00:00:00
    type: rm4c_mini

climate:
  - platform: smartir
    name: living room ac 02
    unique_id: Living_room_ac_02
    device_code: 1101
    controller_data: 1.1.1.1

**Comment by vassilis-panos** [comment]
Please try 1.9.0
https://github.com/smartHomeHub/SmartIR/tree/1.9.0

**Comment by H30lth** [comment]
Thanks thats done it. <3
