### ISSUE TITLE
Update Available but not compatible with current Home-Assistant

### ISSUE THREAD

**Issue by ranrinc** [smartHomeHub/SmartIR#356]
**Home Assistant version**
0.109.6

**SmartIR version**
1.9.0

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

It capture that new smartIR is available but not compatible with current Home-Assistant
<img width="472" alt="Screen Shot 2020-05-17 at 7 04 58 PM" src="https://user-images.githubusercontent.com/15801696/82144643-63202980-9871-11ea-91af-e147d0ebaa73.png">

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by vassilis-panos** [comment]
This is not a bug. This protects you from installing a version that is not compatible with your HA

**Comment by ranrinc** [comment]
> This is not a bug. This protects you from installing a version that is not compatible with your HA

Well the required smartIR is 0.110? which Home-Assistant latest release are 0.109.6?

**Comment by vassilis-panos** [comment]
Last release is 0.110.0b3 ;)

**Comment by pr0fetul** [comment]
Hi, my HA reports also 109.6. And latest SmartIR not being compatible with it. I do not think that HA 110 has been released yet.

**Comment by vassilis-panos** [comment]
The 110 beta is out from Wednesday.

**Comment by t0mmy44-h** [comment]
Seems pretty unreasonable to only release updates that support the absolute latest version. How can someone who hasn't updated for several versions (e.g. moving house and had a couple of days/weeks offline) update the plugin if they're not on the beta channel of Home Assistant?

**Comment by pr0fetul** [comment]
Also, being on Beta channel means by default that that version is not stable enough for a public release. Upgrading to a beta version might break things /integrations or other stuff. My 2 cents.

**Comment by vassilis-panos** [comment]
What's the problem here? The automatic updater of SmartIR informs you that the latest version is not compatible and does not allow you to update. HACS also does not allow you to update. Releases also indicate which version is compatible. What more can I do?

**Comment by vassilis-panos** [comment]
And finally, it's not my choice not to support the previous version of HA. There are changes in HA core that do not allow me.

https://github.com/smartHomeHub/SmartIR/releases
#342

**Comment by vassilis-panos** [comment]
@pr0fetul No one is forcing you to update to beta, as no one is forcing you to update SmartIR. I would like to know what your status would be if you wanted to update HA immediately after its official release and SmartIR could not work due to HA core changes.
SmartIR 1.10 waits you //fixed// when you decide to update your HA instance to 0.110.

**Comment by ranrinc** [comment]
> Last release is 0.110.0b3 ;)

Got it.. thanks..
