### ISSUE TITLE
FAN Component MQTT Not working (Can we have sample Json file for MQTT)

### ISSUE THREAD

**Issue by ceaswaran** [smartHomeHub/SmartIR#365]
**Home Assistant version 0.109.6**

**SmartIR version 1.11.0**

**SmartIR configuration**

```- platform: smartir
  name: LivingRoom SmartIR fan
  unique_id: livingroom_smartir_fan
  device_code: 950522
  controller_data: cmnd/sonoffir/IRsend
  power_sensor: switch.living_room_fan 

```

**Describe the bug**

After adding the component I see  fan.livingroom_smartir_fan entitiy always unavailable error attached below under debug log section.
Please help

```MQTT Fan 950522 Json file:
{
  "manufacturer": "Orient Electric",
  "supportedModels": [
    "BLDC"
  ],
  "supportedController": "MQTT",
  "commandsEncoding": "Raw",
  "speed": [
    "level1",
    "level2",
    "level3",
    "level4",
    "level5"
  ],
  "commands": {
    "off": "{"Protocol":"NEC","Bits":32,"Data":0x31CE08F7}",
    "default": {
      "level1": "{"Protocol":"NEC","Bits":32,"Data":0x31CE20DF}",
      "level2": "{"Protocol":"NEC","Bits":32,"Data":0x31CEA05F}",
      "level3": "{"Protocol":"NEC","Bits":32,"Data":0x31CE609F}",
      "level4": "{"Protocol":"NEC","Bits":32,"Data":0x31CEE01F}",
      "level5": "{"Protocol":"NEC","Bits":32,"Data":0x31CE10EF}"
    }
  }
}```
When I enter the following console commands in Tasmota console the fan works well thru MQTT
```tele/sonoffir/RESULT

OFF
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CE08F7}

ON
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CEF00F}

1
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CE20DF}

2
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CEA05F}

3
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CE609F}

4
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CEE01F}

5
IRsend {"Protocol":"NEC","Bits":32,"Data":0x31CE10EF}```


**Debug log**

```Log Details (ERROR)
Logger: custom_components.smartir.fan
Source: custom_components/smartir/fan.py:72
Integration: SmartIR (documentation)
First occurred: 4:30:05 PM (1 occurrences)
Last logged: 4:30:05 PM

The device JSON file is invalid```

**Additional context**

Add any other context about the problem here.

**Comment by vassilis-panos** [comment]
The json file has format issues. Try the following

```
{
  "manufacturer": "Orient Electric",
  "supportedModels": [
    "BLDC"
  ],
  "supportedController": "MQTT",
  "commandsEncoding": "Raw",
  "speed": [
    "level1",
    "level2",
    "level3",
    "level4",
    "level5"
  ],
  "commands": {
    "off": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE08F7}",
    "default": {
      "level1": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE20DF}",
      "level2": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CEA05F}",
      "level3": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE609F}",
      "level4": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CEE01F}",
      "level5": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE10EF}"
    }
  }
}
```

**Comment by ceaswaran** [comment]
> The json file has format issues. Try the following
> 
> ```
> {
>   "manufacturer": "Orient Electric",
>   "supportedModels": [
>     "BLDC"
>   ],
>   "supportedController": "MQTT",
>   "commandsEncoding": "Raw",
>   "speed": [
>     "level1",
>     "level2",
>     "level3",
>     "level4",
>     "level5"
>   ],
>   "commands": {
>     "off": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE08F7}",
>     "default": {
>       "level1": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE20DF}",
>       "level2": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CEA05F}",
>       "level3": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE609F}",
>       "level4": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CEE01F}",
>       "level5": "{\"Protocol\":\"NEC\",\"Bits\":32,\"Data\":0x31CE10EF}"
>     }
>   }
> }
> ```

Ya thanks above Json makes the entity available.

I have the following queries reg Smart IR
1. Though I see signal being sent from IR transmitted to the FAN, The fan dosent respond to set speed. Happens both with MQTT controller (Tasmota) & Broadlink controller as well (Ref video attachment wr Fan receives the signal  but no change is Speed to low)

But When i send the same Signal from Tasmota console the speed is set to desired. This is happening randomly, not always. 

![ezgif com-optimize](https://user-images.githubusercontent.com/40624146/82912367-a756ac80-9f8a-11ea-8ae0-a1e2f69449f6.gif)


2. What is the purpose of Power sensor in all the Smart IR components I was in an understanding/assumption when power sensor is OFF state, all the IR controls of the device will be disabled(OFF)  in the UI & even if we try to contol the Temprature It wont initiate IR singal to the controller but thats not the case in reality. Example: If the power sensor for My AC is OFF, I won't be able to control the Modes, Temperature etc in Home Assitant UI .
But that's not the case. Though the power sensor is OFF I am able to change the temperature & my IR Controller sends signal to the AC.

Please clarify. Thanks in advance

**Comment by vassilis-panos** [comment]
1. SmartIR is using Home Assistant mqtt.publish service. Try to send the command through services and see if the behavior is the same. Please test it multiple times.
2. The power sensor is useful when a remote control is also used. When a user turns off the unit from the remote control, the state in HA is also goes to off. Of course, the user must be able to turn on / set the mode from HA.

**Comment by ceaswaran** [comment]
@vassilis-panos 
1. I was able to send MQTT publish from Home Assitant call service as well as from node-red MQTT with these above commands it is 100% working fine.
But, the same code from Smart IR component is not making the fan switch to desired speed though I see Fans receiving LED Blinks. Its always a Hit & miss in case of Smart IR but not in case of MQTT service call.

2. Ya , understood now. But shoulnt the Smart IR component also have ON as well? If power sensor is OFF auto diable ON to off??

**Comment by vassilis-panos** [comment]
I can't think of anything right now that could cause it. The component does nothing more than read the command from the json file and send it through the service.

When the power sensor goes to on, the component state updates to ON. And if the power sensor goes to off, the component state updates to Off.

**Comment by ceaswaran** [comment]
> I can't think of anything right now that could cause it. The component does nothing more than read the command from the json file and send it through the service.
> 
> When the power sensor goes to on, the component state updates to ON. And if the power sensor goes to off, the component state updates to Off.

Thanks for the clarification.
U have made an awesome component thanks
