### ISSUE TITLE
Can't use fan_only mode in Home Assistant 

### ISSUE THREAD

**Issue by alpdmrel** [smartHomeHub/SmartIR#368]
I Have the climate IR my ac works. I can set the temperature, set to " heat, cool, dry, auto" but I cant use the fan only mode. It doesn't show up in the operation tab inside climate control on the dashboard.
![image](https://user-images.githubusercontent.com/45689779/83118661-52747c80-a0d7-11ea-8104-6c1cbc727751.png)
And when I try to set the "hvac_mode: fan_only" it does nothing and shows up like this.
![image](https://user-images.githubusercontent.com/45689779/83118606-3bce2580-a0d7-11ea-905c-497aea3fd3ec.png)
This is the code I used for Profilo KLM132000IU
https://bin.privacytools.io/?340d88ef5ae4dee4#mSXteg2MUu3dxAaQHYK/LHMMbHehnHmiqlL0R6MN+Gs=

**Comment by vassilis-panos** [comment]
```
"operationModes":[
    "cool",
    "dry",
    "fan_only",    <======
    "heat",
    "auto"
  
],
```
```
"fan_only":{      <======
   "auto":{        
       "16"
```

**Comment by alpdmrel** [comment]
Thanks that worked.
This the working .json file for Profilo KLM132000IU AC if you wanna add it to the repo.
https://bin.privacytools.io/?4f0c3beea517a4a7#aa+ly/jiJN1lhmFA0DMS9NjhWnR1xdf5nyyDDjwY+6g=
