### ISSUE TITLE
dyson fan control

### ISSUE THREAD

**Issue by pcherkash** [smartHomeHub/SmartIR#37]
Prompt how to set a configuration for fans at which speed is set by buttons + and - (on a 10-point scale). On the example of fan Dyson AM09, remote - http://www.thg.ru/consumer/obzor_dyson_am09_hot_plus_cool/images/dyson_am09_hot_plus_cool_010b.jpg/.
Red buttons set the temperature, blue turns on the fan without heating, and white sets the fan speed/

**Comment by smartHomeHub** [comment]
I'm afraid you can't integrate this remote to the component. It does not even have a discrete on/off button.
