### ISSUE TITLE
Climate. Add new Zanussi controller

### ISSUE THREAD

**Issue by Bratan9600** [smartHomeHub/SmartIR#374]
**Home Assistant version** 0.110.4

**SmartIR version** 1.12.0

**Additional context**

Configured with Broadlink RMC4_Mini
Codes for air conditioner Zanussi Fresco (remote controller ZH/TT-02)
[9999.txt](https://github.com/smartHomeHub/SmartIR/files/4737810/9999.txt)

**Comment by vassilis-panos** [comment]
Thanks for your contribution. Does the auto mode (heat_cool) have fixed temperature?

**Comment by Bratan9600** [comment]
Yes it does. 
Auto mode (heat_cool) and Dry mode works only at 25 degrees.
However auto mode have fan speed control, when dry mode doesnt have it
