### ISSUE TITLE
Missing ON button at Whirpool aircondition

### ISSUE THREAD

**Issue by kornelremete** [smartHomeHub/SmartIR#376]
Hi,

I use the latest version of smart IR with Broadlink mini RM3. It seems to work fine, but my climate needs also the ON button before starting operation. Can you help me please how to add it?
The rest of the IR codes I made it monually.

Thank you

**Comment by vassilis-panos** [comment]
I'm not sure if you need something like this, but you can send an on command every time before any mode / temperature change.
To achieve this you will create your file as follows:

```
{
  "manufacturer": "Toyotomi",
  "supportedModels": [
    "AKIRA GAN/GAG-A128 VL"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "minTemperature": 16,
  "maxTemperature": 30,
  "precision": 1,
  "operationModes": [
    "heat",
    "cool"
  ],
  "fanModes": [
    "low",
    "mid",
    "high",
    "auto"
  ],
  "commands": {
    "off": "....",
    "on": "....",
    "heat": {
      "low": {
        "16": "....."
```
