### ISSUE TITLE
json review - Daikin FT50FVM air conditioner

### ISSUE THREAD

**Issue by junknstuff** [smartHomeHub/SmartIR#380]
**Home Assistant version** HassOS 4.10

**SmartIR version** 1.12.0

**SmartIR configuration**

smartir:

switch:
  - platform: broadlink
    host: 192.168.72.6
    mac: '24:DF:XX:XX:XX:XX'
    type: rm4c_mini

climate:
  - platform: smartir
    name: aircon-jk
    unique_id: aircon-jk
    device_code: 8000
    controller_data: 192.168.72.6

**Describe the bug**

Not a bug but I am trying to create a json for my Daikin FT50FVM (it's an older model, almost 10 years old) using the template 1100.json

If I set the "device_code" to "1100" or any of the current Daikin codes, the correct LoveLace UI card auto populates and shows that it is Online, however, once I switch the "device_code" over to my custom one "8000" the LoveLace UI card shows "Unavailable"

[8000.txt](https://github.com/smartHomeHub/SmartIR/files/4759935/8000.txt)

**Comment by junknstuff** [comment]
that's a relief to hear - that's my first attempt at the code file! any suggestion where i should start troubleshooting? the Log Viewer add-on doesn't show any issues.

**Comment by vassilis-panos** [comment]
Are you sure the 8000.json is in the correct folder?

**Comment by junknstuff** [comment]
yes, i made a copy of the 1100.json file, renamed it to 8000.json and replaced the contents with what i shared above.

all codes are in SmartIR/codes/climate/

i did not revisit the problem yesterday but will give it another go tomorrow since you say the 8000.json is working for you. perhaps a full reboot of the hass.io VM would kick-start something :)

**Comment by junknstuff** [comment]
i found the issue - i had duplicated the code twice in the json file...doh! it's working now. i'll be adding the code in for all of the temp and fan settings.

advise on how to submit the json once it's complete?

**Comment by vassilis-panos** [comment]
You can submit your json here as a zip file or by opening a pull request. Thanks.
