### ISSUE TITLE
MQTT Media Player issue

### ISSUE THREAD

**Issue by robyevolution** [smartHomeHub/SmartIR#385]
**Home Assistant version:0.110.3

SmartIR version:Latest**

Hi I can't make smart ir media player mqtt work, i have an ir transmitter with tasmota-ir 8.3.1, when i send the ir codes it works perfectly, but when i try to send a code via smart ir it gives me json error in the tasmota console.
I used this json for the list of codes: https://emirefek.net/smarthome/samsungtvir/

the configuration is this:
  - platform: smartir
    name: Samsung TV
    unique_id: samsung_tv
    device_code: 1070
    controller_data: cmnd/tasmota_tuya_ir/IRsend
    power_sensor: binary_sensor.tv_power

the tasmota error is as follows:
stat/tasmota_tuya_ir/RESULT = {"IRSend":"Invalid JSON"}

Did I miss something in the configuration? How can I solve it?

**Comment by vassilis-panos** [comment]
Although this is not an issue but a support request, please attach the json file to see what happens.

**Comment by vassilis-panos** [comment]
Could you send me an example of how you send the command through the HA mqtt service?

**Comment by robyevolution** [comment]
with this script work:

  samsung_tv_off:
    sequence:
    - service: mqtt.publish
      data:
        topic: "cmnd/tasmota_tuya_ir/IRsend"
        payload: '{"Protocol":"SAMSUNG","Bits":32,"Data":"0xE0E040BF"}}'
        retain: false

**Comment by vassilis-panos** [comment]
Then please delete the IRsend from the json file

**Comment by robyevolution** [comment]
I had already tried to remove IRsend from the json but I forgot to remove the space too.
Thanks again
