### ISSUE TITLE
Support more fan command

### ISSUE THREAD

**Issue by dzungpv** [smartHomeHub/SmartIR#39]
My fan have light and have on/off command.
It also have 2 button 1 for reverse and 1 for natural win.
How it support by smart IR?
It is RF code but i think the same with IR

**Comment by smartHomeHub** [comment]
The light part is out of this component functionality. You must set it as a broadlink switch.
In order to make a device file that supports both directions, please see this example:
https://github.com/smartHomeHub/SmartIR/blob/master/smartir/codes/fan/1000.json

**Comment by dzungpv** [comment]
@smartHomeHub But on my RF remove, 6 speed fix code, 1 button for 
reverse. From the 1000.json, each direction has it own code and about natural win, i guest mus add to the code

**Comment by smartHomeHub** [comment]
Do the codes of each speed are different if you press the reverse button and then set the speed?

**Comment by dzungpv** [comment]
@smartHomeHub no it is the same code

**Comment by smartHomeHub** [comment]
This is not good. Is at least the direction command different each time you press the button?

**Comment by dzungpv** [comment]
It is the same everytime. Like on/off button of the TV. It toggle and handle by fan itself. All Chinese ceiling fan have this ability

**Comment by smartHomeHub** [comment]
I'm afraid you have to handle the direction from a script in Home Assistant. Use the component to turn on / off and adjust the speed of your fan.

**Comment by Avatar1976** [comment]
+1 here, reverse and "Ocean Breeze" (random changing fan speeds function built in to fan) are separate dedicated buttons, for now I have created my own json file and associated the reverse base64 codes to "oscillate".  Which works well enough for my use case if a little clunky UI wise.  If you could see your way clear to accomodate for a dedicated standalone-reverse function within the JSON (that works in conjunction with the default speeds) config it would sure help matters.  Ocean Breeze or natural a bit tougher and understandably so.

**Comment by Avatar1976** [comment]
Just in case someone comes across this, oscillate will not work either, SmartIR platform will transmit the forward reverse code with each speed change, hence I will need to create as suggested above a switch tied to transmitting the RF code for the forward reverse toggle. Ocean Breeze/natural wind as described above would be difficult but I think it best at speed 7 (my fan has 6 normal speeds).

**Comment by Avatar1976** [comment]
Confirmed Ocean Breeze/natural wind as speed 7 works, have it labelled as such in my Json file.
