### ISSUE TITLE
Climate Control/Broadlink: Failed to send packet: The device storage is full

### ISSUE THREAD

**Issue by digitalinksol** [smartHomeHub/SmartIR#391]
**Home Assistant version**
0.111.4

**SmartIR version**
1.12.0

**SmartIR configuration**

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
group: !include groups.yaml
automation: !include automations.yaml
#script: !include scripts.yaml
scene: !include scenes.yaml

bhyve:
  username: xxxxxx
  password: xxxxxx

switch: 
  - platform: bhyve
  - platform: broadlink
    host: 192.168.4.87
    mac: 'XX:XX:XX:XX:XX:XX'

smartir:
  check_updates: false

climate:
  - platform: smartir
    name: Living Room Climate Control
    unique_id: living_room_climate_control
    device_code: 1282
    controller_data: 192.168.4.87
    temperature_sensor: sensor.basement_motion_sensor_temperature

```

**Describe the bug**

Trying to use my Fujitsu climate control via a Broadlink RM mini 3 and am getting a "device storage is full" error in the logs. When using the same Broadlink using the native remote/send command, it functions properly.

**Debug log**


2020-06-20 14:00:18 ERROR (MainThread) [homeassistant.components.broadlink] Failed to send packet: The device storage is full

**Comment by smartHomeHub** [comment]
Not related to SmartIR but try to specify the device type for the broadlink switch.

**Comment by digitalinksol** [comment]
Thanks! That seemed to have fixed it.
