### ISSUE TITLE
Minor Typo in README

### ISSUE THREAD

**Issue by xiurobert** [smartHomeHub/SmartIR#393]
Just a minor typo in the README file: noticed that the player in media player was spelt wrongly.

**Comment by vassilis-panos** [comment]
I'm trying to find it. Can you tell me exactly where it is?

**Comment by alessio-papi** [comment]
Hi

the typo is in the overview section:

"SmartIR is a custom integration for controlling climate devices, media **palyers** and fans via infrared controllers."

Bye

**Comment by vassilis-panos** [comment]
Thanks
