### ISSUE TITLE
Hitachi RASDX18HDK

### ISSUE THREAD

**Issue by codyli2002hk** [smartHomeHub/SmartIR#395]
Home Assistant version
Home Assistant 0.111.4
SmartIR version
1.09.0
SmartIR configuration

smartir:
  check_updates: false

  - platform: xiaomi_miio
    name: "Living Room Remote"
    host: 192.168.86.27
    token: !token

  - platform: smartir
    name: Living Room AC
    unique_id: livingroom_ac
    device_code: 1082
    controller_data: remote.living_room_remote
    temperature_sensor: sensor.xiaomi_airpurifier_temp
    humidity_sensor: sensor.humidity_158d0002454ad8

**Describe the bug**

No any action when on  off
**Debug log**

```text

Traceback (most recent call last):
  File "/home/homeassistant/.homeassistant/custom_components/smartir/climate.py", line 334, in send_command
    await self._controller.send(command)
  File "/home/homeassistant/.homeassistant/custom_components/smartir/controller.py", line 87, in send
    'broadlink', 'send', service_data)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/core.py", line 1219, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service broadlink/send
```

**Comment by smartHomeHub** [comment]
You are trying to use a file for broadlink controller

**Comment by codyli2002hk** [comment]
How to change the file to xiaomi_miio controller ?  

Thank you

**Comment by vassilis-panos** [comment]
As far as I know you can't. There is no script that can do the conversion

**Comment by codyli2002hk** [comment]
Thank you for your support and Nice job!
