### ISSUE TITLE
Certain commands sent multiple times

### ISSUE THREAD

**Issue by nicxvan** [smartHomeHub/SmartIR#397]
Certain commands get sent multiple times with smart IR. I have two pioneer ac's

For example:
The cool function command will get sent twice
The power command gets sent once
I added the led command (outside smart ir) and it gets sent half a dozen times.

This behavior occurs with both built in scripts with the tv using the broadlink send service as well as smart ir.

I mentioned Smart IR because it is more reproducible, but it also happens with the tv volume, you press the volume script once and broadlink sends the packet half a dozen times. You are trying to reduce the volume by one or two and it just keeps going down.

I use broadlink with smart ir and some scripts to control my tv.

Starting about a week ago it began sending multiple packets when 

## Environment
I'm using docker on a nuc

107 - 111 ( I updated after experiencing the issue and it continues to happen)
107
docker
Smart IR

## Problem-relevant `configuration.yaml`
```
- platform: smartir
  name: Bedroom AC
  unique_id: office_ac
  device_code: 2040
  controller_data: <IPADDRESS>
  temperature_sensor: sensor.bedroom_temperature
- platform: smartir
  name: Living AC
  unique_id: living_ac
  device_code: 2040
  controller_data: <IPADDRESS>
  temperature_sensor: sensor.upstairs_temperature
- platform: broadlink
  host: <IPADDRESS>
  mac: '<MACADDRESS>'
  type: rm2_pro_plus
- platform: broadlink
  host: <IPADDRESS>
  mac: '<MACADDRESS>'
  type: rm2_pro_plus
```

## Traceback/Error logs
None that I can find

**Comment by nicxvan** [comment]
Cross posted: https://github.com/home-assistant/core/issues/37000

**Comment by vassilis-panos** [comment]
I close it. Not related to SmartIR
