### ISSUE TITLE
cooper&hunter ch-s09xn7 ?

### ISSUE THREAD

**Issue by itpcss** [smartHomeHub/SmartIR#398]
Please add codes for air conditioners cooper & hunter ch-s09xn7, or write please how to create and add your json with codes, I can read codes using broadlink rm4 pro.
This model's air conditioner is not on your list.

**Comment by vassilis-panos** [comment]
There are many ways. You will find some of them in the forums.
You can also try the following app
[BroadlinkIRTools](https://keitetran.github.io/BroadlinkIRTools/
