### ISSUE TITLE
Some AC not working 

### ISSUE THREAD

**Issue by keitetran** [smartHomeHub/SmartIR#4]
My AC alway press ON button then get last state or change other state temp, swing, wind.... 
But this component dont send ON command first. I can not ON AC.
How to sloved that ?

**Comment by smartHomeHub** [comment]
Hi, is this the same issue #1

**Comment by keitetran** [comment]
Thank bro, i was re-created my IR code for SHARP AY-B22DM at 1300.json.
I will create new pull request. Please check it. 
Thank you verry verry much :D

**Comment by smartHomeHub** [comment]
Are you the creator of the old sharp INI file?

**Comment by smartHomeHub** [comment]
Yes, you are. How did you turn your AC on until now?

**Comment by keitetran** [comment]
Yes. I was create it. But i dont want convert it because it not wok fine. 
ah, a code a small tool by javascript to learn command faster. If you dont have time or cant finish that tool. I will code it and create new pull request. Then you can set it as project page on Github. It is a html page only. I use websocket of hass.

**Comment by smartHomeHub** [comment]
Please join the telegram chat to discuss later on this tool.
Man, thanks again. I really appreciate your help. It was a difficult task. I'll mention you on the supported devices list.

**Comment by keitetran** [comment]
OK, my AC work fine. Thank you :D
