### ISSUE TITLE
New codes for Samsung TVs (media player)

### ISSUE THREAD

**Issue by alessio-papi** [smartHomeHub/SmartIR#400]
**Home Assistant version**

Home Assistant 0.111.4

**SmartIR version**

SmartIR 1.22.0

Hi,

the JSON file contains codes for the following Samsung TVs:

      UE40C6000
      UE40D6500
      UE32H5500
      UE22D5000

No suggestion on the code to use to identify the file.

Best regards
Alessio

[Samsung.zip](https://github.com/smartHomeHub/SmartIR/files/4824424/Samsung.zip)

**Comment by vassilis-panos** [comment]
Thanks a lot!
