### ISSUE TITLE
Hitachi air conditioner RASDX18HDK 

### ISSUE THREAD

**Issue by codyli2002hk** [smartHomeHub/SmartIR#401]
**Home Assistant version**

Home Assistant 0.111.4

**SmartIR version**

version 1.12.0

Hi, This is an awesome add-on, great work!!

I export a hitachi climate file from HA using Xiaomi remote. How to check the RAW code OK? and contribute to this project?
The json file for Hitachi air conditioner RASDX18HDK 

Thank you,

Cody

[hitachi.json.zip](https://github.com/smartHomeHub/SmartIR/files/4826418/hitachi.json.zip)

**Comment by vassilis-panos** [comment]
I don't understand what you mean by "How to check the RAW code OK?" Does the file work for you?

**Comment by codyli2002hk** [comment]
I use xiaomi_miio.remote_learn_command to learn hitachi remote every buttons and copy to hitachi.json file.  How to test hitachi.json using in HA?
