### ISSUE TITLE
General air conditioner ASWX09LECA

### ISSUE THREAD

**Issue by codyli2002hk** [smartHomeHub/SmartIR#402]
**Home Assistant version**

Home Assistant 0.111.4

**SmartIR version**

version 1.12.0

Hi, 

I export a general climate file from HA using Broadlink remote. and contribute to this project?
The json file for General air conditioner ASWX09LECA 

[general.json.zip](https://github.com/smartHomeHub/SmartIR/files/4832841/general.json.zip)

Thank you,

Cody

**Comment by vassilis-panos** [comment]
Thanks for your contribution. Be aware that there is an error on line 15. It is fixed. The file code is 1043.
