### ISSUE TITLE
Samsung UE40H7000SL works

### ISSUE THREAD

**Issue by zbeez** [smartHomeHub/SmartIR#406]
Hello,

just want to say that my Samsung TV UE40H7000SL works with the SmartIR Media Player platform through my Broadlink RM2 Pro+.
Configuration is as described and the media code is 1060:

Code | Supported Models | Controller
1060 | UE40F6500LE40D550UE40H6400 | Broadlink

You can surely add the TV model, because everything works. Even switching through the inputs is working!

Thank you for the work!

**Comment by vassilis-panos** [comment]
Thanks!
