### ISSUE TITLE
Xiaomi v2 learn code

### ISSUE THREAD

**Issue by Omirax** [smartHomeHub/SmartIR#408]
Hello! 

Perfect work!

_"If your device is not working, you will need to learn your own codes..."_

How I can learn Airwell/Gree AC code for xiaomi RF (v2)?
If we start learning in HA, we get a new code for the “off button” every time.

Maybe there is a way to convert data between broadlink and xiaomi v2?

Best Regards,

**Comment by vassilis-panos** [comment]
I can't help you with that. Maybe you can find help in the forums
