### ISSUE TITLE
No OFF command for AC 

### ISSUE THREAD

**Issue by az911** [smartHomeHub/SmartIR#41]
Hi, first of all - thanks for a great addition to HA.
I have a very big problem - my AC doesn't have "off" command, the off command is merely repeating the specific on command. So the widget can not close the AC and a rather complex (at least for me) script is to be used to turn the AC off.
Your help would be highly appreciated.

**Comment by smartHomeHub** [comment]
Hi,
What is the complex script that you use to turn off your ac?

**Comment by az911** [comment]
I wish I had it LOL - theoretically, the script should "open" the AC again in an rarely used mode (for me it could be vent mode, 30 degrees, high fan), wait 4 seconds and then send the same code again (i.e., vent mode, 30 degrees, high fan). 
I thing that the best solution would be an option in your code that would just send the "on" command again instead of looking in the json file for an "off" command. Example (as I'm not sure I'm coherent enough) - if I open the AC with a "heat mode, 25 degrees, low fan" then when off'ing the AC it should just repeat the command "heat mode, 25 degrees, low fan".

**Comment by smartHomeHub** [comment]
I can't believe this. What is the manufacturer of your unit?

**Comment by az911** [comment]
They are of Israeli brands "Electra" (ACs are not very new, I think 4-5 years) and a "Belkor" old AC (more then 10 years but works very good).

**Comment by az911** [comment]
The remotes are labeled : RC08B (electra)
RC3  (electra)
ZM 9100 (belkor)

**Comment by az911** [comment]
RC08B- https://www.ebay.com/itm/New-For-Airwell-Electra-GREE-RC08A-RC08B-AC-A-C-Air-Conditioner-Remote-Control/123496080495?hash=item1cc0f0a46f:m:mRi-Vc2iC410UR1xFSnr0VQ:rk:1:pf:0

RC3- https://www.ebay.com/itm/Air-Conditioner-Remote-Control-For-Airwell-Emailair-Electra-RC-3-RC-4-RC-7-WMZ/272584205465?_trkparms=aid%3D111001%26algo%3DREC.SEED%26ao%3D1%26asc%3D20160908105057%26meid%3Dac478fccaba8441d8cf6759e2e12292b%26pid%3D100675%26rk%3D1%26rkt%3D15%26mehot%3Dpp%26sd%3D272584205465%26itm%3D272584205465&_trksid=p2481888.c100675.m4236&_trkparms=pageci%3Ae2405a2e-3c7c-11e9-a8cc-74dbd1800b64%7Cparentrq%3A3bab2e221690a9cba727bb85ffde2c9d%7Ciid%3A1

**Comment by az911** [comment]
Cant find the last one on Ebay - http://harel-ac.co.il/?product=%D7%A9%D7%9C%D7%98-%D7%91%D7%9C%D7%A7%D7%95%D7%A8-zm-9100

**Comment by smartHomeHub** [comment]
Assume that you set your unit to 20 degrees/heat. Then you set the temp to 21 but your remote not point the unit. Then you decide to turn off your device. What is the behavior of your device?

**Comment by az911** [comment]
Never tried it so I now checked 3 of them -  they turned off when I do that.

**Comment by smartHomeHub** [comment]
Please double check if the code you get if you turn on or off your device, without change the temp, mode etc is exactly the same. I'm sorry to insist, but Ι hear something like this for the first time

**Comment by smartHomeHub** [comment]
By the above experiment, it seems that your unit doesn’t turn off if receives the same command. The state of the remote control was different from the state of the unit.

**Comment by az911** [comment]
These are 6 codes I recorded now, one immediately after the other, WITHOUT changing anything (heat, 23, low), the remote is RC3. Starting position was AC OFF, so the first one would have turned the AC on:

JgC+AGKEPkE/Ih4hHyIeIR8hHyEfIR9BPyIeIR8iHiEfIR8iHyAgIB8hHyIeIh4iHiEfIh4iHiEfIR8hHyEfQT8iYIM/QT8hHyIeIh4iHiEfIh4hH0E/IR8hHyEfIR8iHiEfIR8hHyEfIR8hHyEfIR8iHiEfIR8hHyIeIh5BPyFhgz9BPyMeIR4iHiIeIR8iHyEfQT8iHiIeIR8hHyEfIh4hHyEfIh4iHiEfIh4iHiEfIR8hHyEfIR8hH0I+IYEADQUAAAAAAAAAAAAA

JgC+AGKDP0E/Ih4hHyIeIR8hHyEfIR9BPyIeIR8iHiEfIR8iHiEfIR8hHyIeIh4iHiEfIh4iHiEfIR8hHyEfQT8iYIM/QT8hHyIeIh4iHiIfIR4hH0E/Ih4iHyEfIR8iHiEfIR8hHyEfIR8hHyEfIR8iHiEfIR8hHyIeIh5BPyFhgz9BPyIeIh4hHyEfIR8hHyEfQT8iHiIeIR8hHyEfIh4hHyIeIh4iHiEfIh4iHiEfIR8hHyEfIR8hH0I+IYEADQUAAAAAAAAAAAAA

JgC+AGKDQEE+Ih8hHyEeIR8hHyIfIh5CPiEfIR8iHiEfIh4hHyEfIR8hHyIeIR8hHyEgIB8hHyEfIh4hHyIeQUAgYYQ+Qj4hHyEfIR8hHyEfIR8iHkE/IR8iHiEfIR8hHyIfIB8hHyIeIR8hHyEfIR8hHyIeIR8iHiIeIR9BPyFhhD5BPyEfIR8iHiEfIR8hHyIeQT8hHyEfIh4hHyEfIh4hHyEfIh8hHyEfIR8iHiEeIh8iHiEfIR4iH0E/IYEADQUAAAAAAAAAAAAA

JgC+AGOEPkA/IR8hHyIfIR8iHiEfIR9AQCEfIh4hHyIeIR8hHyIeIR8hHyEfIR8hICAfIR8hHyIeIR8iHiEfQT8iYIM/QUAgHyEfIR8iHyAfIR8hH0I+IR8hICAfIR8iHiIeIR8hHyEfIR8hHyEfIR8iHiIeIR8iHiEfIR9BPyFhhD5CPiEfIh4iHiEfIh4iHiEfQT8iHyEeIR8jHSIfIR4hHyEfIR8iHyAfIR8iHyIeIR8iHiEfIR8hH0E/IoAADQUAAAAAAAAAAAAA

JgC+AGWDP0E/IR8iHiIeIR8hHyEfIR9CPiEfIR8iHiEfIR8hHyEgIB8hHyIeIh4iHiEfIh8gHyEfIR8iHiIfQT4hYYM/Qj4hHyEfIR8hHyEgIR4hH0E/IR8iHiEgIB8hHyIeIR8hHyIeIh4iHiEfIh4iHyIeIB8iHyIeIR5BPyJhgz9BPyEfIR8iHiEfIh4iHiIfQD8hHyEfIR8hHyEfIR8hHyIeIh4hHyEfIR8iHiIeIR8iHiEfIR8hH0E/IoEADQUAAAAAAAAAAAAA

JgC+AGODPkE/IR8hHyIfIh4iHiEfIh5BPyEfIR8hHyIeIR8iHiIeIR8iHiEfIR8hHyEfIR8iHiIeIR8iHiEfQT8iYIM/QT8hHyEfIR8hHyEfIR8hH0I+IR8hHyEfIh4hHyIeIR8hICAfIR8hHyEfIR8hHyIeIR8iHiEfIR9BPyFhgz9BPyIeIR8hICAgIB8hHyIeQj8iHiIeIR8gHyEfIh8gHyIfIR8iHiEfIR8hHyEfIh4iHiEfIR8hH0I+IYEADQUAAAAAAAAAAAAA

**Comment by az911** [comment]
WELL! I choose one of the "off" codes above and entered it into the json file - and it worked! I will do some more testing tomorrow :)

**Comment by smartHomeHub** [comment]
Please send me your result tomorrow. I'm very interested.

**Comment by az911** [comment]
Well... it works on all 4 ACs HAHA :) thanks a lot, if you wouldn't mention that I would probably wouldn't have tried it :)

On the technical aspect - when the ACs are on, ANY command sent using the power button will shut them off. Moving from heat to cool (or the other way) confuses the thermostat card (I don't know if its from your code or the card's code) and the card show the AC is off although the power sensor show it is on. There is the same problem when the IR code isn't "catched" by the AC. But those are really minor issues that are not problematic to day to day use. 

So, thanks again for this! :)

**Comment by AlmogBaku** [comment]
hey guys, can you share with me your json for the RC-3?

**Comment by mbrevda** [comment]
> hey guys, can you share with me your json for the RC-3?

Would be great if you can share?

**Comment by AlmogBaku** [comment]
> > hey guys, can you share with me your json for the RC-3?
> 
> Would be great if you can share?

You should use device code 1940
