### ISSUE TITLE
CLimate using fan only without temperature dry without temperature and timer

### ISSUE THREAD

**Issue by antoweb** [smartHomeHub/SmartIR#410]
**Home Assistant version**
0.112.2
**SmartIR version**
1.12.0
**SmartIR configuration**
  - platform: smartir
    name: Kelon
    device_code: 7000
    controller_data: 192.168.1.86
    temperature_sensor: sensor.temperature
    humidity_sensor: sensor.humidity
    power_sensor: binary_sensor.stato_accensione
```yaml

Add configuration here

```

**Describe the bug**

I want to know if is possible to use the timer function with auto off, and the dry and fan only modes in my air conditioner work only with fan speed and not with temperature values, how to insert this codes in json?

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by vassilis-panos** [comment]
For the fan and dry mode you need to repeat the code for every temperature.

**Comment by antoweb** [comment]
Ok many thanks
