### ISSUE TITLE
Daikin remote AC466A9 - units FTXS XX K2V

### ISSUE THREAD

**Issue by tigers75** [smartHomeHub/SmartIR#413]
**Home Assistant version**
0.112.1

**SmartIR version**

1.12.0

**SmartIR configuration**

Not relevant.

```yaml

Add configuration here

```

**Describe the bug**

Not a bug: just made a file for Daikin AC466A9 remote and wanted to contribute

**Debug log**
not relevant

```text

Add your logs here.

```

**Additional context**

I made a file for the basic functions of another Daikin remote and wanted to contribute.
I figured it'd be a good thing to name the config file not only after the A/C model but also on the remote model.

Some notes:
I am aware that the file is far from complete: I only did the basic functions (heat/cool/auto) with Auto fan speed, and the power mode codes are copy-pasted from the "auto" mode even if you select heat or cool.
I did not capture swing, low power consumption and night mode; may do them later if I keep using it with HA.

Here's the file:
[1110.txt](https://github.com/smartHomeHub/SmartIR/files/4893499/1110.txt)

EDIT: fixed typos and tried to explain better what is still missing.

**Comment by vassilis-panos** [comment]
Are you planning to complete the file?

**Comment by tigers75** [comment]
I think I will, but haven't decided what to implement, there are A LOT of functions missing (apart from the scheduling options that are nonsense for a HA implementation) there are:
- night mode, for auto, cool, heat modes;
- vertical swing for the 3 modes + power mode;
- horizontal swing (the same: 4 modes);
- energy saving mode for any of the possible combinations above plus the ones that are in the file.

I certainly am NOT making them all, may implement the swings.

**Comment by tigers75** [comment]
It's fine for me, but I see it has not been added to the list. I wanted to improve it with at least the swing modes but summer has not been very hot, so I haven't used it much.
I'd add it to the repository, so maybe someone will add other modes.
Thanks for the great code.
