### ISSUE TITLE
Climate: Mitsubishi Electric - MSZ-HJ35VA

### ISSUE THREAD

**Issue by ToRvaLDz** [smartHomeHub/SmartIR#415]
Home Assistant version

Home Assistant 0.112.4

SmartIR version

version 1.12.0

Json file for climate Mitsubishi Electric - MSZ-HJ35VA

[1128.zip](https://github.com/smartHomeHub/SmartIR/files/4906888/1128.zip)

Thank you

**Comment by vassilis-panos** [comment]
Thanks for your contribution. Really appreciate it!

**Comment by ee02217** [comment]
By any chance can you control the vertical tilt swing mode?
