### ISSUE TITLE
Climate: Flouu. ( A Gree system)

### ISSUE THREAD

**Issue by alfonsolsl** [smartHomeHub/SmartIR#420]
Codes to "Flouu" A/C by Gree

**Additional context**

[flouu.txt](https://github.com/smartHomeHub/SmartIR/files/4916750/flouu.txt)

the tool doesn't let me add the swing commands and the special buttons like: health.

**Comment by vassilis-panos** [comment]
Thanks for your contribution. Is it Flouu or Fluo?

**Comment by alfonsolsl** [comment]
Hello, it's "Flouu" i guess a budget brand by Gree.

**Comment by vassilis-panos** [comment]
Does the sun mode means heat mode?

**Comment by alfonsolsl** [comment]
That's a good question.

We lives in the Caribbean so I guess heat should not be a option in this equipment, when is active is still cool.

In the remote the icon is a Sun. By default the temp sets on 28°C, maybe a defrost/heat option.

The remote has another mode but I don't know what it does, maybe with your expertise can figure what the icon means. The icon is like a fan but unlike the fan only option this allow temp adjustment.

I didn't learn the codes for this last mode.
![15948211184957055471579585470093](https://user-images.githubusercontent.com/6255385/87553404-851f0800-c678-11ea-99c2-95744ff4e2d9.jpg)
![15948211555524069433585662135323](https://user-images.githubusercontent.com/6255385/87553458-90723380-c678-11ea-908c-5b1cb16852b9.jpg)
