### ISSUE TITLE
Add TV Silver

### ISSUE THREAD

**Issue by ricard0g0mes** [smartHomeHub/SmartIR#421]
I don't know how to send this any other way so...
I just want to give my help sending my own file for the Silver TV.
I've made it using (https://keitetran.github.io/BroadlinkIRTools/dist/#/).

I don't know the model but i beleive it should work with all Silver models
Link to the TV: https://loja.meo.pt/Equipamentos/tv/Silver/TV-Silver-Led-32-495523?cor=Preto&modo-compra=PromptPayment&search=MontraLoja

http://ricardogomes.eu/3001.json

**Comment by vassilis-panos** [comment]
Thanks!
