### ISSUE TITLE
Climate: Hitachi - RASDX18HDK

### ISSUE THREAD

**Issue by codyli2002hk** [smartHomeHub/SmartIR#426]
Home Assistant version

Home Assistant 0.111.4

SmartIR version

version 1.12.0

Json file for climate Hitachi - RASDX18HDK
[RASDX18HDK.json.zip](https://github.com/smartHomeHub/SmartIR/files/4977640/RASDX18HDK.json.zip)

Thank you

**Comment by codyli2002hk** [comment]
update supportedModels
[RASDX18HDK.json.zip](https://github.com/smartHomeHub/SmartIR/files/4974865/RASDX18HDK.json.zip)

**Comment by codyli2002hk** [comment]
update off command
[RASDX18HDK.json.zip](https://github.com/smartHomeHub/SmartIR/files/4974963/RASDX18HDK.json.zip)

**Comment by vassilis-panos** [comment]
Great work. Thanks
