### ISSUE TITLE
CLIMATE: DAIKIN ATX20J2V1B - ATX25J2V1B - ATX35J2V1B json conf file

### ISSUE THREAD

**Issue by Petengy** [smartHomeHub/SmartIR#427]
Hi to all

Here my json file for Daikin conditioners:

[1106.zip](https://github.com/smartHomeHub/SmartIR/files/4975877/1106.zip)

Compatible models: 

ATX20J2V1B
ATX25J2V1B
ATX35J2V1B

**Home Assistant version** : 0.113.1

**SmartIR version**: 1.12.0

Additional info request:
I noticed that sometimes it is necessary to send the command 2 or 3 times before the splitter detects it (it is as if the duration of sending the signal was too short).
Is there a way to increase the signal sending duration in the "climate" module? Or, if not so, would it be possible to add this function in future versions?

**Comment by vassilis-panos** [comment]
Thanks for the great work.
At some point I will add support for the broadlink remote component which supports number of repeats.
https://www.home-assistant.io/integrations/broadlink/#send-command
