### ISSUE TITLE
Fujitsu Aircon Remote AR-JW11

### ISSUE THREAD

**Issue by brent0np** [smartHomeHub/SmartIR#43]
Hi, thanks for the great work on SmartIR.  I have a question; my aircon has different minimum temps dependant on the setting.  As an example, the lowest the remote goes to on the heat setting is 16, but when set to cool it will only go to 18.  There are similar issues at high temps.

I have attached the INI file and have had it working with broadlink for some time under the older model, I just want to understand how to handle this in the file.
[fujitsu ar-jw11.zip](https://github.com/smartHomeHub/SmartIR/files/2922075/fujitsu.ar-jw11.zip)

**Comment by smartHomeHub** [comment]
Hi, how did you handle it from the old component?

**Comment by brent0np** [comment]
I have only used cooling so far as its peak summer here

**Comment by smartHomeHub** [comment]
The code 1281 seems compatible with your unit. Could you set the device_code: 1281 and restart HA (the component will download the file at startup)?
Please let me know if this file works with your unit.

**Comment by brent0np** [comment]
Hi, the 1281 codes appear different (and when tested didn't work).  I then saved over the 1281.json file with my converted JSON file and it worked as expected.  It seems my codes are fine, its just the different high/low temps between settings.

**Comment by smartHomeHub** [comment]
The HA climate platform is not able to use different temperature ranges between modes. 
The solution to this situation is to delete the 16 and 17 records from heat mode or add 16 and 17 records to the other modes using the same command as 18.

**Comment by brent0np** [comment]
Ok understood - thanks for the insight. I will submit the code soon
