### ISSUE TITLE
Failed to send packet: The device storage is full

### ISSUE THREAD

**Issue by trannamhung** [smartHomeHub/SmartIR#433]
**Home Assistant version** 

Home Assistant 0.113.1

**SmartIR version**

latest release

**SmartIR configuration**

smartir:
switch:
  - platform: broadlink
    host: 192.168.1.4
    mac: '24:df:a7:4f:d4:61'
fan:
  - platform: smartir
    name: Master Fan
    unique_id: master_fan
    device_code: 9999
    controller_data: 192.168.1.4
    power_sensor: sensor.sonoff_1000bda2d9_power

Add configuration here

{
  "manufacturer": "Panasonic",
  "supportedModels": [
    "Unknown"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "speed": [
    "low",
    "medium",
    "high"
  ],
  "commands": {
    "on": "JgBsAG10HFccWBwdHFgbWRtXHB4cHhwdHB4cHhtYHB4cHhtYGx4cHhweG1gcVxxYG1gcVxweHAAFBnN0HFccWBseHFgbWBxXHB4cHhseHB4cHhtYHB4bHhxYGx4cHhweG1gcVxxYG1gcVxweHAANBQAAAAAAAAAAAAAAAA==",
    "off": "JgCiAG5zHFccVxweHFccWBxXHB4cHRweHB4cHRxYHB0cHhxXHB4cHhwdHFgcVxxXHFgcVxweHAAFBnNzHFgbWBweHFccVxxYGx4cHhweGx4cHhxXHB4cHhtYHB4bHhweHFccVxxYHFccVxweHAAFBnRzHFccWBwdHFgcVxxXHB4cHhwdHB4cHhxXHB4cHRxYHB4bHhweHFccWBtYHFccVxweHAANBQAAAAAAAA==",
    "default": {
      "low": "JgBsAHJ0HVYdVxwdHFgbWBxXHVccVxxXHFcdVxseHB4cHhtYHB4bHhweHB4bHhweHB0dHRxXHAAFBnRzHFccWBwdHVYdVxxXHFccWBxXHFccWBseHB4cHhtYHB4bHhweHB4bHhweHB4bHhxYGwANBQAAAAAAAAAAAAA=",
      "medium": "JgBsAHJ0HVYdVxwdHFgbWBxXHVccVxxXHFcdVxseHB4cHhtYHB4bHhweHB4bHhweHB0dHRxXHAAFBnRzHFccWBwdHVYdVxxXHFccWBxXHFccWBseHB4cHhtYHB4bHhweHB4bHhweHB4bHhxYGwANBQAAAAAAAAAAAAA=",
      "high": "JgBsAHJ0HVYdVxwdHFgbWBxXHVccVxxXHFcdVxseHB4cHhtYHB4bHhweHB4bHhweHB0dHRxXHAAFBnRzHFccWBwdHVYdVxxXHFccWBxXHFccWBseHB4cHhtYHB4bHhweHB4bHhweHB4bHhxYGwANBQAAAAAAAAAAAAA="
    },
    "oscillate": "JgBsAHRzHFccVxweHFccVxxYHFcdHRtYHFcdVxseHB4cHhxXHB4bHh0dHB4bWBweGx4dHRxXHAAFBnRzHFccWBwdHVcbWBxXHFgbHhxXHFgcVxweGx4cHhxXHB4cHhseHB4cVxweGx4cHhxXHAANBQAAAAAAAAAAAAA=",
	"timer": "JgA2AHRzHFccVxweHFccWBtYHB0cWBxXHFccWBwdHB4cHhtYHB4cHRweHFccHhseHB4cHhtYHAANBQ=="
  }
}

**Describe the bug**

After adding a fan, I try to turn it on/ off but I get the below error.

**Debug log**

 ERROR (MainThread) [homeassistant.components.broadlink] Failed to send packet: The device storage is full

Add your logs here.

 ERROR (MainThread) [homeassistant.components.broadlink] Failed to send packet: The device storage is full

**Additional context**

**Comment by vassilis-panos** [comment]
Please see  #425
