### ISSUE TITLE
Updated 1284.json

### ISSUE THREAD

**Issue by alexjonclement** [smartHomeHub/SmartIR#438]
I am the original author of 1284.json for the Fujitsu AR-REG1U remote.

Fixed two major issues:

Corrected all entries for Cool/Auto
Corrected heat/low/26

Verified every output with Broadlink RM33 Pro+ via Home Assistant 0.113.1. 

Original codes captured with RM Mini3 (about a year ago).

[1284-v0.1.2.json.zip](https://github.com/smartHomeHub/SmartIR/files/5011461/1284-v0.1.2.json.zip)

**Comment by vassilis-panos** [comment]
Great work. Thanks.
