### ISSUE TITLE
Media Player ping host

### ISSUE THREAD

**Issue by pdeelen** [smartHomeHub/SmartIR#45]
Hi, 

Thanks for the component. 
In the older version there was an option ping_host.

Is it possible to implement it also to this version?

**Comment by smartHomeHub** [comment]
Hi,
[Already discussed in forums](https://community.home-assistant.io/t/smartir-control-your-climate-tv-and-fan-devices-via-ir-rf-controllers/100798/14?u=vassilis)

**Comment by pdeelen** [comment]
Thanks, i will give it a try!
