### ISSUE TITLE
Xiaomi MiTv

### ISSUE THREAD

**Issue by lakshinskij** [smartHomeHub/SmartIR#464]
Hi guys. I have a TV from Xiaomi. I also have a Broadlink Rm mini 3. My TV is perfectly controlled from the native Intelligent Home Center application. I took a set of codes from the base of this application. There is no Xiaomi TV in the Media Player SmartIR integration database (((
Please tell me if I can somehow transfer this set of codes to the SmartIR integration. I really want to control my TV from the Home Assistant.
Best regards, Dmitry.

**Comment by iMadGera** [comment]
do u found the codes man? thx

**Comment by lakshinskij** [comment]
unfortunately not found.  nobody supported (((

вс, 27 сент. 2020 г., 20:17 iMadGera <notifications@github.com>:
