### ISSUE TITLE
I've got a airco with on and off commando's How do i use this?

### ISSUE THREAD

**Issue by Acetyld** [smartHomeHub/SmartIR#473]
Im running every new version ^_^
"off":
"on": Like this?

**Comment by saucedge** [comment]
It seems like this is my issue too.  If I manually turn the unit on, I can control temp, switch modes, and turn the unit off with SmartIR.  But if the unit is off, none of the sent commands turn the unit on first.

**Comment by smartHomeHub** [comment]
What is your AC model?

**Comment by saucedge** [comment]
> What is your AC model?

The remote is Fujitsu AR-REY1U, and they unit on the wall is Fujitsu ASUG09LMAS.

**Comment by smartHomeHub** [comment]
Did you capture your own commands or use one of the ready json files?

**Comment by smartHomeHub** [comment]
Please make the following test. Turn off your AC unit from the remote. Hide the remote ir len and press the on button. Your unit should remain to off. Now point the unit with the remote and change the temperature. Did the AC turned on?

**Comment by saucedge** [comment]
> Please make the following test. Turn off your AC unit from the remote. Hide the remote ir len and press the on button. Your unit should remain to off. Now point the unit with the remote and change the temperature. Did the AC turned on?

Smart suggestion!  When the unit is off and the remote thinks it is on, none of the temperature commands turn on the unit.  I did capture the codes manually.

**Comment by smartHomeHub** [comment]
Please capture an on command and add it under the off line.
"off" : ".. ",
"on" : "..."

**Comment by saucedge** [comment]
That worked!  It now seems to send the ON command before every other command... so the unit beeps twice on a temp change, for example.  But the outcome is the same as the remote, so I'm happy.  Thanks a lot for the help!
