### ISSUE TITLE
Broken in HA 0.115 beta

### ISSUE THREAD

**Issue by sweebee** [smartHomeHub/SmartIR#476]
**Home Assistant version**
0.115.0b2

**SmartIR version**
1.12.0

**SmartIR configuration**

```yaml
smartir:
```

**Describe the bug**

Latest beta of home assistant uses GUI integration for Broadlink. So the 'switch' option is gone for Broadlink. SmartIR uses the ```switch``` to control my Airconditioning, but since the switch is gone it doesn't work anymore.

**Comment by smartHomeHub** [comment]
#475
