### ISSUE TITLE
 Sequence of commands not working with broadlink on 115.1 

### ISSUE THREAD

**Issue by Madseason41** [smartHomeHub/SmartIR#481]
HA 115.1
SmartIR 13.1

Since I can not directly select sources on my dumb TV's, i use a sequence of commands to change to the next source and label the sources "next" and "previous".

As far as I can tell this doesn't work since updating.

Other features work fine.

Homeassistant Log:

Logger: custom_components.smartir.media_player
Source: custom_components/smartir/controller.py:98
Integration: SmartIR (documentation)
First occurred: 2:33:11 PM (1 occurrences)
Last logged: 2:33:11 PM
can only concatenate str (not "list") to str

Traceback (most recent call last):
  File "/config/custom_components/smartir/media_player.py", line 267, in send_command
    await self._controller.send(command)
  File "/config/custom_components/smartir/controller.py", line 98, in send
    'command':  'b64:' + command
TypeError: can only concatenate str (not "list") to str

The sources are setup like channel 10 and 11 on code file 1200, with the exception being 3 commands instead of 2.

This worked fine on 114. I have 3 broadlink rm mini 3's and one rmpro2, all of which provide the same error when trying to change the source.

**Comment by smartHomeHub** [comment]
I am able to reproduce it. I will fix it as soon as possible

**Comment by vassilis-panos** [comment]
Could you try to update to 1.13.2?

**Comment by Madseason41** [comment]
Worked with the rmpro2. Will try the mini’s after the kids get up.

Thanks!
