### ISSUE TITLE
Widget broken in Hebrew

### ISSUE THREAD

**Issue by eladzazon** [smartHomeHub/SmartIR#484]
Hi, latest version of home assistant and smartir

The widget shows 26.2 c
But the design is broken 

Language: Hebrew
Text-direction: RTL
![Screenshot_20200919-195252](https://user-images.githubusercontent.com/441114/93672260-2cbe1980-fab2-11ea-87e8-8df5c0756d46.png)

**Comment by smartHomeHub** [comment]
SmartIR has nothing to do with the front end
