### ISSUE TITLE
Add support for Fan Light

### ISSUE THREAD

**Issue by VirtualL** [smartHomeHub/SmartIR#486]
**Home Assistant version** 0.115.1

**SmartIR version** 1.13.2

**Describe the feature**

I have a Fan that works great with SmaetIR
but the fan also has a light button in the remote (controlled via BroadLink IR as the other buttons (fan speed:L,M,H)
It's will be awesome to add this into the set of SmatIR

**Comment by smartHomeHub** [comment]
Sorry, HA fan card does not support light.
