### ISSUE TITLE
Electrolux QE09F not fully compatible

### ISSUE THREAD

**Issue by tenkaibr** [smartHomeHub/SmartIR#504]
I have an Electrolux QE09F air conditioner but some codes works but not others. For example, the power button does not work, it just turns off. Another issue is that the device has different functions. For example, mine has an ECO function but does not have a HEAT function. How can I make these changes? I can make the codes available if its need

Edit: In fact the codes of the HEAT function are the codes of the ECO function. How do I change names and icons?

Edit2: there is also a function called oscillate that is not in the codes

**Comment by vassilis-panos** [comment]
Device code is 1702?

**Comment by tenkaibr** [comment]
> Is device code 1702?

Yeap
