### ISSUE TITLE
Add Play, Pause and Stop to Media Player

### ISSUE THREAD

**Issue by AlfredoCABA** [smartHomeHub/SmartIR#51]
I was able to add play, pause, stop and more to the obsolete media player:
[custom_components/broadlink/media_player.py](https://github.com/AlfredoCABA/Home-Assistant-Config/blob/master/custom_components/broadlink/media_player.py)
Now also to current:
[commit diff](https://github.com/AlfredoCABA/Home-Assistant-Config/commit/189b8039788bcc94059ccb9161ea878e3b64b60d#diff-17e1aa02926052282b506da8deaf3b51)

**Comment by smartHomeHub** [comment]
Play / Pause will not be implemented. The reason is the way the official media player handle this. In fact, it's a toggle button.
Thank you
