### ISSUE TITLE
error getting value from unavailable sensor

### ISSUE THREAD

**Issue by yuri-vashchenko** [smartHomeHub/SmartIR#511]
My Humidity and Temperature room sensor that I use for climate integration updates values with some delay.
On system start, both Humidity and Temperature readings have "unavailable" value.

This leads to error message:
Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:390
Integration: SmartIR (documentation)
First occurred: 19:02:36 (1 occurrences)
Last logged: 19:02:36

Unable to update from humidity sensor: could not convert string to float: 'unavailable'

**Comment by kylehase** [comment]
Hi @yuri-vashchenko Could you share the details of your source temp/humidity sensors used when you received this error.

I'm also seeing this error on startup. Looking through the code, [there is a check for STATE_UNKNOWN](https://github.com/smartHomeHub/SmartIR/blob/d8b1f5fac6e5935ce658b80d51438f8a18d92afe/custom_components/smartir/climate.py#L174) for both temp and humidity which should handle sensors in bad states without throwing errors. 
```python
if temp_sensor_state and temp_sensor_state.state != STATE_UNKNOWN:
```
This makes me believe the issue may be the sensor sending a string when it should be a const.
My instance is using [BLE temp/humidity sensors](https://github.com/custom-components/ble_monitor) for Xiaomi temp/humidity sensors.

**Comment by rabin-io** [comment]
Same here, from what I can see the value is a string -> `unavailable`

**Comment by yuri-vashchenko** [comment]
Hi @kylehase, 
I'm using Xiaomi BLE Temperature sensor.
To get temperature/humidity values I'm using ESP32 device configured as BLE tracker.
See more details at https://esphome.io/components/sensor/xiaomi_ble.html#lywsd02

Here is a configuration of the sensor cut from from ESP32 confuguration

```
sensor:
  - platform: xiaomi_lywsd02
    mac_address: <sensor MAC address>
    temperature:
      name: <temperature sensor name>
    humidity:
      name: <humidity sensor name>

```

Currently the issue happens at different location (climate.py:438)

```
Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:438
Integration: SmartIR (documentation)
First occurred: September 12, 2021, 8:06:34 PM (13 occurrences)
Last logged: September 12, 2021, 11:15:08 PM

Unable to update from humidity sensor: could not convert string to float: 'unavailable'

```

**Comment by yuri-vashchenko** [comment]
The issue is still reproducing:

```
Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:429
Integration: SmartIR (documentation)
First occurred: 17:41:57 (1 occurrences)
Last logged: 17:41:57

Unable to update from temperature sensor: could not convert string to float: 'unavailable'
```
