### ISSUE TITLE
Add to HACS default repositories so no custom repository adding is needed

### ISSUE THREAD

**Issue by wojciechczyz** [smartHomeHub/SmartIR#512]
**Home Assistant version**
Enhancement of installation, not a problem with project

**SmartIR version**
1.13.2
**SmartIR configuration**

Enhancement of installation, not a problem with project

Add configuration here

Enhancement of installation, not a problem with project

**Describe the bug**

Add to HACS default repositories so no custom repository adding is needed.
I would love to all new people to just see it in standard HACS store. Even better, add it to Home Assistant plugins.
Thank you for hard work

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by vassilis-panos** [comment]
There are specific reasons why SmartIR is not added to HACS as default repository. Thanks
