### ISSUE TITLE
Panasonic CS-C9MKP-7

### ISSUE THREAD

**Issue by ranrinc** [smartHomeHub/SmartIR#521]
Issues not containing the minimum requirements will be closed:

Got a brand new Broadlink RM4C Mini which works great, however, it fail to run the Panasonic AC command.
Test every single SmartIR command for Panasonic and fail miserably. So wondering how can I make it work?
Is there a way to make this series available? I'm willing to contribute 

**Home Assistant version**
0.117.4

**SmartIR version**
1.13.2

**SmartIR configuration**
N/A

**Describe the bug**
The Panasonic AC Split series CS-C9MKP-7

I'm trying to used broadlink manager to make my b64 code and it never work unsure what have been done incorrectly since my other remote such as Samsung TV, Cable Box is working. Is there a way to register an AC code?

Again willing to contribute for this specific Panasonic Brand. Thanks

**Comment by devilization** [comment]
Hi,

You can use this tutorial to start [https://www.youtube.com/watch?v=tfEnadwKs-o](url) learning the code. After learning all the code, you can use any of the codes provided by SmartIR under climate (XXXX.json) and amend accordingly.
