### ISSUE TITLE
Adding support for Fujitsu AR-REW1E

### ISSUE THREAD

**Issue by comangus13** [smartHomeHub/SmartIR#523]
Hi  there,

Not an issue, but a contribution :).
Attached please find the codes for air conditioning device Fujitsu AR-REW1E

Can you please add it?

Note: Dry function only operates on "Auto", hence, I leave the rest of the instances as "NULL" (Let me know if that's correct)
Also, The Fan_Only, only operates on speed and not temperature, hence, I have populated the same code for all temperatures (also, let me know if this is the correct way)

Thanks again for this awesome integration and let me know if you require something else

Cheers,
Gus

[Fujitsu AR-REW1E.txt](https://github.com/smartHomeHub/SmartIR/files/5534029/Fujitsu.AR-REW1E.txt)

**Comment by vassilis-panos** [comment]
Added. Thanks for your contribution

**Comment by comangus13** [comment]
Sorry, I forgot to add the OFF command.

I have fixed the code, can you re-upload it or tell if I can do it myself?

Cheers,
Gus

[Fujitsu AR-REW1E.txt](https://github.com/smartHomeHub/SmartIR/files/5579440/Fujitsu.AR-REW1E.txt)

**Comment by joaovitoriasilva** [comment]
Hello,

How were you able to get the codes? I have the AR-REW2E model and it does not work with AR-REW1E config.

Thanks.
