### ISSUE TITLE
Junkers Excellence (1480.json) update

### ISSUE THREAD

**Issue by cinzas** [smartHomeHub/SmartIR#537]
Hi

I've updated the 1480.json file, for JUNKERS Excellence devices.
It is also sold as GREE Excellence, and it may also be compatible with many other brands, as GREE sells it to other brands.
Current 1480.json files does not have commands for Dry and Fan_Only.
I've added them, and it also includes auto and heat/cool codes. Feel free to delete one of them if wanted/needed.

Swing is set to auto. Some of the past codes the swing was set to low.

Thanks
[1480.txt](https://github.com/smartHomeHub/SmartIR/files/5647272/1480.txt)

**Comment by vassilis-panos** [comment]
Added. Thanks for your contribution
