### ISSUE TITLE
Alexa support

### ISSUE THREAD

**Issue by imperialjoy** [smartHomeHub/SmartIR#54]
Great plugin, works well with HomeKit and my Mitsubishi heatpumps.  One thing lacking is support for Alexa, it would be nice to be able to use her voice commands to set temperature and turn the heat pumps on and off.  Are there any plans to add this enhancement?

**Comment by smartHomeHub** [comment]
Alexa is already supported

**Comment by imperialjoy** [comment]
How is this configured for Alexa support?  The examples don't cover Alexa integration.  The alexa cloud component does not list climate as a supported option.  Does it just work anyway?

Also, the discussion thread https://community.home-assistant.io/t/smartir-climate-component/ doesn't seem to load.  Is there one yet?

**Comment by smartHomeHub** [comment]
The link was fixed.
This component is discovered by Alexa as all HA climate components. There is nothing special to cover here.

**Comment by imperialjoy** [comment]
Thanks, I restarted and it appeared in Alexa without any configuration.
