### ISSUE TITLE
Please add "advance" remote options

### ISSUE THREAD

**Issue by artucast** [smartHomeHub/SmartIR#541]
Hi. This is not an issue. 
It's working great for me. 
I want to ask for help on how to add other functions in the remote, to be set easily accessible. I would love to be able to control the flap swing and a sleep function. 
A menu such as the fan speed would be perfect.

I'm Using Tasmota MQTT IR blasters, and the codes for this are really easy to write.

**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by trankillity** [comment]
Swing speed/direction should be possible in a future update, but advanced features like sleep timer may not be in the scope of SmartIR.

The problem with stuff like this is that IR codes for air conditioners tend to be discrete. This means that when you press a button on an AC remote, you're not only sending the "sleep" command, you're sending the ENTIRE state. So what you're sending is "Sleep 1h, cool, 22c, low fan speed, high angle" in a single command. So requests like these really complicate the IR code structure.

**Comment by artucast** [comment]
> des for air conditioners tend to be discrete. This means that when you press a button on an AC remote, y

I'm using Tasmota MQTT it blaster, so i can reed the message, (tasmota does de coding) ... I can send these commands via de console,  but that is not a useful integration.

My guess is that for doing that, I'll will need to re arrange the hole .json to add all the other commands (each temp, with each swing mode, and sleep or not sleep) That is not a problem.

Am I wrong?  

Thanks for the great job!

**Comment by vassilis-panos** [comment]
SmartIR abstracts the HA climate integration and functions like Sleep are not available.
