### ISSUE TITLE
Kastron AC work with midea remote

### ISSUE THREAD

**Issue by hasan-fardan** [smartHomeHub/SmartIR#543]
- Issues without a description (using the header is not good enough) will be closed.
- Issues without debug logging will be closed.
- Issues without configuration will be closed
-->

Home Assistant 2020.12.1

**SmartIR version**
1.13.2

**SmartIR configuration**

climate:
  - platform: smartir
    name: LIving Room
    unique_id: livingroom_ac
    device_code: 1382
    controller_data: remote.rm_pro_remote

**Describe the bug**

Kastron AC with remote number "RG57A2/BGEF can use midea device_code: 1382.

**Debug log**

**Additional context**

**Comment by vassilis-panos** [comment]
Thanks!
