### ISSUE TITLE
add new climate code

### ISSUE THREAD

**Issue by rossiluis22** [smartHomeHub/SmartIR#544]
Hi i would like to upload a new config file for "Endesa" climates  it is almost the same 1522 but this goes from 18to32 degree.

[endesa.txt](https://github.com/smartHomeHub/SmartIR/files/5748772/endesa.txt)

**Comment by vassilis-panos** [comment]
Thanks! Note that the json file had many formatting errors. I fixed them. Use the 2500 file.
