### ISSUE TITLE
Issues with custom code file (JSON file is invalid)

### ISSUE THREAD

**Issue by NunoCosta14** [smartHomeHub/SmartIR#555]
[Hello,](url) I am looking to create a new code file for an unsupported air con unit from Panasonic. I download a file from the repo and altered with new base64 codes extracted from the broadlink manager app on windows. Unfortunately, no matter what I try I can't seem to get the file to work.

**Home Assistant version**

2020.12.2

**SmartIR version**

1.13.2

**Code file configuration**

[File](https://pastebin.com/9cwPJ72b)

**Describe the bug**

JSON file isn't accepted by the home assistant istance.

**Debug log**

```
2021-01-05 22:58:28 ERROR (MainThread) [custom_components.smartir.climate] The device Json file is invalid
Add your logs here.
```

**Additional context**

I have checked the file agains YAML and JSON validator and saved in both the indented form as well as uglyfied.

**Comment by vassilis-panos** [comment]
Your file works well for me. Could you post your configuration?

**Comment by NunoCosta14** [comment]
Sure. I don't really know what you need to know, but I'm running HA in a docker container in a rpi 4 and installed smartir through hacs.
After doing that, I added the code file to custom_components/smartir/codes/climate and this snippet to the configuration.yaml

`climate:
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 1027
    controller_data: remote.rm3mini_remote`

**Comment by vassilis-panos** [comment]
Double-checked. It works ok here

**Comment by NunoCosta14** [comment]
Update on this: Endend up forking the repo and editing climate.py on my ha install so that it downloads the code file from my fork. Added my code file to my fork and it ended up working. 

On another note, I'm having issues with the actual codes themselves. they function as a toggle (for example, if I change the mode or temperature while the ac is on, it will turn off). Any tips regarding this or how to actually record codes correctly? I ended up going up the temps and recording the on commands.

**Comment by NunoCosta14** [comment]
Update: Some more testing. Quick info on my AC unit:

Model: CS-SA9CKP
Remote Model: A75C2284

Notes: 

- Any command sent using the power button on the remote is read as a toggle on the AC unit (when I turn the AC on, hide the remote and press the power button again, the AC turns on again).

- Each command sent with any other buttons don't turn on the AC if it is already off (although it does beep).

- Each command appears to send the full state (tested with the swing feature of the AC).

After all of this, I assume I need to relearn codes (where, instead of turning the AC on and off, I should instead press any other button and save the state it turns into).

If anyone can confirm the assumptions I made do let me know.

**Comment by NunoCosta14** [comment]
Final Update: Finally got everything to work.

Here is the file I used:

[file](https://pastebin.com/VGzVzrUJ)

This is compatible with the model above and should also be compatible with the following models:

- CS-SA9CKP 
- CU-SA9CKP5
- CS-SA12CKP 
- CU-SA12CKP5

@vassilis-panos if you'd like to add these codes to the repo. Tested on RM3 Mini.

**Comment by vassilis-panos** [comment]
Thanks!
