### ISSUE TITLE
1.14.1 random IR blasts

### ISSUE THREAD

**Issue by Paulie-Moo** [smartHomeHub/SmartIR#556]
Since upgrading this morning I've had several random activations of my zircon and my TV

Oddly my TV has not been added to my Broadlink RM4 Pro or Home Assistant.

No issues with previous version. Just letting you know

Paul

**Comment by smartHomeHub** [comment]
Absolutely nothing changed in media_player.

**Comment by smartHomeHub** [comment]
Absolutely nothing changed in controller part.

**Comment by Paulie-Moo** [comment]
So pleased to read that, I'll leave smartir alone then, it's my favourite integration.
I'll remove the broadlink app from my phone, maybe it's that.

I'm having real trouble getting a decent learn of my main rf light switch. I wonder if that is connected?  I tried to use the tool here: https://keitetran.github.io/BroadlinkIRTools/dist/#/ but it hasnt been updated to work with latest HA and RM4

**Comment by Paulie-Moo** [comment]
a-ha, my partner said that the blue light was flashing in a random patter for about a minute at 10pm last night.  (and just told me this morning) wonder if Broadlink were pushing an update.  Think it's time to disconnect from the cloud.

Sorry for blaming SmartIR, I thought I was helping
