### ISSUE TITLE
Using a power_sensor to determine the real state of climate

### ISSUE THREAD

**Issue by a005** [smartHomeHub/SmartIR#557]
In some cases, the power_sensor does not confirm a change of the climate state (loss of command, equipment failure, etc.). Thus, the climate will have an out-of-sync state with the real state of the power_sensor, since the power_sensor is not be updated. Moreover, even if the sensor periodically sends its (unchanged) state, the construction "if new_state.state == old_state.state: return" will block an update and not allow synchronizing the state.

>another thing I noticed is that if I turn off the climate using HA but it doesn't work for whatever reason (just put a piece of paper in front of the IR) it still reports `off` as state regardless of the `power_sensor` state. Could you try that too? Thx

This issue not fixed

_Originally posted by @a005 in https://github.com/smartHomeHub/SmartIR/issues/445#issuecomment-756094507_

**Comment by 007trains** [comment]
Still an issue
