### ISSUE TITLE
Audinac AC Code

### ISSUE THREAD

**Issue by rnlascano** [smartHomeHub/SmartIR#565]
Hello, i´m trying to add support for an Air Conditioner, but i am new at github with no knowledge of it at all; long story short, i created the text file (3251.txt) but i don´t know how to upload it to make it work.

Brand: Audinac
Model Number: SP-3500
Controller: Broadlink
[3251.txt](https://github.com/smartHomeHub/SmartIR/files/5826750/3251.txt)

**Comment by vassilis-panos** [comment]
Hello and thank you for your contribution. Unfortunately we do not accept incomplete files.

**Comment by rnlascano** [comment]
Would you be so kind to  tell me what i`m missing? I`m new at this an tis is the 3rd time i try to upload a file.
