### ISSUE TITLE
Unable to find service remote.send_command

### ISSUE THREAD

**Issue by rickyi89** [smartHomeHub/SmartIR#567]
Hello everyone! I was correctly using my Broadlink RM Mini 3 with SmartIR up to the last update. I now have HomeAssistant  2021.1.4 and SmartIR updated at the last version. Now, everytime I try to use it I get "Unable to find service remote.send_command" in the report:

_Logger: custom_components.smartir.climate
Source: core.py:1395
Integration: SmartIR (documentation)
First occurred: 18 gennaio 2021, 07:48:16 (12 occurrences)
Last logged: 08:33:22
Unable to find service remote.send_command

Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 343, in send_command
    await self._controller.send(
  File "/config/custom_components/smartir/controller.py", line 111, in send
    await self.hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1395, in async_call
    raise ServiceNotFound(domain, service) from None
homeassistant.exceptions.ServiceNotFound: Unable to find service remote.send_command_

Here my configuration for smartIR on Home Assistant:

`#SmartIR
smartir:

switch:
  - platform: broadlink
    host: 192.168.1.152
    mac: 'C8:F7:42:16:F7:0B'
  - platform: command_line
    switches:
      computer_studio:
        command_on: '/config/script/pcstudioon.sh'
        command_off: '/config/script/pcstudiooff.sh'
        friendly_name: Computer Studio

climate:
  - platform: smartir
    name: Condizionatore
    unique_id: condizionatore_corridoio
    device_code: 1382
    controller_data: 192.168.1.152

media_player:
  - platform: smartir
    name: Stereo camera
    unique_id: stereo_panasonic
    device_code: 1001
    controller_data: 192.168.1.152
`

**Comment by vassilis-panos** [comment]
I guess you updated your system from a very old version.
You need to update the broadlink with the new instructions
https://www.home-assistant.io/integrations/broadlink/#configuration
