### ISSUE TITLE
How to find the HDMI 1 code for me TV

### ISSUE THREAD

**Issue by hasan-fardan** [smartHomeHub/SmartIR#568]
**Describe the bug**

I want add my Sony TV (model KDL55-HX855) to home assistant using smart ir. I have found that code 1020 works with my model but HDMI sources were not added. I would like to add them but i don't know where to find the codes. I found few codes online but they don't work. How could i find the codes for my TV?

**Comment by ostracizado** [comment]
Try the app "sure universal remote", if you have a smartphone with IR.
Check this blog's post (shorturl.at/zCQY2) for a list of Android phones with it.
