### ISSUE TITLE
Add Codes for Mistral MPAC15CY28 Climate

### ISSUE THREAD

**Issue by enjoyhiukan** [smartHomeHub/SmartIR#575]
Codes for Mistral MPAC15CY28 Climate

manufacturer: Mistral
supported Models: MPAC15CY28
commands Encoding: Base64
supported Controller: Broadlink
min Temperature: 16
max Temperature: 30
precision: 1
operation Modes:
[
"cool",
"dry",
"fan_only"
]
fan Modes:
[
"level1",
"level2",
"level3"
]
swing Modes:
[
"stop",
"swing"
]

photo of the remote control

![20210130_152137](https://user-images.githubusercontent.com/41302468/106350495-beffe500-6310-11eb-98d0-1a32c5dfa430.jpg)

[4.zip](https://github.com/smartHomeHub/SmartIR/files/5897542/4.zip)

**Comment by vassilis-panos** [comment]
Thanks!
