### ISSUE TITLE
add Codes for AC daitsu DOS-(9/12/18/21)KIDB

### ISSUE THREAD

**Issue by zrcz** [smartHomeHub/SmartIR#577]
**Home Assistant version**

2021.1.5

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

Attached codes for AC  daitsu DOS-(9/12/18/21)KIDB

I have add the number 1764

[1764.zip](https://github.com/smartHomeHub/SmartIR/files/5906050/1764.zip)

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by vassilis-panos** [comment]
Thanks!
