### ISSUE TITLE
Add support to different Haier climate

### ISSUE THREAD

**Issue by romaydan** [smartHomeHub/SmartIR#578]
<!-- Before you open a new issue, search through the existing issues to see if others have had the same problem.

**Home Assistant version**
2021.1.5

**SmartIR version**
1.16.0
**SmartIR configuration**
`smartir:
climate:
  - platform: smartir
    name: Livingroom AC
    unique_id: livingroom_ac
    device_code: 1320
    controller_data: remote.broadlink_remote

the Haier remote that supported currently not working with my Haier air conditioner

**Comment by romaydan** [comment]
this is the remote codes for my haier ac
[1330.zip](https://github.com/smartHomeHub/SmartIR/files/5926248/1330.zip)

**Comment by vassilis-panos** [comment]
![εικόνα](https://user-images.githubusercontent.com/4130346/106905370-e685f180-6704-11eb-8a5d-206058382d4f.png)

**Comment by romaydan** [comment]
oops  forgot to save 💯 
[1330.zip](https://github.com/smartHomeHub/SmartIR/files/5926590/1330.zip)

**Comment by vassilis-panos** [comment]
Thanks!
