### ISSUE TITLE
Mitsubishi RKX502A001

### ISSUE THREAD

**Issue by antibill51** [smartHomeHub/SmartIR#58]
Hi. 
Is there a json file for Mitsubishi RKX502A001 remote? 

my ini file ( who is not working fully ) is available [here](https://raw.githubusercontent.com/antibill51/ThermostatV2/master/mitsubishi.ini)  
Thanks.

**Comment by smartHomeHub** [comment]
What is the problem with your old ini file?

**Comment by antibill51** [comment]
some code don't work...

**Comment by smartHomeHub** [comment]
Did you try any of these codes?
https://github.com/smartHomeHub/SmartIR/blob/master/docs/CLIMATE.md#mitsubishi-electric

**Comment by antibill51** [comment]
Yes, but it's not the same remote.

**Comment by smartHomeHub** [comment]
I'm afraid you need to learn your own codes. Also, ask in the community forum.

**Comment by antibill51** [comment]
It is what i do whith the old component but some code are not recognized.
