### ISSUE TITLE
A/C remote listed in media players

### ISSUE THREAD

**Issue by krasatos** [smartHomeHub/SmartIR#588]
Hey there, thank you for this great component.

A quick correction that this [remote](https://github.com/smartHomeHub/SmartIR/blob/master/codes/media_player/1340.json) should be listed under `climate` and not `media players`.

Keep up the good work.

PS. Sorry for opening an issue, i dont know if there's a better way to suggest this :)

**Comment by vassilis-panos** [comment]
Ευχαριστώ! Δεν ξέρω πως πέρασε αυτό.
Δεν πληροί τις προϋποθέσεις ούτε ως αρχείο  κλιματιστικού.

**Comment by krasatos** [comment]
Happy to help.
Συγχαρητήρια & πάλι
