### ISSUE TITLE
JSON file for Fujitsu AR-AB5 remote

### ISSUE THREAD

**Issue by aheath70** [smartHomeHub/SmartIR#60]
Existing JSON files for Fujitsu Air Conditioner didn't work on my air conditioner with AR-AB5 remote. I created the full set of cool, dry (auto only available in this mode) and fan codes, 18-30 degrees. 

[1289.json.zip](https://github.com/smartHomeHub/SmartIR/files/2948039/1289.json.zip)

**Comment by smartHomeHub** [comment]
Hello,
Thank you very much for your contribution. Are you planning to implement the heat mode also?
Thanks

**Comment by aheath70** [comment]
I would love to, but my air conditioner is cooling only- no heat mode.

**Comment by smartHomeHub** [comment]
Uploaded. Thanks for your contribution. I really appreciated.
