### ISSUE TITLE
Remote Code for Mitsubishi Electric MS-SGD18VC A/C

### ISSUE THREAD

**Issue by MaxDucy** [smartHomeHub/SmartIR#604]
Remote code for Mitsubishi Electric MS-SGD18VC A/C (Straight cool model)

[1130.zip](https://github.com/smartHomeHub/SmartIR/files/6107137/1130.zip)

![รีโมท MS-SGD18VC 05120367426](https://user-images.githubusercontent.com/51054387/110444283-6b42a180-80ef-11eb-9f12-14c7914391c1.jpg)

**Comment by vassilis-panos** [comment]
Thanks!
