### ISSUE TITLE
Daikin FTXV35AV1B

### ISSUE THREAD

**Issue by bvermes17** [smartHomeHub/SmartIR#606]
Hello @smartHomeHub !

I was looking for a file to support my AC as a climate device with Broadlink controller but it was not in the list so I created my own. 

I share it attached, please add it to the repo if you find it useful. It is complete with all the functions and temperatures that the device is capable of. 

BR,

Belián

[FTXV35AV1B.zip](https://github.com/smartHomeHub/SmartIR/files/6143755/FTXV35AV1B.zip)

**Comment by vassilis-panos** [comment]
Thanks!
