### ISSUE TITLE
Next/Previous Track buttons not showing

### ISSUE THREAD

**Issue by robchap79** [smartHomeHub/SmartIR#609]
Hi,

I hadn't updated my SmartIR/ home assistant for a while as I was in the middle of a major home network overhaul - I have updated now, and I no longer have next/previous track buttons visible on the media player card in the lovelace UI.

For reference:-

HA Core 2021.4.1 OS5.13

Smart IR 1.16.0

I am using Broadlink IR blasters.

The next/previous track works if I manually call up the service/entity using developer tools, I just don't get the buttons on the UI. I am 99% sure I previously had the buttons on there. The relevant config is:-
#Living Room TV Ping switch to determine if on
binary_sensor 10:
  - platform: ping
    host: 192.168.100.52
    scan_interval: 5
    name: living_room_tv_power

#Living Room TV controls thru broadlink 1063.json is code file    
media_player 10:
  - platform: smartir
    name: Living room TV
    unique_id: living_room_tv
    device_code: 1063
    controller_data: remote.livingroom_remote
    power_sensor: binary_sensor.living_room_tv_power

The code file is my own.

**Comment by vassilis-panos** [comment]
These options were removed from Home Assistant. There is an open request in HA repo to restore them.

**Comment by robchap79** [comment]
Well that would explain the issue. Thanks mate, appreciate the response, and all the work you've done on this integration.
