### ISSUE TITLE
Template for adding fan codes

### ISSUE THREAD

**Issue by papinist** [smartHomeHub/SmartIR#613]
Hi,
I want to add codes found from my ceiling fan (DCG brand) but I don't know how to do it.
I tried to modify an existing json file but I have more codes other than only speed:
speed: low, medium, high
timer: 1h, 2h, 4h
fan off
light on\off

So, how should I do?

**Comment by vassilis-panos** [comment]
I'm sorry but you can not add these extra codes. Only HA fan platform functions are allowed
