### ISSUE TITLE
Homekit integration error when using SmartIR power state sensor

### ISSUE THREAD

**Issue by avdiushkin** [smartHomeHub/SmartIR#618]
"Power state" from binary sensor don't work correctly.

When I'm manually turning AC off or on, power state from binary sensor displays correctly in Home Assistant, but in Homekit device becoming "Not responding".

Log from HomeAssistant:

Logger: pyhap.accessory_driver
Source: components/homekit/type_thermostats.py:254 
First occurred: 14:21:15 (4 occurrences) 
Last logged: 14:21:30

{'TargetHeatingCoolingState': 0}: Error while setting characteristics to ('192.168.1.192', 54574) for the Thermostat service
{'TargetHeatingCoolingState': 2}: Error while setting characteristics to ('192.168.1.192', 54574) for the Thermostat service
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/pyhap/accessory_driver.py", line 794, in set_characteristics
    service_data[SERVICE_CALLBACK](service_data[SERVICE_CHARS])
  File "/usr/src/homeassistant/homeassistant/components/homekit/type_thermostats.py", line 254, in _set_chars
    homekit_hvac_mode = HC_HASS_TO_HOMEKIT[hvac_mode]
KeyError: 'on'

**Comment by vassilis-panos** [comment]
In this case try to add `power_sensor_restore_state: true` in your configuration

**Comment by avdiushkin** [comment]
After adding the parameter error has been fixed. Thank you!
