### ISSUE TITLE
FIY: new a/c Yamatsu AUS-07C53R013L24

### ISSUE THREAD

**Issue by seventhsite** [smartHomeHub/SmartIR#629]
Hi! I have a/c Yamatsu AUS-07C series, model AUS-07C53R013L24 and codes [2400](https://github.com/smartHomeHub/SmartIR/blob/master/codes/climate/2400.json) for another Yamatsu is working for me. One difference - I don't have a heating function.

![](https://habrastorage.org/webt/ys/jx/4e/ysjx4emxsgd4zzdid9b7ggcj13s.jpeg)

**Comment by vassilis-panos** [comment]
Thanks!
