### ISSUE TITLE
How to set poweroff timer after power on an A/C?

### ISSUE THREAD

**Issue by seventhsite** [smartHomeHub/SmartIR#630]
Hello!
I use SmartIR and thermostat card in HA.

```
        - type: thermostat
          entity: climate.ac
          name: Room A/C
          icon: 'mdi:air-conditioner'
          state_color: true
          title: ac_view
```

Two question:

1.  How to set timer for auto power off an a/c after two hours when it been powered on?
2.  How to switch to FAN mode for 1 minute after the power off button tap? I want to drain the A/C before turning off.

![](https://habrastorage.org/webt/uf/k2/xp/ufk2xppytofnr4uqkyo--lvdvvu.png)

**Comment by vassilis-panos** [comment]
You can achieve all this through automation. If you need help, you can ask @ forums.
