### ISSUE TITLE
New AC code. Manufacturer: Apton, Model: AFC-100T

### ISSUE THREAD

**Issue by Skyler841017** [smartHomeHub/SmartIR#637]
[ir-code.json.txt](https://github.com/smartHomeHub/SmartIR/files/6801246/ir-code.json.txt)

**Comment by Skyler841017** [comment]
Is there any problem with my code?

**Comment by vassilis-panos** [comment]
You need to repeat all fan modes and temperatures for dry mode

**Comment by Skyler841017** [comment]
my dry mode only has auto, doesn't have level1,level2, level3

**Comment by smartHomeHub** [comment]
I know, but you have to repeat them. Otherwise the smartir will throw key was not found error

**Comment by Skyler841017** [comment]
I repeat them, and re-upload the file, please take a see.

**Comment by vassilis-panos** [comment]
Thanks!
