### ISSUE TITLE
Issue with Samsung TV

### ISSUE THREAD

**Issue by astergiou** [smartHomeHub/SmartIR#639]
Hello,

I have 2 Samsung TVs and I would like to have a new code that will be combination of 1060 and 1061 code because with 1061 code everything is working except power off/on and with 1060 code everything is working but I do not have the capability to change sources to HDMI as it does not have them as option.
So I would like to have a new code 1063 that will have power on and off commands from 1060 and all other commands from 1061

thank you

**Comment by vassilis-panos** [comment]
Γεια σας,
Καλύτερα να χρησιμοποιήσετε κάποιον κωδικό που δεν υπάρχει στη λίστα, όπως 9999.

**Comment by astergiou** [comment]
Ok
Could you create 9999 code and merge it?
