### ISSUE TITLE
New AC code. Manufacturer: Gree, General Climate

### ISSUE THREAD

**Issue by Anton-Ka** [smartHomeHub/SmartIR#645]
**Brand:**
Gree
General Climate (russian local brand)

**Model:**
GWH07KF (GC-EAF07HR)
GWH09KF (GC-EAF09HR)
GWH12KF (GC-EAF12HR)

**Codes:**
See file
[1184.json.txt](https://github.com/smartHomeHub/SmartIR/files/6658515/1184.json.txt)

**Comment by vassilis-panos** [comment]
Thanks!
