### ISSUE TITLE
Add support for Daikin remote BRC4C156

### ISSUE THREAD

**Issue by lin34r** [smartHomeHub/SmartIR#652]
I believe this remote is similar to the BRC4C158 remote for which support was recently added except that '156 uses Fahrenheit.

**Comment by vassilis-panos** [comment]
Thanks!

**Comment by lin34r** [comment]
Sorry, but this issue isn't resolved so it should be re-opened?  What I meant was that even though BRC4C156 remote is similar to the BRC4C158 remote, **it's still going to need a separate code file** because it uses Fahrenheit rather than Celsius.  Thanks.
