### ISSUE TITLE
Add support for Midea R5119/BGE remote, Xiaomi remote (v2)

### ISSUE THREAD

**Issue by vmannoor** [smartHomeHub/SmartIR#653]
I tried the only xiaomi code available under Midea section and it is not working. 
I don't know the model number of air conditioner. Remote model is **R5119/BG**
I can control the ac from Mi Home app.
Can you please add support for this remote.

**Comment by vassilis-panos** [comment]
I can not do anything about it. You will have to create the commands file yourself.
