### ISSUE TITLE
New AC code. Manufacturer: General Electric, Model: AHD08LXW1

### ISSUE THREAD

**Issue by danian95** [smartHomeHub/SmartIR#665]
[1044.json](https://github.com/smartHomeHub/SmartIR/files/6766096/1044.json.txt)

Some command combinations don't work together (like dry + auto fan, the original remote does not send a command for these). The light for the display is not implemented as it requires a new set of codes.

**Comment by danian95** [comment]
Also, the energy saver mode is set as "auto".

**Comment by vassilis-panos** [comment]
Thanks!
