### ISSUE TITLE
New AC code.  Gree Xk76 thermostat w/ YT1F remote.

### ISSUE THREAD

**Issue by rlatimer4** [smartHomeHub/SmartIR#668]
Edit: found some errors in my code file.  Updated file here: 
[9900.json.txt](https://github.com/smartHomeHub/SmartIR/files/6801701/9900.json.txt)

**Comment by charlesdagenais** [comment]
Hi, curious about that. My YAN1F10F remote look a little like the YT1F (I assume you used).

asking because these remote have a clock: does the code change if you send the same command at different time ? Like « cool,fan_low,65 » at 08:40, then again at 08:41 ?

**Comment by rlatimer4** [comment]
My codes still work, so I don't think they change with time.  The thermostat's clock is set independently too.  I think the clock may change codes related to the timer functions, but I don't plan on using those.

**Comment by vassilis-panos** [comment]
You need also to repeat each temperature for fan_only mode.
