### ISSUE TITLE
New AC code. Manufacturer: Kolin, Remote Controller: RC-M7B1

### ISSUE THREAD

**Issue by chinyaolin** [smartHomeHub/SmartIR#675]
Manufacturer: 

> Kolin

SupportedModels:
> remote controller: RC-M7B1

> indoor unit: "KSA-D201", "KSA-D252", "KSA-D562", "KSA-D912", "KSA-D202", "KSA-D322", "KSA-D632", "KSA-20D", "KSA-D362", "KSA-D682", "KSA-25D", "KSA-D452", "KSA-D782"

![21927956146507_604](https://user-images.githubusercontent.com/52078139/125715838-55da668a-d3fa-4adb-bd16-6d31211b8270.JPG)

Temperature: 25~31
OperationModes: cool
Fan Modes: auto/high/low
Swing Modes: auto/top/buttom

[https://gist.github.com/chinyaolin/c79a0eca12029f447ccfbb951c29519e](url)

**Comment by vassilis-panos** [comment]
Swing Modes: auto/top/button
Do you mean bottom?

**Comment by chinyaolin** [comment]
Yes, it should be 'bottom'.
I updated gist.

**Comment by vassilis-panos** [comment]
Thanks!
