### ISSUE TITLE
An error occurred while checking for updates.

### ISSUE THREAD

**Issue by JachinY** [smartHomeHub/SmartIR#680]
**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by vassilis-panos** [comment]
What kind of error?

**Comment by JachinY** [comment]
> What kind of error?

I add check_updates : false to config yaml and this error was gone

**Comment by JachinY** [comment]
Thank you
@vassilis-panos
