### ISSUE TITLE
Fujitsu AR-REF1E

### ISSUE THREAD

**Issue by kaizersoje** [smartHomeHub/SmartIR#694]
I have got a Fujitsu AR-REF1E. The existing codes don't seem to work for this remote. Any suggestions on how to proceed?

![image](https://user-images.githubusercontent.com/54566217/128615511-374f3d33-6ff1-4e4a-8dbf-3fd502e40aa1.png)

**Home Assistant version**

**SmartIR version**

**SmartIR configuration**

```yaml

Add configuration here

```

**Describe the bug**

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by vassilis-panos** [comment]
Better ask to forums.
