### ISSUE TITLE
Add codes for Mitsu. C56-RW5 Ceiling Fan

### ISSUE THREAD

**Issue by christianonpele** [smartHomeHub/SmartIR#697]
{
  "manufacturer":"Mitsubishi",
  "supportedModels":[
    "C56-RW5 Ceiling Fan"
  ],
  "supportedController":"Broadlink",
  "commandsEncoding":"Base64",
  "speed":[
    "1",
    "2",
    "3",
    "4",
    "5",
    "rhythm"
  ],
  "commands":{
    "off":"JgCGAGo0DSgNKA0ODQ0NDg0oDQ4NDQ0pDSgNDQ0oDQ4MDwwpDCkMDwwpDCkNDQ0pDQ0NDgwODQ4NDgwpDQ0NDg0NDigNDQ0ODQ0NDgwPDA4MDwwODSgNKQwpDSgNDgwpDA4NDgwODSkNDQ0ODA4NDg0ODA4MDw0NDQ4MDg4NDA8NKAwpDCkMAA0F",
    "default":{
      "1":"JgCGAGo0DSgNKA0ODQ0NDg0oDQ4NDQ0pDSgNDQ0oDQ4MDwwpDCkMDwwpDCkNDQ0pDQ0NDgwODQ4NDgwpDQ0NDg0NDigNDQ0ODQ0NDgwPDA4MDwwODSgNKQwpDSgNDgwpDA4NDgwODSkNDQ0ODA4NDg0ODA4MDw0NDQ4MDg4NDA8NKAwpDCkMAA0F",
      "2":"JgCGAGk0DycOJw0NDQ4MDg0pDA4NDg0oDSgODQwpDQ0NDg0oDCkNDg0oDCkMDw0oDA4NDgwPDQ0NDg0oDgwODQwPDCkMDg0ODQ0NDgwPDA4ODQ0NDSgOKA0oDSgMDw4nDA4NDg0NDg0NKA0ODQ0NDg4nDA8MDg0ODA4NDg0NDigMKQ0oDSgMAA0F",
      "3":"JgCGAGo0DSgOKA0NDQ4MDg0oDg0MDw0oDSgNDg0oDQ0NDgwpDCkMDw0oDSgNDgwpDQ0ODQwPDA4NDg0oDA4ODQ0ODSgMDg0ODA8MDg0ODQ0NDg0NDigNKA0oDSgODQ4nDQ0ODQwPDSgNKA0NDQ4MDwwpDA4NDg0ODQ0MDwwODQ4MKQ0oDSgOAA0F",
      "4":"JgCGAGo0DSgOKAwODQ4MDg0oDg0NDg0oDicMDw0oDwsNDg0oDSgNDgwpDSgNDgwpDQ0NDg0NDg0NDgwpDQ0NDg0NDSkMDg0ODQ0NDg0NDQ8MDg0NDCkNKA4oDSgNDQ0oDQ4MDw4MDQ4NDQ0oDQ4MDw0oDA4NDg0NDQ4ODQwODSgNDgwODicNAA0F",
      "5":"JgCGAGg2DicNKA0ODA4NDgwpDQ4MDgwpDSgODQ0oDg0ODA4oDSgNDQ0oDigNDQ0oDg0NDg0NDQ4MDg0oDg0MDw4MDSgODQ0NDg0NDgwODg0NDg0OCykPJg4nDigNDQ0oDg0ODQ0NDCkPDA8mDQ4NDgwoDg0NDgwODQ4MDg4NDg0NDQwPDSgNAA0F",
      "rhythm":"JgCGAGk1DSgNKA0ODQ0NDg0oDQ4NDQ0oDSgNDg0oDQ4NDQ4oDCkMDg0oDSkMDg4nDg0NDg0NDQ4NDQ4oDA4NDg0NDigNDQ0ODQ0ODQ4NDQ0NDg0NDSgOKA0oDSgMDw4nDA4ODQ0ODSgMDwwoDg0NDg0NDQ4NDQ4NDQ4NDQ0ODQ0OKAwODicNAA0F"
    }
  }
}

**Comment by vassilis-panos** [comment]
Thanks
