### ISSUE TITLE
[Climate] Custom settings per operations

### ISSUE THREAD

**Issue by earth08** [smartHomeHub/SmartIR#70]
Dear,
This was earlier provided by thunderbird2086,
which was working perfectly,
Please provide us the same.
Thanks in adv.
link for thunderbird2086
https://github.com/vpnmaster/homeassistant-custom-components/pull/75

**Comment by smartHomeHub** [comment]
You have already sent to @Thunderbird2086 pull request on the old repo.
Please wait for his answer.
Thank you

**Comment by earth08** [comment]
dear,
no reply 
nor any changes in files seen,
Please provide us
thanks
