### ISSUE TITLE
add Bosch climate code

### ISSUE THREAD

**Issue by rossiluis22** [smartHomeHub/SmartIR#707]
Hi, I've created a json with file code for Bosch 5000i climate, could you please upload it

[bosch5000i.txt](https://github.com/smartHomeHub/SmartIR/files/6988129/bosch5000i.txt)

**Comment by rossiluis22** [comment]
i've tried locally but i'm getting `The device Json file is invalid` i checked the file 1000 times, also reinstalled SmartIR, the version i'm using of HA is 2021.8.6 and for SmartIR is 1.17.0.

Thanks in advance

**Comment by rossiluis22** [comment]
I reply my self, there was an error in the file. 
Here it is the one that works fine so you can upload it to the rest of the community 😃 
[bosch5000i.json.txt](https://github.com/smartHomeHub/SmartIR/files/7007814/bosch5000i.json.txt)

**Comment by vassilis-panos** [comment]
Thanks!
