### ISSUE TITLE
Wrong code after powerfailure

### ISSUE THREAD

**Issue by pamm01** [smartHomeHub/SmartIR#74]
**Home Assistant version**
running version 0.88.1

**SmartIR version**
1.2.1

**SmartIR configuration**
climate:
  - platform: smartir
    name: SmartIR Climate
    device_code: 1020
    controller_send_service: switch.broadlink_send_packet_192_168_1_91
    temperature_sensor: sensor.innevagg_temperature

```yaml



```

**Describe the bug**
After power failure it changes to code 1021, should be 1020.

**Comment by smartHomeHub** [comment]
The component cannot change this value!
