### ISSUE TITLE
New IR codes for Climate Lennox: LNINVE052 (2162)

### ISSUE THREAD

**Issue by axa4953** [smartHomeHub/SmartIR#756]
Home Assistant version
Home Assistant 2021.11.5

SmartIR version
1.17.1

------

Hi team,
I did not find a working configuration for my Lennox AC model LNINVE052 and decided to create one via Broadlink/Hass IR remote_learn function. The result can be found in attached file.

Please consider adding it to repo, and feel free to let me know of any issues with it.

Ps: Not a Github expert, thus cannot pull, branch, etc. etc. Sorry.

----

Add configuration here

[2162.txt](https://github.com/smartHomeHub/SmartIR/files/7682701/2162.txt)

```

**Additional context**

Manual, supported models and details about limitations of fan modes listed here: 

https://www.ebranch.online/is-bin/INTERSHOP.enfinity/WFS/eCat-LnHGroup-Site/en_AU/-/AUD/ViewStaticContent-OpenFile;sid=L1ntwI7HJG75wNLjFsT6wA7NUq1ScfMzkOg=?LocaleId=&UnitName=eCat&DirectoryPath=61305976&FileName=SERVICE_MANUAL_LNINV5210_TO_LNINV8010.PDF.

**Comment by vassilis-panos** [comment]
Thanks!
