### ISSUE TITLE
Daikin AC units, models FTXM25UVMA (Alira), FTXM35UVMA (Alira) working with code 1101

### ISSUE THREAD

**Issue by axa4953** [smartHomeHub/SmartIR#757]
Home Assistant version
Home Assistant 2021.11.5

SmartIR version
1.17.1

SmartIR configuration with Broadlink ir

  - platform: smartir
    name: Main Room AC
    unique_id: Main_room_ac
    device_code: 1101
    controller_data: remote.main_room_remote
  
  - platform: smartir
    name: Guest Room AC
    unique_id: guest_room_ac
    device_code: 1101
    controller_data: remote.guest_room_remote

Describe the Issue:
I have functioning control of my Daikin (2x)  AC units, models FTXM25UVMA (Alira), FTXM35UVMA (Alira)  with the code 1101. 
I think this model can be added to the configuration. Thx for the work of whoever did it in the past.

Debug log

Not applicable

Additional context

**Comment by vassilis-panos** [comment]
Thanks!
