### ISSUE TITLE
Vortex AC working with remote 2380

### ISSUE THREAD

**Issue by wtv1211** [smartHomeHub/SmartIR#765]
AC device: Vortex VAI-A1221FFWR and a lot more current generation Vortex AC inverters.
Remote control name; YKR-H/009E
Compatible listed remote: 2380
Mention: "fan_only auto" and will not work as there is no such option on the physical remote. 

Rambling: I suspect  "cool_heat" set temp is not configurable by the user (there is no set_temp option on "auto" mode on the physical remote). From what I observed, depending on the exterior temp, the device tries to make compromise between spent energy and confort. Meaning at 7C, max COP, will auto heat to 24C. Under -7C, will heat to 20C. At 35C+ outside. will cool down to 26C, at 30C outside, 23C inside. 
Ideally, the "feeling" button (remote's build in temp sensor that reports to the ac unit) will work at some point as it halfs the starts/stops of the compressor.

**Comment by vassilis-panos** [comment]
Thanks!

**Comment by rennokki** [comment]
@samuelolteanu I was searching up these things like a madman. Thanks! (Mulțumesc mult!)

**Comment by samuelolteanu** [comment]
Tested further and found 2580 has the the most working features including 0.5 temperature step.

**Comment by rennokki** [comment]
Tested both. `2580` is defo useful if you have 0.5C increments. Sadly mine does not support 0.5C, so `2380` is good too! Thanks again!

**Comment by rennokki** [comment]
> Ideally, the "feeling" button (remote's build in temp sensor that reports to the ac unit) will work at some point as it halfs the starts/stops of the compressor.

I know that the physical remote control uses its own built-in temp sensor to adjust the Feeling function, but do you have any idea if the IR sensor takes its place? Or a physical remote control is also required to sync the right temps?
