### ISSUE TITLE
Add support for "Best" brand model "BSTS18CNE2"

### ISSUE THREAD

**Issue by ammaralfarsi** [smartHomeHub/SmartIR#771]
i have gathered codes of AC "Best" brand model "BSTS18CNE2" the file uploaded in the below link.

note: 

1.  Fan: has only low, mid, and high. without temperature adjustment. also copied high in auto.
2. Dry: has only one code, copied across all low, mid, high & auto.
3. Auto mode: not added yet.

[1000.zip](https://github.com/smartHomeHub/SmartIR/files/7921202/1000.zip)

**Comment by vassilis-panos** [comment]
Thanks!
