### ISSUE TITLE
IR Codes for ac Midea RG70E whit BGEF remote (Broadkink)

### ISSUE THREAD

**Issue by lucasjbx** [smartHomeHub/SmartIR#774]
This are the IR codes i got for tha ac Midea RG70E whit BGEF remote.
Everything seems to be working, "auto", "cool", "dry", "heat", "fan_only".

[RG70E-BGEF.zip](https://github.com/smartHomeHub/SmartIR/files/7963462/RG70E-BGEF.zip)

**Comment by vassilis-panos** [comment]
Nice! Thanks
