### ISSUE TITLE
Fan speed unable to be changed with HA 2022.2

### ISSUE THREAD

**Issue by aidbish** [smartHomeHub/SmartIR#776]
**Home Assistant version**
2022.2

**SmartIR version**
1.17.4

**SmartIR configuration**

```yaml

Add configuration here

fan:
  - platform: smartir
    name: Master Bedroom fan
    unique_id: master_bedroom_fam
    device_code: 1600
    controller_data: remote.broadlinkrmpro_remote

**Describe the bug**

Unable to set fan speed using the latest HA version, rolling back to 2021.12.x works
Suspect soimething to do with

This is more a breaking change for custom integration developers.
Now that all core fans are using the new fan entity model, the compatibility shim has been removed. Custom integrations that have not yet switched to the new fan model may be affected. For more information see:
https://developers.home-assistant.io/docs/core/entity/fan/#deprecated-properties
Preset modes and percentages will continue to be translated back to legacy speeds until 2022.3 in order to give users a bit more time to update automations.
([@bdraco 1](https://github.com/bdraco) - [#59781](https://github.com/home-assistant/core/pull/59781)) ([fan docs](https://www.home-assistant.io/integrations/fan/))

eroor message below

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 190, in handle_call_service

    await hass.services.async_call(

  File "/usr/src/homeassistant/homeassistant/core.py", line 1630, in async_call

    task.result()

  File "/usr/src/homeassistant/homeassistant/core.py", line 1667, in _execute_service

    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(

  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service

    await self.hass.helpers.service.entity_service_call(

  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call

    future.result()  # pop exception if have

  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 921, in async_request_call

    await coro

  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call

    await result

  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 246, in async_set_percentage

    await self.hass.async_add_executor_job(self.set_percentage, percentage)

  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 240, in set_percentage

    raise NotImplementedError()

NotImplementedError


A clear and concise description of what the bug is.

**Debug log**

```text

Add your logs here.

```

**Additional context**

**Comment by nsheldon** [comment]
Just upgraded to 2022.2 and can confirm this exact issue myself with SmartIR 1.17.4.

**Comment by SrBurner** [comment]
Issue persist in Home Assistant 2022.2.1 and SmartIR 1.17.4 I can confirm the issue is because "Speed parameter" is deprecated and "percentage parameter" is needed now. I have just create a fan template with an script and helper that translates percentage orders to speed orders and with that it works. (but I think is a temporary fix until HA2022.3)

**Comment by sasukebinbin** [comment]
+1 Same

**Comment by dredzed** [comment]
I have the same issue. HA 2022.2, smartIR 1.17.4.
I am able to turn fan on and off, but have no control of the speed.
Very similar logs to the above, ending with:
`  File "/usr/src/homeassistant/homeassistant/components/fan/__init__.py", line 240, in set_percentage
    raise NotImplementedError()`

**Comment by vassilis-panos** [comment]
I need a few days to take a look at this. Unless one can create a PR.

**Comment by LeandroIssa** [comment]
Here I have the same problem.

**Comment by vassilis-panos** [comment]
I created a fast gist. Replace all code in fan.py and leave a feedback. 

https://gist.github.com/vassilis-panos/d22f0c24e582f9f461d5423fd02d2965

**Comment by h3nrytan** [comment]
> I created a fast gist. Replace all code in fan.py and leave a feedback.
> 
> https://gist.github.com/vassilis-panos/d22f0c24e582f9f461d5423fd02d2965

Tested this and it works all good with HA 2022.2.2

**Comment by aidbish** [comment]
> I created a fast gist. Replace all code in fan.py and leave a feedback.
> 
> https://gist.github.com/vassilis-panos/d22f0c24e582f9f461d5423fd02d2965

Same here, confirming this works

**Comment by LeandroIssa** [comment]
> I created a fast gist. Replace all code in fan.py and leave a feedback.
> 
> https://gist.github.com/vassilis-panos/d22f0c24e582f9f461d5423fd02d2965

I put it here and it solved the problem! Thank you very much!
