### ISSUE TITLE
Climate does not work (Xiaomi IR + MiiO)

### ISSUE THREAD

**Issue by fantnhu** [smartHomeHub/SmartIR#807]
**Home Assistant version**
### **Home Assistant 2022.3.5**
**SmartIR version**
### **1.17.5**
**SmartIR configuration**

`smartir:
  check_updates: false
remote:
  - platform: xiaomi_miio
    host: 192.168.31.222
    token: 8f6ffa21cf52fb7851fe342a79bcXXXX
climate:
  - platform: smartir
    name: Heinner AC
    unique_id: heinner_ac
    device_code: 3380
    #controller_data: remote.xiaomi_miio_192_168_31_222
    controller_data: remote.xiaomi_miio_192_168_31_222
    temperature_sensor: sensor.mi_mtk_temperature
    humidity_sensor: sensor.mi_mtk_humidity`

Hi! It used to work perfectly, but it’s been bad since the big change.
Only turning off the air conditioner works, nothing else. What could be the problem?
I've tried controller_data in several formats as described, but it doesn't work.
- Xiaomi IR entity: remote.xiaomi_miio_192_168_31_222
- IP address: Good
- Token: Good
- Device code: Good
remote.send_command service works perfectly with RAW command.
Please help! Thank you very much.

`'1'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 378, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: '1'`

**Comment by carlos-48** [comment]
Hi, same error for me, but I have Broadlink RM4 mini and an LG air conditioner (code 1062). I noticed it stopped working today, but none of my AC automations have been triggered from last Friday, so maybe the failure started before.

Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:378
Integration: SmartIR (documentation)
First occurred: 18:52:14 (5 occurrences)
Last logged: 19:21:14

''
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 378, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: ''

**Comment by fantnhu** [comment]
Yes, the error started earlier. I haven't used it in a long time. There was nothing wrong with it before the updates. All functions worked. Now that can only turn off the climate.

**Comment by carlos-48** [comment]
Hi again, I've checked in my HA that the climate entity had no "fan speed". This was usually in Automatic or in Low speed modes, but I don't know why one of the updates or reboots has cleared that property to blank. Now I've changed that manually to any speed and it works.

I'll keep an eye on it to see if it happens again.

**Comment by fantnhu** [comment]
Unfortunately, for me, only the shutdown works, nothing else.
It used to be perfect, but I haven’t been able to use it since the big update.

**Comment by PcOnline2004** [comment]
> 

Me got the same error again.
I remember last time, I did remove (or copy overwrite) from backup then it will be work agaim.

**Comment by PcOnline2004** [comment]
This error originated from a custom integration.

Logger: custom_components.smartir.climate
Source: custom_components/smartir/climate.py:378 
Integration: SmartIR (documentation) 
First occurred: 9:20:27 PM (17 occurrences) 
Last logged: 9:26:05 PM

'On Low'
Traceback (most recent call last):
  File "/config/custom_components/smartir/climate.py", line 378, in send_command
    self._commands[operation_mode][fan_mode][target_temperature])
KeyError: 'On Low'

**Comment by fantnhu** [comment]
> > 
> 
> Me got the same error again. I remember last time, I did remove (or copy overwrite) from backup then it will be work agaim.

Yes, I saw that post. Unfortunately, this solution does not work in the new version.
The author does nothing :( Yet a wonderful idea and solution

**Comment by PcOnline2004** [comment]
> > > 
> 
> > 
> 
> > Me got the same error again. I remember last time, I did remove (or copy overwrite) from backup then it will be work agaim.
> 
> 
> 
> Yes, I saw that post. Unfortunately, this solution does not work in the new version.
> 
> The author does nothing :( Yet a wonderful idea and solution

It works for me (new version). I've just remove/reinstall it. Remember, you should remove folder of SmartIR then reinstall it.
