### ISSUE TITLE
IR Codes for Midea MAP05R1WWT (portable AC unit)

### ISSUE THREAD

**Issue by MrDanSiegel** [smartHomeHub/SmartIR#815]
This should be a complete file for the Midea MAP05R1WWT. I used "auto" in place of "heat/cool" and edited the codes to F so if those need to be reverted just let me know and I'll clean that up really quick.

Thanks for the dope integration. 

[Pastebin link](https://pastebin.com/GFPunx5u)

**Comment by vassilis-panos** [comment]
Thanks!
