### ISSUE TITLE
Homeassistant is lastest release，but notification error message

### ISSUE THREAD

**Issue by jaove** [smartHomeHub/SmartIR#818]
Home Assistant version
    host:Home Assistant OS 7.6
    Supervisor:supervisor-2022.03.5
    Core:core-2022.3.8

SmartIR version

Describe the bug
    Notification windows message：There is a new version of SmartIR integration, but it is incompatible with your system. Please first update Home Assistant.
    But my homeassistant is lastest release

**Comment by vassilis-panos** [comment]
https://www.home-assistant.io/blog/2022/04/06/release-20224/
