### ISSUE TITLE
Codes for Viessmann Vitoclima 300-S series

### ISSUE THREAD

**Issue by cryogeno** [smartHomeHub/SmartIR#825]
Tested with SmarIR 1.17.6 - Home Assistant 2022.4.4
Using BroadLink RM 4 mini.
[Viessmann-Vitoclima-300-S.zip](https://github.com/smartHomeHub/SmartIR/files/8495915/Viessmann-Vitoclima-300-S.zip)

**Comment by cryogeno** [comment]
Just a little information: in dry mode it's not possible to set a fan speed, so I have used the same codes for low/mid/high/auto fan.

**Comment by vassilis-panos** [comment]
Thanks!
