### ISSUE TITLE
Need HELP with A/C Remote DG11H1-01(E)

### ISSUE THREAD

**Issue by KaportsevIA** [smartHomeHub/SmartIR#827]
Hi, guys!

Need help with wrote JSON file for air Conditioner Ballu A/C Remote DG11H1-01E.
This Remote Partitialy compatible with Hisense DG11R2-01 (JSON File 1522).

But ic't understand structure of this JSON-file.

In my example, read code from original RC through Broadlink RM4C mini

> 
{
  "manufacturer": "Ballu",
  "supportedModels": [
    "DG11H1"
  ],
  "supportedController": "Broadlink",
  "commandsEncoding": "Base64",
  "minTemperature": 18.0,
  "maxTemperature": 28.0,
  "precision": 1.0,
  "operationModes": [
    "heat",
    "cool",
  ],
  "fanModes": [
    "auto"
  ],
  "commands": {
    "off": "JgBgAQABJ5cQORA6DxcPFw8XDxcOFw85ERURORA6DxYPFxAWDxcPFRAWEBYQOg8XDxcOFxIUDxYRFQ86DxcPFw8XEBYPFw84ERURFRAWEBYQFhAWDhgPFREVERUPFxAWEBYQFQ8XEBQOAAEODxcQORA5ERURFREVEBYQFBI4ERUPOhAWDzsPFhAWEBUQFhAWEBURFQ8XEBYPFw8WDxcPFhEVEBYPFw8XDxcOFhEVEBYQOg86EBYPOg8XDxYQFREVEBYQFhAWEBYPFw8VERUQOhAWDzoPOxAVEBcOFhA6EjcPFw8XDxYQOg8XDjkOAAEOEBYPFhAWDxcPFxAWDxcOFhA6DxcPFhAWDxcQFg8XDhYOFhEVDxcPFw8XDhgPFw4WDhYQFg8XDxcPFw4YDhcOFw0WEBYQFhAWERUPFw8XDhYOFhAWDxcPFw8XDxYPFw8WDToPFw8XDxcPFg8XDxcPFg8ADQU=",
    "heat": {
      "auto": {
        "18": "JgBgAQABJpcRORA6DxcPFw8XDhgOFw85EBYQORA6EBYPFhAWEBYPFhAVERURORAWDxcPFw8WEBUQFhAWEBYQFg8WEBYQFg8WEBYQFRAWEBYPFw8XDxcOFhAWEBcPFg8XDxcPFw8XDhUPAAENEBYPOhA5EBYQFhAWEBYPFREVERUQOg87DhgOFw8XDxYPFw8XDxYQFg8XDxcPFhAWDxYQFhAVERUQFhAWEBYPFREWEBYPOhA6DxcOOw8XDhYQFhAWDxcPFw8XDxcOGA4WEDkQFhAWDzoQOg8XDxcPFg86DzoQFhA5EDoPOw8XDhUPAAEMERURFREVEBYQFhAWDxcOFhA6EBYQFRAWEBYQFhAWDxUPFg8WEBYQFhAVEBYQFw8VDhYQFhAWDxYQFhAWEBYPFg4WDxYQFhAWEBYPFw8WEBUOFhAWDxcPFw8XDxcOFw8WDToQFhAWEBURFRAWEBYPFQ8ADQU=",
        "19": "JgBgAQABJpcQORE5EBYPFw8XDxcPFg85EBYQOhA5EBYQFg8XDxcPFhAVEBYQOg8XDxcPFg8XDxYQFhAVEBYQFhA6DxcOGA4WEBYQFg8XDxYQFhAWDxcPFREVERUQFhAWEBYPFw8XDxQPAAENEBYQOg86DxcPFw8XDhgOFhA5EDoQOg86DxcPFw4YDhYQFg8XDxcPFw8XDhgOFw8WEBYPFw8WEBYPFw8XDxYQFRAWEBYQOg86DxcPOhAWDxURFREVERUQFhAWEBYPFw8VEDkRFREVEDoPOw4YDhgOFhAWDxcPFw86DxcPOhAWDxUPAAEMERUQFhAWEBYQFg8WEBcPFRA6DxcPFhAWEBYPFw8WEBUOFhAWEBYPFw8XDxYQFg8WDhUQFhAWEBYQFg8XDxcPFQ4WEBYPFw8XDxcPFw4YDhYOFREVEBYQFg8XDxcPFw8VDzkQFhAVEBYQFhAWEBYPFQ8ADQU=",
        "20": "JgBgAQABJpgQORE5EBUQFhAWEBYQFg88DRYQOg86EBYQFg8XDxcPFRAWDxcPOhAWEBYQFg8XDxURFRAWEBYPFw8XDzoPFw8VERURFRAWEBYQFg8XDxcPFRAXDxYPFxAWDxgPFg4YDhUPAAENDxcPOhA6DxcPFhAWDxcPFhAVERYPOg86DxcPFw8XDhYQFhAWEBYPFw8XDxcPFg8WEBYQFhAWDxYQFhAWDxcPFREVERYPOg86DxgOOw8XDxYQFRAWEBYPFw8XDhgOGA4WEDkQFhAWEDkQOg8XDxcOFhA6DzoQFhA6DzoPFw8XDhYPAAEMEBYPFw8XDxcPFw4YDhgOFhA5EBYQFhAWDxcPFg8YDhYOFREVERUQFhAWEBYPFw4XDhUQFhAVERURFRAWEBYQFQ4WEBYQFRAWEBYQFg8XDxUOFhAWEBYQFg8WEBYQFhAVDjkRFRAWDxcPFw8XDxcOFRAADQU=",
        "21": "JgBgAQABJpgPOg86EBYQFhAWDxcPFw85EBYQORA5ERUQFhAWDxcPFg8XDxcPOhAWEBcOFw8XDxUQFhAWDxcPFw47DzoPGA4WEBYQFg8WEBYQFhAWDxcPFREVERUQFhAWEBYPFw8XDhUPAAEMERYQORA6DxcQFg4YDhgOFhA5EBYPOhA6DxcPFw8WEBYPFhAWEBYQFRAWEBYQFg8VERURFREVEBYQFg8XDxcOFhEVERYPOhA5EBYPOw4YDhYQFw8WDxcPFw8XDhcPFw8WEDkQFg8XDzoQORAWEBYQFRAWEDoPFw86DxcPFw4YDhUPAAEMERUQFhAWEBYPFw8XDxcOFhA6EBYPFw8WDxcPFw8XDxUPFREVEBYQFhAWDxcOGA4WDhYQFREVEBYQFhAWEBYPFQ8WDxYQFhAWEBUQFhAWEBUOFhAWEBYPFw8WEBYQFg8WDjkQFg8XDxcPFw4YDhgOFRAADQU=",
        "22": "JgBgAQABJpcROBE5EBYQFg8XDxYQFw85EBYPOg86EBYQFhAWEBYPFREVERUQORAWEBYQFhAWDxURFREVERUQFhAWEBYPOhAVEBYQFhAWEBUQFhAWDxcPFhAVEBYQFg8XDxcPFw8XDhUQAAEMEBYQORA6DxcPFw8WEBYPFhA5EBcPOhA5EBYQFg8XDxURFRAWEBYQFhAWDxcPFw8VEBYQFg8XDxcPFw4YDhgOFhAWDxcPOg86EBYQOg8XDhcPFhAWEBYPFhAWEBYQFg8WEDoPFw8WEDoPOhAWDxcPFREVEDkRFRA6DzsOOw86DxUPAAENEBYPFw8XDxcOGA4XDxcPFg86DxcPFw8XDxYPFw8XDxYOFRAWEBYPFw8XDxcOGA8VDhYQFREVEBYQGA4WDxcQFA8VERUQFhAWEBYQFg8XDxUOFhAWEBURFg8WEBYQFg8VDzkQFg8XDxcPFw8XDhgOFRAADQU=",
        "23": "JgBgAQABJpcRORA5EBYPFw8XDxcPFw45ERURORA6DxcPFw4XDxcPFhAWDxYQOg8XDxcPFw4YDhYQFhAWDxcPFw86DxcPOg8VERURFRAWEBYPFw8XDxcOFhAWEBYQFg8XDxcPFw8XDhUPAAENEBYPOhA5EBYQFhAWEBYPFREWEDkQOg86EBYPFw8XDxUQFhAWEBYPFw8YDRgOGA4WEBYPFw8XDxcPFw4XDxcRFA8XDxYQOg86EBYQORAWDxYQFREVERUQFhAWEBYPFw8VETkQFhAVEDsOOw8XDxcOFhA5ERUQFhA5EBYQOg87DxQPAAENEBURFREVEBYQFhAWDxcPFRE5EBYQFREVEBcPFhAWExIOFg8XDxYQFhAWDxYQFhAVDhYQFhAWDxcPFw8WEBYPFg4WDxYQFhAWDxcPFw8XDxUOFhAWDxcPFw8XDxcOGA4WDjkQFhAWEBYQFRAWEBYQFA8ADQU=",
        "24": "JgBgAQABJ5cQORA6DxcPFhAWEBcOFw85EBYQOg86EBYQFg8XDxcPFRAWEBYQORAWEBYQFg8XDxURFg8WEBYQFhAWDzoPOw4WEBYQFhAWDxcPFw8WEBcOFhAWEBYQFRAWEBYQFg8XDxUOAAENERUQOg86EBYPFw8XDhgOFw8WEDkRORA6DxcOGA4YDhYQFg8XDxcPFg8XDxcPFw8WDxYQFw8WEBUQFhAWEBYQFRAWEBYQOg86DxcPOg8XDhYQFhAWDxcPFw8XDxcOGA4XDzkQFw8WDzoQOg8XDxcPFhA5EBYPFw86EDkQFw86DxUPAAEMEBYQFw4XDxcPFw8XDhgOFhA5EBYQFg8XDxcPFw8XDhcOFRAWEBUQFhAWDxcPGA4WDhURFRAWEBYQFhAWDxcPFQ4WEBYQFREVEBYQFhAWEBQPFhAWDxcPFw8WEBYPFw8WDTkRFRAWEBYQFg8XDxcPFQ8ADQU=",
        "25": "JgBgAQABKJYRORA5EBYPFw8XDxcPFw45ERUQOhA6DxcPFg8XDxcPFhAVEBYQOg8XDxcPFw4XDxYQFhAWDxYQFhA6DzoQORAVERUQFhAWERUPFw8WEBYQFRAWERQSFBAWDxcRFREVERIRAAELERUSNxI4EBYPFxAWEBYOFhEVETkROBA5ERURFQ8XEBQSFBEVEBYQFhAWEBYPFxAUEhQQFhAWERUPFw8XDhgOFhAWDxcPOhA5ERUQOhAWDxYPFw8WEBYQFhAWEBUQFhAVETkQFg8XDzoROBEVDxcQFBE5ERUQFg86DxcPFw87EBMPAAEMEhQRFREVEBYQFhAWDxcQFBA6ERUQFRAWEBYQFhAWDxUPFRAWEBYQFhAVEBYRFRAVDhYQFhAWDxYQFhAWEBYQFA8VEhQQFhAWDxcQFRAWEBUOFhAWDxcPFw8XDxcOFw8WDToQFhAWEBURFREVEBYQFA8ADQU=",
        "26": "JgBgAQABJpcQORE6DxYQFg8XDxYQFhA5EBYPOhA6DxYQFhAWEBYPFhAVERUQOg8XDxYQFhAWDxYQFREVERUQFhAWEBYQFg85EBYQFhAVERUQFhAXDxYPFREVERUQFhAWDxcPFw8XDhUQAAEKExUQORA6DxcPFw8XDxcOFhAWEDkQOhA6DxYQFg8YDhYQFRAWEBYQFhAWDxcPFw8VEBYQFhAWDxcPFw4YDxcOFhAWDxcPOhA5EBYQOg8XDhcPFhAWEBYPFw8WEBYQFg8WEDoPFhAXDzoPOhAWDxcPFRE5EBYQFg86DzsPOg8XDzgPAAENEBYPFw8XDxcOGA4XDxcPFg86EBYPFw8XDxYPFw8XDxYOFREVEBYQFhAWDxcPFw4WDhYQFREVERUQFhAWEBYPFQ8WEBUQFhAWEBYQFg8XDxUOFhAWEBYQFRAWEBYQFg8WDjkQFhAWDxcPFw8XDhgOFRAADQU=",
        "27": "JgBgAQABJpcRORA5EBYQFg8XDxcPFw46EBYQORA6DxcPFw8XDhgOFhAWEBYPOg8XDxcPFw8XDhYQFhAWEBYPFw86DxcPFw46EBYQFhAWDxcOFw8XDxcPFg8XDxcPFhAWDxcPFw8XDhUPAAENEBYQORA6EBYPFhAWEBcOFhA6DzoPOhA6DxcPFw8WDxYQFhAWEBUQFhAWEBYQFg8VERURFRAXDxYQFg8XDxcOFhAWEBYPOhA6DxcPOw4YDhYQFg8XDxcPFw4YDhcPFw8WDzoPFw8XDzoQORAWEBYPFhAVERURFRA6DxcPOw4YDjgPAAENEBYQFhAVERUQFhAWEBYPFhA5EBYQFhAWDxYQFhAWEBUOFhAWDxcPFw8WEBYPFw8WDRYQFhAWEBYPFw8XDxYPFg4WDxcPFw8XDxYPFw8XDxYNFhAWEBYPFw8XDxcPFw4WDjkRFg8WEBYQFhAWDxcPFQ8ADQU=",
        "28": "JgBgAQABJ5cQOg86EBYPFw8XDxcOGA45ERUQORE6DxcPFg8XDxcPFg8XDxYQOg8XDxcOGA4XDxYQFg8XDxYQFhAWDzsOGA45ERUQFhAWDxcPFw8XDhgOFhAWEBYPFw8XDxcPFw4XDxUOAAEODxcPOhA5EBYQFhAWDxcPFRE5EDkQOhA5EBYPFw8XDxURFRAWEBYQFhAWDxcPFw8VERUQFhAWDxcPFw4XDxgOFhAWDxcPOhA5EBYQOg8XDhYQFhAWEBYPFw8WEBYQFg8WEDkQFhAWEDoPOhAWDxcPFREVEBYQFhA5EDoPFw8XDjkPAAEMERURFRAWEBYQFhAWDxcPFRA5ERURFRAWEBYQFg8XDxUOFhAWEBYQFg8WEBYQFhAVDhYQFg8XDxcPFhAWDxcPFg0WEBYQFhAWDxcPFw8WDxYOFg8XDxcPFw8WDxgOFw8WDjkQFREVERUQFhAWEBYQFA8ADQU=",
      }
    },
    "cool": {
      "auto": {
        "18": "JgBgAQABJ5gQORA5ERUQFhAWEBYPFw85EBYQOg86EBYQFg8XDxcOFhAWERUQORAWEBYPFw8XDxURFRA5EBYRFREVERUPFxAUERURFREVEBYQFhAWEBYPFREVERUPFxAWERUPFw8XDxQPAAEMEhQSOBE4ERURFRAWEBYQFREUERURFREVETkQFQ8XERQRFBMUEBURFREVEBYQFhAUEhQRFREVERURFRAWEBYQFBIUERUROBE5ERQROREVEBQSFBIUEhQRFREVERUQFREUEjgRFREVETgROBEVEBYQFBI4EhQSNxIUDxcROBEWEBMRAAELEhUQFBEVERURFREVEBYQFBI4ERURFBEVERURFREVDxYQFA8WEhQSFBEVDxcQFREUEBQSFA8XERURFREUERURFA8UEhQSFBIUERURFREVERMQFBIUDxcRFREVEBYOGBAUDjkQFhEVERUQFREVERUREw8ADQU=",
        "19": "JgBgAQABKJcROBE4EhQQFhEVERURFQ86DxcPOhA5EBYQFhAWDxcPFREVEBYPOhAWEBYQFg8XDxURFRE5EBYPFhA6DxcPFw8WDxYQFhAWDxcOFxAWEBYPFhEVEBURFRAWEBYQFhAWDxQQAAEMEhQQOg86DxcQFg8XEBYOFhEVEBYQFhAWEDkQFhAWDxUQFhAWERUPFxAWDxcQFg4WERURFREVDxYQFxAVERUQFREUEhQROQ87DxcPOhAWEBQRFRAWERUQFhAWDxcPFw8VETgSFBAWETgRORAWEBYPFg86EBYQOREVETkQORAWDxQRAAELEhQQFhAWEBYQFg8XDxcPFRE4EhQQFhEVEBYQFg8XDxUNFxEUEhQRFQ8XERUQFg8VDxYPFhAWEBYQFg8XDxYRFA4WERUQFhAWDxcQFQ8XEBUOFRIUEBYQFg8XDxcPFw8VDzgRFREVEBYQFhAWEBYPFBAADQU=",
        "20": "JgBgAQABJ5cRORA6DxcPFw4YDhcPGA45EBYQORA6DxcPFw8XDxYPFhAWEBYQORAWDxcPFw8XDhcPFhA6DxcPFw47DxcPFw8WDxYQFhAWDxcPFw4YDhgOFhAWDxcPFw8XDhgOFw8XDxUOAAENEBYQORE5EBYPFw8WEBYQFRAWEBURFREVEDoPFw8XDxYQFRAWEBYQFhAVEBYQFw8VEBYQFhAWDxYQFg8XDxcPFg8XDxcPOhA5EBYQOg8XDhYQFhAWDxcPFw8WEBYPFw8WEDkQFhAWDzoQOg8XDxcPFRE5EBYPOg8XDzoQOg8XDxUOAAENEBYQFg8XDxcPFw8WDxcPFhA5EBYQFg8XDxcPFw8XDhYOFg8XDxYQFhAWDxcPFw8WDhUQFhAWDxcPFw8XDhgOFg4VERURFREVEBYQFg8XDxUPFREVEBYQFhAWDxcPFw8VDjkQFhAWEBYPFw8XDxcPFQ4ADQU=",
        "21": "JgBgAQABJpkPOhA5EBYQFhAWDxcPFw85EBYQORA5ERUQFhAWDxcPFg8WEBcPOhAWDxcPFw8XDxUQFhA5EBYQFhA6DzoPFw4WEBYQFhAWDxcPFw8XDxcOFhAWEBYQFg8XDxYQFg8XDxUOAAEOEBYPOg86EBYQFhAWDxcPFRE5EBYQFRAXDzoPFw8XDxUQFhAWEBYQFRAWEBYQFg8WEBURFREVEBYQFhAWEBYPFREVEBYQORE6DxcOOw4YDhYQFhAWDxcPFw8XDhgOFw8WEDkQFg8XDzoQOg8XDxYQFRAWEBYQOg8XDzoPFw4YDhUPAAEMERURFREVEBYQFg8XDxcOFhA6EBYQFREVEBYQFhAWDxUPFREVEBYQFhAWDxYQFw8VDhYQFhAWDxYQFhAWEhQPFQ8WDxcPFw8WEBYPFw8WEBYNFhAWEBYPFw8XDxcPFg8WDjkQFhAWEBYQFg8WEBYQFBAADQU=",
        "22": "JgBgAQABJ5YROBI4ERURFQ4XERURFRE4ERUQORA5ERURFREVDxcQFBIUEhQQORAWERURFREVDxUSFBI4ERUQFhAVERURORAVERUQFhAWEBUPFxAWEBYQFBAWERURFREUEBYRFREVERMQAAELEhQSOBE4ERUQFhEVEBYPFRE5ERURFREVDzoPFxAWEBQSFBAWERURFREVEBYQFhAUERURFREVEBYPFhAWEBYQFQ8XEBYQORE4ERURORAWDhYRFREVERUPFxAVERUQFhAVETgRFREVEDoPOg8XEBYQFBIUEBYROBEVERURORA5EBQQAAELEhQSFBAWERURFRAWDhgQFBE4EhQQFhEVERURFQ8XEBQOFhEVERURFBAWERURFREUDxURFREVEBYQFREVDxcQFQ4VERURFQ8XEBYQFhAVDxYPFQ8XEBYQFREVDxcQFhAVDzgRFREUEhQPFxEVERUQFBAADQU=",
        "23": "JgBgAQABJ5YRORA5EBYRFREVERUPFxA3EhQSOBE5EBYQFg4XEBcPFREVEBYQOREVEBYPFxAWDxURFRA5EBYRFRE4ERURORAUEBcQFRIUERUQFhAVERYQFBEVERURFBEVERURFREVEBQQAAELEhQRORA5EBYRFREVEBYPFRE4EhQSFBEVETkQFhAWEBQRFREVERURFBEVERURFREUEBYRFBIUERUQFhAWEBYQFBEVERURORE5EBUQOg8XDxURFREVEBYQFhAVERUQFhAVETgRFREVEDkPOw4YEBYQFBEVERURORAVETkQORE5EBQPAAEMERURFQ8XEBYQFhAVDxcQFRE4ERURFQ8XEBYQFhAVDhcPFBAWERURFQ8XEBYQFhAUEBQSFBAWERUQFhAWDhgPFQ4VEhQSFBEVDxcRFRAWEBQQFBAWERURFREUEBYRFREUDzgRFREVERUPFxAWEBYQFA8ADQU=",
        "24": "JgBgAQABJpcQORE4ERUQFhAWEBYQFg85ERQSOBA6DxcPFg8XDxcPFg8XDxcPOhAWDxcQFg4YDhYQFhE4ERUQFhAWEDoPOg8VEBYQFhAWDxcPFw8WEBYPFhEVERURFBEVERURFRAWEBQQAAEMERUPOhE4EBYQFhAWDxcPFRE5ERQRFg8WEDoQFhAWEBUPFhEVERURFBEVERUQFhAVEBURFREVEBYQFhAWDxcPFREVERUQOhA5EBYPOw4YDhYQFhEVERUPFw8XDxYPFw8WEDkQFhAWDzoQOg8XDxcPFRAWEBYQOg8WEBYPFw87DhUPAAENEBYQFhAVEBYPFw8XDxcPFhE4EBYQFhAWDxYQFg8XDxUPFREVEBYQFhAWEBYPFw8VDhYQFhEUERUQFhEVEBYQFA8WEBYQFRAWERUQFhAWDxUQFBEVERUPFxAWDxYQFg8WEDcSFBAWERUQFhEVDxcQExEADQU=",
        "25": "JgBgAQABKJcQORE5EBYQFRAWEBYQFg86EBYPOg86EBYQFhAWDxcPFREVEBYQORAWEBYQFhAWDxURFRE5EBYQFRA7DjsPOg8VERURFRAWEBYQFhAWDxcPFRIUEBYQFhEVDxcPFw4YEBMPAAENEBUSOBA6DxcPFw8WEBYQFREVDzoPFw8XETgQFhAWDxURFRAWEBYPFxEVERURFQ4WEBYQFhAWERUQFg8WDxcQFREVERUPOg86EBYQORAXDxURFRAWERUQFhAWDxcPFw8VEDoPFhAWEDoPOhAWDxcPFRA6EDoPOg8XDzoQFhA5EBUOAAENEBYQFg8XDxcPFhAWDxcPFhA5EBYQFg8XDxcPFw4XDxYOFRAWEBYQFg8XDxcPFw8VDxURFRAWEBYPFw8XDhgOFg4VERURFRAWEBYQFhAWDxUPFRAWEBYQFREVEBYQFhAVDjkQFhAWEBYPFw8XDxcPFA8ADQU=",
      }
    },
  }
}
but integrations in Home Assistant not correct works
![Снимок экрана 2022-04-17 214631](https://user-images.githubusercontent.com/98884453/163728222-51d2dc4d-ce92-4207-9915-06621012a54e.png)
to many support modes, and they not work.

But, scripts for service Remote: Send Command in bottom of screen shoot perfect working (without sync with climate service)

**Comment by danilovvs** [comment]
I have the same remote. Did you manage to solve the problem?
