### ISSUE TITLE
Midea MSAG-12HRN1 .json conf file

### ISSUE THREAD

**Issue by stiw47** [smartHomeHub/SmartIR#846]
Hi Vassilis,

Please find conf file for Midea MSAG-12HRN1
This is without swing. I am still struggling to make it work properly with swing, with current .json structure, if I make success, I will send you new file. Btw, I am also agree with guys in issue #746 that would be awesome if we could have simple swing switch, which would be independent of mode, temp, fun speed... but hey, this is up to you, your time and your free will - thank you anyway for this custom integration as it is 😍😍.

[1388.zip](https://github.com/smartHomeHub/SmartIR/files/8699049/1388.zip)

Btw, I already posted before, another conf file for another AC model here: #735 😎😎

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
