### ISSUE TITLE
Code 1764 for Daitsu DS-12KIDC(WD)

### ISSUE THREAD

**Issue by Adrian1984-es** [smartHomeHub/SmartIR#848]
After installing this integration to Home Assistant i found out that my AC is missing in the list. 
I create a new file with all codes for it "1764.json".
Hope this would help. I've tested it and it works fine now with my model.

I had to change the file to *.txt. 
*.json was not allowed to send it on this issue. Hope that would help to make the list for this great integration a little bigger an better.

Thank you,

[1764.txt](https://github.com/smartHomeHub/SmartIR/files/8741923/1764.txt)
.

**Comment by liuk4friends** [comment]
Hi,
how did you get your AC codes?
I have three Daitsu DSM-9KIDT(W) and one Daitsu DS-12KIDT-2(W).

I'm testing right now 1762.json with DS-12KIDT-2(W).

The basic functions seem ok (shutdown, heat, cool, dry, fan and temperature regulation). 
However, some important functions are missing, such as the "ECO" button.

**Comment by vassilis-panos** [comment]
Thanks
