### ISSUE TITLE
New AC model: Mitsubishi Electric MSZ-HR25VF

### ISSUE THREAD

**Issue by YerayOrtiz** [smartHomeHub/SmartIR#849]
Hi! I found out that my AC is missing in the list.
I create a new file with all codes for it "Mitsubishi Electric MSZ-HR25VF".
Hope this would help. I've tested it and it works fine now with my model.

I had to change the file to *.txt.
*.json was not allowed to send it on this issue. Hope that would help to make the list for this great integration a little bigger an better.
[Mitsubishi Electric MSZ-HR25VF.txt](https://github.com/smartHomeHub/SmartIR/files/8743331/Mitsubishi.Electric.MSZ-HR25VF.txt)

Thank you,

**Comment by vassilis-panos** [comment]
You need to set the temperatures for dry and fan_only modes.

**Comment by YerayOrtiz** [comment]
Hi!

My AACC doesn't have temperatures for these two modes. When you set dry mode or fan_only, temperature set number dissappears.

Thank you

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
