### ISSUE TITLE
KaisaiEco KEM-09KTA

### ISSUE THREAD

**Issue by JimmiJonathan** [smartHomeHub/SmartIR#855]
Hello, 
I'm trying to add integration based on another AC to run with my Kaisai (I can share with you when i'm done :) ). Can You tell me how to write IR code when in Mode Auto and Dry there is only one fan speed - Auto. 
And in Swing mode is on/off only - I must add every temperature  with or without swing or can i add button to enable it ? 

Very good job with this integration ! 
Thanks !

**Comment by vassilis-panos** [comment]
You need to repeat the same command.
For the swing you must add every temperature with or without swing.
