### ISSUE TITLE
Add more FAQ

### ISSUE THREAD

**Issue by pawel-jurczyk** [smartHomeHub/SmartIR#868]
I like the project, thank you for creating and maintaining it.

I would like to know what's the desired behaviour of the climate control.
If I set the temp to 22, mode to cool and the temperature is reporting a 21, the AC unit should be shut down until the temperature jumps back above 22? I don't experience this currently, but I would expect it to work this way.

Is there a simpler way of obtaining the IR codes other than tapping over 900 times on the remote? I'm currently using the broadlink to learn the codes, but it's tedious AF. 

I'm hoping there is a source of codes somewhere, also some that maybe are not coded into this remote, but some service remote, like to switch the feedback sound off :D (I have the AC unit in my bedroom)

**Comment by pawel-jurczyk** [comment]
I actually found a pretty fast way of obtaining the codes. You can use the home assistant scripts folder to define a sequence of ir codes to learn, like here https://www.home-assistant.io/integrations/broadlink/#learning-a-sequence-of-commands I defined all temperatures from 16 to 32 with 0.5 precision and it takes 30 seconds to go through them 😄

**Comment by auanasgheps** [comment]
@pawel-jurczyk THANK YOU FOR THIS TIP! It's great!
