### ISSUE TITLE
Suggestion: Discussions for templates

### ISSUE THREAD

**Issue by newhinton** [smartHomeHub/SmartIR#879]
Hello, 

you have closed multiple PR's containing requests for mqtt controller. I understand and agree that it would not be helpful due to compatibility reasons. However, would it be possible to enable the Discussions-Feature on this repostitory and create a place to Post configs? This way people have a chance to post specific device configurations in the hope that it may help someone else.

**Comment by vassilis-panos** [comment]
Activated. Let's see how it goes
