### ISSUE TITLE
Not registering in home assistant (?)

### ISSUE THREAD

**Issue by Doomsdayrs** [smartHomeHub/SmartIR#896]
I added SmartIR via HACS

It does not show up as an integration
Attempting to add it to the configuration file leads to the "check configuration" loading forever, and the restart button being disabled.

**Comment by jakkra** [comment]
I have the same issue:
```
Home Assistant Core 2022.6.7
Home Assistant Supervisor 2022.07.0
Home Assistant OS 8.2
Path to configuration.yaml: /config

Frontend version: 20220601.0 - latest
```
