### ISSUE TITLE
Convert Codes from ini to json

### ISSUE THREAD

**Issue by ekkesa** [smartHomeHub/SmartIR#9]
Hi,

Could you please convert and add these to the repo - Thank you!

[alliance_aircon.zip](https://github.com/smartHomeHub/SmartIR/files/2895375/alliance_aircon.zip)
[phillipsHTS.zip](https://github.com/smartHomeHub/SmartIR/files/2895377/phillipsHTS.zip)
[lg42tv.zip](https://github.com/smartHomeHub/SmartIR/files/2895378/lg42tv.zip)

**Comment by ekkesa** [comment]
This might be additional info you need:

- platform: broadlink
  name: Living Room Airconditioner
  host: 192.168.x.x
  mac: '34:EA:34:58:C7:2C'
  ircodes_ini: 'broadlink_climate_codes/alliance_aircon.ini'
  min_temp: 17
  max_temp: 30
  target_temp: 20
  target_temp_step: 1
  temp_sensor: sensor.living_room_temperature
  default_operation: 'off'
  default_fan_mode: low
  customize:
    operations:
      - 'off'
      - cool
      - heat
      - dry
      - fan
      - auto
    fan_modes:
      - low
      - mid
      - high
     
- platform: broadlink
  name: Master Bedroom Airconditioner
  host: 192.168.x.x
  mac: '34:EA:34:58:BB:CB'
  ircodes_ini: 'broadlink_climate_codes/alliance_aircon.ini'
  min_temp: 17
  max_temp: 30
  target_temp: 20
  target_temp_step: 1
  default_operation: 'off'
  default_fan_mode: low
  customize:
    operations:
      - 'off'
      - cool
      - heat
      - dry
      - fan
      - auto
    fan_modes:
      - low
      - mid
      - high

**Comment by smartHomeHub** [comment]
The Alliance AC was added. The device code is 1450. I want to ask you how you handle the extra Surround, Eject etc commands in Philips HTS.

**Comment by ekkesa** [comment]
Thank you for the aircon codes.

I ommitted them, since logically tou have to be in physical close proximity to insert/remove a disc. It is connected to my TV and use it for music / surround sound on the TV.

The TV has all the discreet codes I could get for the LG TV to function.

**Comment by smartHomeHub** [comment]
> Thank you for the aircon codes.
> 
> I ommitted them, since logically tou have to be in physical close proximity to insert/remove a disc. It is connected to my TV and use it for music / surround sound on the TV.
> 
> The TV has all the discreet codes I could get for the LG TV to function.

I mean, what's the reason for these codes? The component ignores them.

**Comment by ekkesa** [comment]
Never really used them - When creating the ini files I just captured as much data as possible. I figured if I capture all commands now, I can always use them as reference for future use somewhere.

**Comment by hmmkash** [comment]
Anyone has the Sony Tv codes ?
Thanks

**Comment by smartHomeHub** [comment]
Here are your LG TV codes. While I'm converting your Philips codes I found that channel 1 and channel 2 commands are the same.
[1040.zip](https://github.com/smartHomeHub/SmartIR/files/2897227/1040.zip)

**Comment by ekkesa** [comment]
I will recapture the Phillips Channel 1 /2 - Could you please post the phillips json in the time being with the duplicate codes. I mainly use power and volume and would like to get everything to function again.
Thank you.

**Comment by smartHomeHub** [comment]
Here it is
[0.zip](https://github.com/smartHomeHub/SmartIR/files/2900904/0.zip)

**Comment by ekkesa** [comment]
Thank you - I will post the correct codes ASAP.
