### ISSUE TITLE
Add support for Mitsubishi Electric MSY-GM18VA, MSY-GE10VA, MSY-GH13VA (.json attached)

### ISSUE THREAD

**Issue by junknstuff** [smartHomeHub/SmartIR#922]
Created and tested for (3) similar Mitsubishi Electric models:
MSY-GM18VA, MSY-GE10VA, MSY-GH13VA

Presently, only includes "Operation Mode: Cool" with 4 "Fan Modes: Low, Mid, High, Highest"

Future update will include "Operation Mode: Auto"

[1135.zip](https://github.com/smartHomeHub/SmartIR/files/9248255/1135.zip)

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
