### ISSUE TITLE
add AC Hokkaido HKEU series - file attached

### ISSUE THREAD

**Issue by poliant** [smartHomeHub/SmartIR#924]
**Home Assistant version** 2022.3.6

**SmartIR version** 1.17.6

**SmartIR configuration** Base64 broadlink

**Additional context**

Please add the configuration file for AC Hokkaido HKEU series (for broadlink).
For this first release I've defined the most common modes (cool, dry, heat) and only with fan auto; for next release I'm planning to include mode fan modes.
[2190.json.txt](https://github.com/smartHomeHub/SmartIR/files/9259238/2190.json.txt)

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
