### ISSUE TITLE
add support for Mitsubishi AC SRK--ZMP-S serie (RKX502A007P remote control)

### ISSUE THREAD

**Issue by Uraeus82** [smartHomeHub/SmartIR#931]
**Home Assistant version** 2022.6.7

**SmartIR version** 1.17.6

**SmartIR configuration** Base64 broadlink

**Additional context**

Created and tested by learning IR code of a RKX502A007P remote controller:
For the Mitsubishi AC SRK--ZMP-S serie ( SRK25ZMP-S, SRK35ZMP-S, SRK45ZMP-S)

Presently, includes "Operation Mode: Cool, Heat, Auto and Fan" with 4 "Fan Modes: Low, Mid, High, Auto"
With only the Swing mod

I propose the number code number 1136
[1136.zip](https://github.com/smartHomeHub/SmartIR/files/9320648/1136.zip)

**Comment by vassilis-panos** [comment]
Thanks!
