### ISSUE TITLE
New Samsung code and file

### ISSUE THREAD

**Issue by dankarization** [smartHomeHub/SmartIR#936]
This file has all modes, all fan speeds (including eco and turbo) and both swing and stop options. Should work with AR**TSHZ**** models

[1403.zip](https://github.com/smartHomeHub/SmartIR/files/9384035/1403.zip)
>

**Comment by auanasgheps** [comment]
Hi, you have to open a pull request and rename the file, 1403 is already used, go for 1404 :)

**Comment by dankarization** [comment]
I wish I knew how to do this.... can just someone pull for me?

**Comment by auanasgheps** [comment]
Sure. I will do and mention you.

**Comment by dankarization** [comment]
ty
