### ISSUE TITLE
How can I submit a new Climate control JSON File

### ISSUE THREAD

**Issue by lmath56** [smartHomeHub/SmartIR#948]
**Home Assistant version**

Home Assistant 2022.9.2 
Supervisor 2022.08.6 
Operating System 8.5 
Frontend 20220907.0 - latest 

**SmartIR version**

1.17.6

**SmartIR configuration**

```yaml
see attachment

```

**Describe the bug**

No Bug

**Debug log**

```text

No Logs

```

**Additional context**

I have created a .json file for the below three Hitachi Air conditioner models:
RAS-E25YHAB
RAS-E35YHAB
RAS-E50YHAB

I am not particularly sure where to submit it, I am not great at GitHub..
I have uploaded the file. Change the extension to .json

I initially tried using code file 1082 however it did not work, the codes are completely different. I modified the 1082.json file to create the .json file for my aircon model.

I am using the .json I created with my Aircon now.

Possibly needs some changes. I am not too sure how far I can modify the config:

- The dry mode only has a low and quiet setting, I have added the codes from low speed setting to the auto, high, and medium speed settings
- The fan only mode only does not have temperature control, only the fan speeds quiet, low, medium, and high - no auto mode. I have put the same codes for each speed for each temperature code.
- I added the auto fan speed setting. Seems to work however in the Thermostat Card it shows some kind of calendar icon instead.

Happy to make any changes myself if required or post elsewhere. 

Thanks.
[Hitachi.txt](https://github.com/smartHomeHub/SmartIR/files/9556243/Hitachi.txt)

**Comment by vassilis-panos** [comment]
Ευχαριστώ. Προστέθηκε με τον κωδικό 1087.

**Comment by vassilis-panos** [comment]
Thanks. Added with code 1087.
