### ISSUE TITLE
Add New Device - AC Ballu and compatible remote (DG11H1-01E)

### ISSUE THREAD

**Issue by KaportsevIA** [smartHomeHub/SmartIR#996]
Please ADD AC Remote DG1
[dg11h1_commands.txt](https://github.com/smartHomeHub/SmartIR/files/10325391/dg11h1_commands.txt)
1H1-01(E) Codes in attachments

**Comment by vassilis-panos** [comment]
You should open a pull request by providing the json file. For this reason this issue will be closed. However, we have saved your file and depending on our workload we may add it in the future. Thanks for your valuable input.
